using System.Collections.ObjectModel;
using Dreamine.MVVM.ViewModels;

namespace DreamineWeb.ViewModels.Demos;

/// <summary>
/// \if KO
/// <para>Controls Showcase View Model 기능과 관련 상태를 캡슐화합니다.</para>
/// \endif
/// \if EN
/// <para>ViewModel for the controls showcase live demo. This browser-friendly version mirrors the ControlsViewModel / ControlsEvent shape from SampleCrossUi.Shared. In the real sample, logic lives in ControlsEvent and members are generated by [DreamineCommand]/[DreamineProperty].</para>
/// \endif
/// </summary>
public sealed class ControlsShowcaseViewModel : ViewModelBase
{
    // ── Button ────────────────────────────────────────────
    /// <summary>
    /// \if KO
    /// <para>Click Count 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the click count value.</para>
    /// \endif
    /// </summary>
    public int ClickCount { get; private set; }
    /// <summary>
    /// \if KO
    /// <para>Activity Log 값을 가져옵니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets the activity log value.</para>
    /// \endif
    /// </summary>
    public ObservableCollection<string> ActivityLog { get; } = new();

    /// <summary>
    /// \if KO
    /// <para>Click Me 작업을 수행합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Performs the click me operation.</para>
    /// \endif
    /// </summary>
    public void ClickMe()
    {
        ClickCount++;
        ActivityLog.Insert(0, $"[{DateTime.Now:HH:mm:ss}] Clicked ({ClickCount})");
        while (ActivityLog.Count > 8) ActivityLog.RemoveAt(ActivityLog.Count - 1);
        Raise();
    }

    // ── CheckBox ──────────────────────────────────────────
    /// <summary>
    /// \if KO
    /// <para>check1 And check2 And check3 값을 보관합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Stores the check1 and check2 and check3 value.</para>
    /// \endif
    /// </summary>
    private bool _check1 = true, _check2, _check3;
    /// <summary>
    /// \if KO
    /// <para>Check1 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the check1 value.</para>
    /// \endif
    /// </summary>
    public bool Check1 { get => _check1; set { _check1 = value; Raise(); } }
    /// <summary>
    /// \if KO
    /// <para>Check2 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the check2 value.</para>
    /// \endif
    /// </summary>
    public bool Check2 { get => _check2; set { _check2 = value; Raise(); } }
    /// <summary>
    /// \if KO
    /// <para>Check3 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the check3 value.</para>
    /// \endif
    /// </summary>
    public bool Check3 { get => _check3; set { _check3 = value; Raise(); } }

    // ── RadioButton ───────────────────────────────────────
    /// <summary>
    /// \if KO
    /// <para>Selected Radio 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the selected radio value.</para>
    /// \endif
    /// </summary>
    public string SelectedRadio { get; private set; } = "Option A";
    /// <summary>
    /// \if KO
    /// <para>Select Radio 작업을 수행합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Performs the select radio operation.</para>
    /// \endif
    /// </summary>
    /// <param name="option">
    /// \if KO
    /// <para>option에 사용할 <c>string</c> 값입니다.</para>
    /// \endif
    /// \if EN
    /// <para>The <c>string</c> value used for option.</para>
    /// \endif
    /// </param>
    public void SelectRadio(string option) { SelectedRadio = option; Raise(); }

    // -- CheckLed (Dreamine signature control) -------------
    /// <summary>
    /// \if KO
    /// <para>Led Is On 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the led is on value.</para>
    /// \endif
    /// </summary>
    public bool LedIsOn { get; private set; } = true;
    /// <summary>
    /// \if KO
    /// <para>Led Is Pulse 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the led is pulse value.</para>
    /// \endif
    /// </summary>
    public bool LedIsPulse { get; private set; }
    /// <summary>
    /// \if KO
    /// <para>Toggle Led 작업을 수행합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Performs the toggle led operation.</para>
    /// \endif
    /// </summary>
    public void ToggleLed() { LedIsOn = !LedIsOn; Raise(); }
    /// <summary>
    /// \if KO
    /// <para>Toggle Pulse 작업을 수행합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Performs the toggle pulse operation.</para>
    /// \endif
    /// </summary>
    public void TogglePulse() { LedIsPulse = !LedIsPulse; Raise(); }

    // ── TextBox / PasswordBox ─────────────────────────────
    /// <summary>
    /// \if KO
    /// <para>text Input 값을 보관합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Stores the text input value.</para>
    /// \endif
    /// </summary>
    private string _textInput = string.Empty;
    /// <summary>
    /// \if KO
    /// <para>password 값을 보관합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Stores the password value.</para>
    /// \endif
    /// </summary>
    private string _password = string.Empty;
    /// <summary>
    /// \if KO
    /// <para>Text Input 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the text input value.</para>
    /// \endif
    /// </summary>
    public string TextInput { get => _textInput; set { _textInput = value; Raise(); } }
    /// <summary>
    /// \if KO
    /// <para>Password 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the password value.</para>
    /// \endif
    /// </summary>
    public string Password { get => _password; set { _password = value; Raise(); } }
    /// <summary>
    /// \if KO
    /// <para>Clear Text 작업을 수행합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Performs the clear text operation.</para>
    /// \endif
    /// </summary>
    public void ClearText() { _textInput = string.Empty; Raise(); }
    /// <summary>
    /// \if KO
    /// <para>Clear Password 작업을 수행합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Performs the clear password operation.</para>
    /// \endif
    /// </summary>
    public void ClearPassword() { _password = string.Empty; Raise(); }

    // ── ComboBox ──────────────────────────────────────────
    /// <summary>
    /// \if KO
    /// <para>Fruit Items 값을 가져옵니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets the fruit items value.</para>
    /// \endif
    /// </summary>
    public string[] FruitItems { get; } = { "Apple", "Banana", "Cherry", "Grape", "Mango", "Melon" };
    /// <summary>
    /// \if KO
    /// <para>selected Fruit 값을 보관합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Stores the selected fruit value.</para>
    /// \endif
    /// </summary>
    private string _selectedFruit = "Cherry";
    /// <summary>
    /// \if KO
    /// <para>Selected Fruit 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the selected fruit value.</para>
    /// \endif
    /// </summary>
    public string SelectedFruit { get => _selectedFruit; set { _selectedFruit = value; Raise(); } }

    // ── Expander ──────────────────────────────────────────
    /// <summary>
    /// \if KO
    /// <para>is Expanded 값을 보관합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Stores the is expanded value.</para>
    /// \endif
    /// </summary>
    private bool _isExpanded = true;
    /// <summary>
    /// \if KO
    /// <para>Is Expanded 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the is expanded value.</para>
    /// \endif
    /// </summary>
    public bool IsExpanded { get => _isExpanded; set { _isExpanded = value; Raise(); } }
    /// <summary>
    /// \if KO
    /// <para>Toggle Expand 작업을 수행합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Performs the toggle expand operation.</para>
    /// \endif
    /// </summary>
    public void ToggleExpand() { _isExpanded = !_isExpanded; Raise(); }

    // ── Numeric (0~100 clamp) ─────────────────────────────
    /// <summary>
    /// \if KO
    /// <para>numeric Input 값을 보관합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Stores the numeric input value.</para>
    /// \endif
    /// </summary>
    private double _numericInput = 50;
    /// <summary>
    /// \if KO
    /// <para>Numeric Input 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the numeric input value.</para>
    /// \endif
    /// </summary>
    public double NumericInput
    {
        get => _numericInput;
        set { _numericInput = Math.Clamp(value, 0, 100); Raise(); }
    }

    // -- ListBox (selection + double-click activation) -----
    /// <summary>
    /// \if KO
    /// <para>List Activated 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the list activated value.</para>
    /// \endif
    /// </summary>
    public string ListActivated { get; private set; } = "(double-click an item)";
    /// <summary>
    /// \if KO
    /// <para>Activate List Item 작업을 수행합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Performs the activate list item operation.</para>
    /// \endif
    /// </summary>
    /// <param name="item">
    /// \if KO
    /// <para>item에 사용할 <c>string</c> 값입니다.</para>
    /// \endif
    /// \if EN
    /// <para>The <c>string</c> value used for item.</para>
    /// \endif
    /// </param>
    public void ActivateListItem(string item) { ListActivated = $"Activated: {item}"; Raise(); }

    // ── Counter ──────────────────────────────────────────
    /// <summary>
    /// \if KO
    /// <para>count 값을 보관합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Stores the count value.</para>
    /// \endif
    /// </summary>
    private int _count;
    /// <summary>
    /// \if KO
    /// <para>Count 값을 가져옵니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets the count value.</para>
    /// \endif
    /// </summary>
    public int Count => _count;
    /// <summary>
    /// \if KO
    /// <para>Counter Logs 값을 가져옵니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets the counter logs value.</para>
    /// \endif
    /// </summary>
    public ObservableCollection<string> CounterLogs { get; } = new();

    /// <summary>
    /// \if KO
    /// <para>Increment 작업을 수행합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Performs the increment operation.</para>
    /// \endif
    /// </summary>
    public void Increment()
    {
        _count++;
        CounterLogs.Insert(0, $"[{DateTime.Now:HH:mm:ss}] Incremented → {_count}");
        while (CounterLogs.Count > 10) CounterLogs.RemoveAt(CounterLogs.Count - 1);
        Raise();
    }

    /// <summary>
    /// \if KO
    /// <para>Reset Counter 작업을 수행합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Performs the reset counter operation.</para>
    /// \endif
    /// </summary>
    public void ResetCounter()
    {
        _count = 0;
        CounterLogs.Insert(0, $"[{DateTime.Now:HH:mm:ss}] Counter reset.");
        while (CounterLogs.Count > 10) CounterLogs.RemoveAt(CounterLogs.Count - 1);
        Raise();
    }

    // -- DataGrid (static demo data) -----------------------
    /// <summary>
    /// \if KO
    /// <para>Grid Rows 값을 가져옵니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets the grid rows value.</para>
    /// \endif
    /// </summary>
    public ObservableCollection<GridRow> GridRows { get; } = new()
    {
        new() { No = 1, Name = "Device A", Status = "Running" },
        new() { No = 2, Name = "Device B", Status = "Stopped" },
        new() { No = 3, Name = "Device C", Status = "Running" },
        new() { No = 4, Name = "Device D", Status = "Error" },
    };

    /// <summary>
    /// \if KO
    /// <para>selected Row 값을 보관합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Stores the selected row value.</para>
    /// \endif
    /// </summary>
    private GridRow? _selectedRow;
    /// <summary>
    /// \if KO
    /// <para>Selected Row 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the selected row value.</para>
    /// \endif
    /// </summary>
    public GridRow? SelectedRow { get => _selectedRow; set { _selectedRow = value; Raise(); } }

    // -- TimeSpinner (time selection) ----------------------
    /// <summary>
    /// \if KO
    /// <para>hours And minutes And seconds 값을 보관합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Stores the hours and minutes and seconds value.</para>
    /// \endif
    /// </summary>
    private int _hours = 9, _minutes = 30, _seconds = 0;
    /// <summary>
    /// \if KO
    /// <para>Hours 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the hours value.</para>
    /// \endif
    /// </summary>
    public int Hours { get => _hours; set { _hours = Math.Clamp(value, 0, 23); Raise(); } }
    /// <summary>
    /// \if KO
    /// <para>Minutes 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the minutes value.</para>
    /// \endif
    /// </summary>
    public int Minutes { get => _minutes; set { _minutes = Math.Clamp(value, 0, 59); Raise(); } }
    /// <summary>
    /// \if KO
    /// <para>Seconds 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the seconds value.</para>
    /// \endif
    /// </summary>
    public int Seconds { get => _seconds; set { _seconds = Math.Clamp(value, 0, 59); Raise(); } }
    /// <summary>
    /// \if KO
    /// <para>Time Display 값을 가져옵니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets the time display value.</para>
    /// \endif
    /// </summary>
    public string TimeDisplay => $"{_hours:D2}:{_minutes:D2}:{_seconds:D2}";

    // -- DreamineImage (clickable image) -------------------
    /// <summary>
    /// \if KO
    /// <para>Image Click Count 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the image click count value.</para>
    /// \endif
    /// </summary>
    public int ImageClickCount { get; private set; }
    /// <summary>
    /// \if KO
    /// <para>Click Image 작업을 수행합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Performs the click image operation.</para>
    /// \endif
    /// </summary>
    public void ClickImage()
    {
        ImageClickCount++;
        ActivityLog.Insert(0, $"[{DateTime.Now:HH:mm:ss}] Image clicked ({ImageClickCount})");
        while (ActivityLog.Count > 8) ActivityLog.RemoveAt(ActivityLog.Count - 1);
        Raise();
    }

    /// <summary>
    /// \if KO
    /// <para>Raise 작업을 수행합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Performs the raise operation.</para>
    /// \endif
    /// </summary>
    private void Raise() => OnPropertyChanged(string.Empty);
}

/// <summary>
/// \if KO
/// <para>Grid Row 기능과 관련 상태를 캡슐화합니다.</para>
/// \endif
/// \if EN
/// <para>Encapsulates grid row functionality and related state.</para>
/// \endif
/// </summary>
public class GridRow
{
    /// <summary>
    /// \if KO
    /// <para>No 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the no value.</para>
    /// \endif
    /// </summary>
    public int No { get; set; }
    /// <summary>
    /// \if KO
    /// <para>Name 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the name value.</para>
    /// \endif
    /// </summary>
    public string Name { get; set; } = string.Empty;
    /// <summary>
    /// \if KO
    /// <para>Status 값을 가져오거나 설정합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets or sets the status value.</para>
    /// \endif
    /// </summary>
    public string Status { get; set; } = string.Empty;
}
