using System.Collections.ObjectModel;
using Dreamine.MVVM.ViewModels;

namespace DreamineWeb.ViewModels.Demos;

/// <summary>
/// ViewModel for the controls showcase live demo.
/// This browser-friendly version mirrors the ControlsViewModel / ControlsEvent shape from SampleCrossUi.Shared.
/// In the real sample, logic lives in ControlsEvent and members are generated by [DreamineCommand]/[DreamineProperty].
/// </summary>
public sealed class ControlsShowcaseViewModel : ViewModelBase
{
    // ── Button ────────────────────────────────────────────
    public int ClickCount { get; private set; }
    public ObservableCollection<string> ActivityLog { get; } = new();

    public void ClickMe()
    {
        ClickCount++;
        ActivityLog.Insert(0, $"[{DateTime.Now:HH:mm:ss}] Clicked ({ClickCount})");
        while (ActivityLog.Count > 8) ActivityLog.RemoveAt(ActivityLog.Count - 1);
        Raise();
    }

    // ── CheckBox ──────────────────────────────────────────
    private bool _check1 = true, _check2, _check3;
    public bool Check1 { get => _check1; set { _check1 = value; Raise(); } }
    public bool Check2 { get => _check2; set { _check2 = value; Raise(); } }
    public bool Check3 { get => _check3; set { _check3 = value; Raise(); } }

    // ── RadioButton ───────────────────────────────────────
    public string SelectedRadio { get; private set; } = "Option A";
    public void SelectRadio(string option) { SelectedRadio = option; Raise(); }

    // -- CheckLed (Dreamine signature control) -------------
    public bool LedIsOn { get; private set; } = true;
    public bool LedIsPulse { get; private set; }
    public void ToggleLed() { LedIsOn = !LedIsOn; Raise(); }
    public void TogglePulse() { LedIsPulse = !LedIsPulse; Raise(); }

    // ── TextBox / PasswordBox ─────────────────────────────
    private string _textInput = string.Empty;
    private string _password = string.Empty;
    public string TextInput { get => _textInput; set { _textInput = value; Raise(); } }
    public string Password { get => _password; set { _password = value; Raise(); } }
    public void ClearText() { _textInput = string.Empty; Raise(); }
    public void ClearPassword() { _password = string.Empty; Raise(); }

    // ── ComboBox ──────────────────────────────────────────
    public string[] FruitItems { get; } = { "Apple", "Banana", "Cherry", "Grape", "Mango", "Melon" };
    private string _selectedFruit = "Cherry";
    public string SelectedFruit { get => _selectedFruit; set { _selectedFruit = value; Raise(); } }

    // ── Expander ──────────────────────────────────────────
    private bool _isExpanded = true;
    public bool IsExpanded { get => _isExpanded; set { _isExpanded = value; Raise(); } }
    public void ToggleExpand() { _isExpanded = !_isExpanded; Raise(); }

    // ── Numeric (0~100 clamp) ─────────────────────────────
    private double _numericInput = 50;
    public double NumericInput
    {
        get => _numericInput;
        set { _numericInput = Math.Clamp(value, 0, 100); Raise(); }
    }

    // -- ListBox (selection + double-click activation) -----
    public string ListActivated { get; private set; } = "(double-click an item)";
    public void ActivateListItem(string item) { ListActivated = $"Activated: {item}"; Raise(); }

    // ── Counter ──────────────────────────────────────────
    private int _count;
    public int Count => _count;
    public ObservableCollection<string> CounterLogs { get; } = new();

    public void Increment()
    {
        _count++;
        CounterLogs.Insert(0, $"[{DateTime.Now:HH:mm:ss}] Incremented → {_count}");
        while (CounterLogs.Count > 10) CounterLogs.RemoveAt(CounterLogs.Count - 1);
        Raise();
    }

    public void ResetCounter()
    {
        _count = 0;
        CounterLogs.Insert(0, $"[{DateTime.Now:HH:mm:ss}] Counter reset.");
        while (CounterLogs.Count > 10) CounterLogs.RemoveAt(CounterLogs.Count - 1);
        Raise();
    }

    // -- DataGrid (static demo data) -----------------------
    public ObservableCollection<GridRow> GridRows { get; } = new()
    {
        new() { No = 1, Name = "Device A", Status = "Running" },
        new() { No = 2, Name = "Device B", Status = "Stopped" },
        new() { No = 3, Name = "Device C", Status = "Running" },
        new() { No = 4, Name = "Device D", Status = "Error" },
    };

    private GridRow? _selectedRow;
    public GridRow? SelectedRow { get => _selectedRow; set { _selectedRow = value; Raise(); } }

    // -- TimeSpinner (time selection) ----------------------
    private int _hours = 9, _minutes = 30, _seconds = 0;
    public int Hours { get => _hours; set { _hours = Math.Clamp(value, 0, 23); Raise(); } }
    public int Minutes { get => _minutes; set { _minutes = Math.Clamp(value, 0, 59); Raise(); } }
    public int Seconds { get => _seconds; set { _seconds = Math.Clamp(value, 0, 59); Raise(); } }
    public string TimeDisplay => $"{_hours:D2}:{_minutes:D2}:{_seconds:D2}";

    // -- DreamineImage (clickable image) -------------------
    public int ImageClickCount { get; private set; }
    public void ClickImage()
    {
        ImageClickCount++;
        ActivityLog.Insert(0, $"[{DateTime.Now:HH:mm:ss}] Image clicked ({ImageClickCount})");
        while (ActivityLog.Count > 8) ActivityLog.RemoveAt(ActivityLog.Count - 1);
        Raise();
    }

    private void Raise() => OnPropertyChanged(string.Empty);
}

public class GridRow
{
    public int No { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Status { get; set; } = string.Empty;
}
