namespace WeddingPlatform.Services;

public sealed class WeddingLocalization
{
    public sealed record LanguageOption(string Code, string Region, string NativeName, string HtmlLanguage);

    public static readonly LanguageOption[] Languages =
    [
        new("en", "US", "English", "en"), new("es", "ES", "Español", "es"),
        new("fr", "FR", "Français", "fr"), new("it", "IT", "Italiano", "it"),
        new("pt", "PT", "Português", "pt"), new("ko", "KR", "한국어", "ko"),
        new("ja", "JP", "日本語", "ja"), new("zh-hans", "CN", "简体中文", "zh-Hans"),
        new("zh-hant", "HK", "繁體中文", "zh-Hant"), new("vi", "VN", "Tiếng Việt", "vi")
    ];

    private static readonly string[] Codes = Languages.Select(x => x.Code).ToArray();
    private static readonly Dictionary<string, string[]> Texts = new(StringComparer.OrdinalIgnoreCase)
    {
        ["language"] = ["Language","Idioma","Langue","Lingua","Idioma","언어","言語","语言","語言","Ngôn ngữ"],
        ["theme"] = ["Theme","Tema","Thème","Tema","Tema","화면 테마","テーマ","主题","主題","Giao diện"],
        ["system"] = ["System","Sistema","Système","Sistema","Sistema","시스템","システム","系统","系統","Hệ thống"],
        ["light"] = ["Light","Claro","Clair","Chiaro","Claro","라이트","ライト","浅色","淺色","Sáng"],
        ["dark"] = ["Dark","Oscuro","Sombre","Scuro","Escuro","다크","ダーク","深色","深色","Tối"],
        ["home"] = ["Home","Inicio","Accueil","Home","Início","홈","ホーム","首页","首頁","Trang chủ"],
        ["contact"] = ["Contact","Contacto","Contact","Contatti","Contato","문의하기","お問い合わせ","联系我们","聯絡我們","Liên hệ"],
        ["login"] = ["Sign in","Iniciar sesión","Connexion","Accedi","Entrar","로그인","ログイン","登录","登入","Đăng nhập"],
        ["logout"] = ["Sign out","Cerrar sesión","Déconnexion","Esci","Sair","로그아웃","ログアウト","退出登录","登出","Đăng xuất"],
        ["account"] = ["My account","Mi cuenta","Mon compte","Il mio account","Minha conta","내 계정","マイアカウント","我的账户","我的帳戶","Tài khoản"],
        ["screen.settings"] = ["Screen settings","Ajustes de pantalla","Réglages d’affichage","Impostazioni schermo","Configurações da tela","화면 설정","画面設定","屏幕设置","畫面設定","Cài đặt màn hình"],
        ["nav.toggle"] = ["Open or close menu","Abrir o cerrar menú","Ouvrir ou fermer le menu","Apri o chiudi menu","Abrir ou fechar menu","메뉴 열기/닫기","メニューを開閉","打开或关闭菜单","開啟或關閉選單","Mở hoặc đóng menu"],
        ["page.title"] = ["Free mobile wedding invitation — CodeMaru Wedding","Invitación de boda móvil gratis — CodeMaru Wedding","Invitation de mariage mobile gratuite — CodeMaru Wedding","Invito di nozze mobile gratuito — CodeMaru Wedding","Convite de casamento móvel gratuito — CodeMaru Wedding","무료 모바일 청첩장 — CodeMaru Wedding","無料モバイル結婚招待状 — CodeMaru Wedding","免费移动婚礼请柬 — CodeMaru Wedding","免費行動婚禮喜帖 — CodeMaru Wedding","Thiệp cưới di động miễn phí — CodeMaru Wedding"],
        ["hero.badge"] = ["✨ Free mobile wedding invitation","✨ Invitación móvil gratuita","✨ Invitation mobile gratuite","✨ Invito mobile gratuito","✨ Convite móvel gratuito","✨ 무료 모바일 청첩장","✨ 無料モバイル結婚招待状","✨ 免费移动婚礼请柬","✨ 免費行動婚禮喜帖","✨ Thiệp cưới di động miễn phí"],
        ["hero.title"] = ["Turn our special day\ninto a mobile invitation","Convierte nuestro día especial\nen una invitación móvil","Transformez notre journée spéciale\nen invitation mobile","Trasforma il nostro giorno speciale\nin un invito mobile","Transforme nosso dia especial\nem um convite móvel","우리의 특별한 날을\n모바일 청첩장으로","特別な一日を\nモバイル招待状に","把我们的特别日子\n做成移动婚礼请柬","將我們的特別日子\n製作成行動喜帖","Biến ngày đặc biệt của chúng ta\nthành thiệp cưới di động"],
        ["hero.sub"] = ["Photos, music, maps and guestbook — ready in five minutes","Fotos, música, mapas y libro de visitas — listo en cinco minutos","Photos, musique, cartes et livre d’or — prêt en cinq minutes","Foto, musica, mappe e messaggi — pronto in cinque minuti","Fotos, música, mapas e mensagens — pronto em cinco minutos","사진·음악·지도·방명록 — 5분이면 완성","写真・音楽・地図・ゲストブック — 5分で完成","照片、音乐、地图、留言簿 — 五分钟完成","照片、音樂、地圖、留言簿 — 五分鐘完成","Ảnh, nhạc, bản đồ và sổ lưu bút — hoàn thành trong 5 phút"],
        ["create.now"] = ["Create free now →","Crear gratis ahora →","Créer gratuitement →","Crea gratis ora →","Criar grátis agora →","지금 무료로 만들기 →","今すぐ無料で作成 →","立即免费创建 →","立即免費建立 →","Tạo miễn phí ngay →"],
        ["codemaru.home"] = ["CodeMaru home","Inicio CodeMaru","Accueil CodeMaru","Home CodeMaru","Início CodeMaru","CodeMaru 홈","CodeMaru ホーム","CodeMaru 首页","CodeMaru 首頁","Trang chủ CodeMaru"],
        ["manage.mine"] = ["Manage my invitations","Gestionar mis invitaciones","Gérer mes invitations","Gestisci i miei inviti","Gerenciar meus convites","내 청첩장 관리","招待状を管理","管理我的请柬","管理我的喜帖","Quản lý thiệp của tôi"],
        ["features.photos"] = ["Photo gallery","Galería de fotos","Galerie photo","Galleria foto","Galeria de fotos","사진 갤러리","フォトギャラリー","照片画廊","照片圖庫","Thư viện ảnh"],
        ["features.map"] = ["Smart map","Mapa inteligente","Carte intelligente","Mappa intelligente","Mapa inteligente","스마트 지도","スマート地図","智能地图","智慧地圖","Bản đồ thông minh"],
        ["features.music"] = ["Background music","Música de fondo","Musique de fond","Musica di sottofondo","Música de fundo","배경 음악","BGM","背景音乐","背景音樂","Nhạc nền"],
        ["features.guestbook"] = ["Guestbook","Libro de visitas","Livre d’or","Libro degli ospiti","Livro de visitas","방명록","ゲストブック","留言簿","留言簿","Sổ lưu bút"],
        ["features.accounts"] = ["Payment details","Datos de pago","Coordonnées de paiement","Dati di pagamento","Dados de pagamento","계좌 안내","ご祝儀口座案内","收款信息","收款資訊","Thông tin mừng cưới"],
        ["features.themes"] = ["Five themes","Cinco temas","Cinq thèmes","Cinque temi","Cinco temas","5가지 테마","5つのテーマ","五种主题","五種主題","Năm chủ đề"],
        ["start.title"] = ["Start for free","Comenzar gratis","Commencer gratuitement","Inizia gratis","Começar grátis","무료로 시작하기","無料で始める","免费开始","免費開始","Bắt đầu miễn phí"],
        ["start.desc"] = ["Enter the details below to create your invitation immediately.","Introduce los datos para crear tu invitación al instante.","Saisissez les informations pour créer immédiatement votre invitation.","Inserisci i dati per creare subito il tuo invito.","Informe os dados para criar seu convite agora.","아래 정보를 입력하면 바로 청첩장이 생성됩니다.","以下を入力すると招待状がすぐ作成されます。","填写以下信息即可立即创建请柬。","填寫以下資訊即可立即建立喜帖。","Nhập thông tin dưới đây để tạo thiệp ngay."],
        ["field.slug"] = ["URL address","Dirección URL","Adresse URL","Indirizzo URL","Endereço URL","URL 주소","URL アドレス","URL 地址","URL 位址","Địa chỉ URL"],
        ["field.couple"] = ["Couple names","Nombres de la pareja","Noms du couple","Nomi della coppia","Nomes do casal","커플 이름","お二人の名前","新人姓名","新人姓名","Tên cô dâu chú rể"],
        ["field.date"] = ["Wedding date","Fecha de la boda","Date du mariage","Data del matrimonio","Data do casamento","결혼 예정일","挙式日","婚礼日期","婚禮日期","Ngày cưới"],
        ["field.password"] = ["Admin password","Contraseña de administración","Mot de passe administrateur","Password amministratore","Senha de administração","어드민 비밀번호","管理パスワード","管理员密码","管理員密碼","Mật khẩu quản trị"],
        ["create.button"] = ["✨ Create invitation","✨ Crear invitación","✨ Créer l’invitation","✨ Crea invito","✨ Criar convite","✨ 청첩장 만들기","✨ 招待状を作成","✨ 创建请柬","✨ 建立喜帖","✨ Tạo thiệp cưới"],
        ["creating"] = ["Creating...","Creando...","Création...","Creazione...","Criando...","생성 중...","作成中...","正在创建...","正在建立...","Đang tạo..."],
        ["my.invites"] = ["My invitations","Mis invitaciones","Mes invitations","I miei inviti","Meus convites","내 청첩장","マイ招待状","我的请柬","我的喜帖","Thiệp của tôi"],
        ["public.invites"] = ["💒 Invitation gallery","💒 Galería de invitaciones","💒 Galerie d’invitations","💒 Galleria inviti","💒 Galeria de convites","💒 청첩장 목록","💒 招待状一覧","💒 请柬列表","💒 喜帖列表","💒 Danh sách thiệp cưới"],
        ["admin"] = ["Admin","Administración","Administration","Amministrazione","Administração","관리자","管理者","管理","管理","Quản trị"]
        ,["seo.description"] = ["Create a free mobile wedding invitation with photos, music, maps, guestbook and payment details in five minutes.","Crea en cinco minutos una invitación móvil gratuita con fotos, música, mapas, libro de visitas y datos de pago.","Créez en cinq minutes une invitation mobile gratuite avec photos, musique, cartes, livre d’or et informations de paiement.","Crea in cinque minuti un invito mobile gratuito con foto, musica, mappe, messaggi e dati di pagamento.","Crie em cinco minutos um convite móvel gratuito com fotos, música, mapas, mensagens e dados de pagamento.","사진·음악·지도·방명록·계좌 안내까지 5분이면 완성되는 무료 모바일 청첩장 서비스입니다.","写真・音楽・地図・ゲストブック・ご祝儀口座案内まで、5分で作れる無料モバイル招待状です。","包含照片、音乐、地图、留言簿和收款信息，五分钟即可创建免费移动婚礼请柬。","包含照片、音樂、地圖、留言簿與收款資訊，五分鐘即可建立免費行動喜帖。","Tạo thiệp cưới di động miễn phí với ảnh, nhạc, bản đồ, sổ lưu bút và thông tin mừng cưới chỉ trong 5 phút."],
        ["service.notice"] = ["⚡ Temporary delays may occur on this free service. Contact:","⚡ Este servicio gratuito puede sufrir demoras temporales. Contacto:","⚡ Ce service gratuit peut subir des ralentissements temporaires. Contact :","⚡ Il servizio gratuito può subire ritardi temporanei. Contatto:","⚡ Este serviço gratuito pode apresentar atrasos temporários. Contato:","⚡ 무료 서비스 특성상 일시적인 접속 지연이 발생할 수 있습니다. 문의:","⚡ 無料サービスのため、一時的に接続が遅くなる場合があります。お問い合わせ:","⚡ 免费服务可能会暂时出现访问延迟。联系：","⚡ 免費服務可能會暫時出現連線延遲。聯絡：","⚡ Dịch vụ miễn phí đôi khi có thể truy cập chậm. Liên hệ:"],
        ["service.cleanup"] = ["🗑 Accounts without uploaded photos are automatically deleted after 24 hours.","🗑 Las cuentas sin fotos se eliminan automáticamente después de 24 horas.","🗑 Les comptes sans photo sont supprimés automatiquement après 24 heures.","🗑 Gli account senza foto vengono eliminati automaticamente dopo 24 ore.","🗑 Contas sem fotos são excluídas automaticamente após 24 horas.","🗑 사진 미업로드 계정은 24시간 후 자동 삭제됩니다.","🗑 写真未アップロードのアカウントは24時間後に自動削除されます。","🗑 未上传照片的账户将在24小时后自动删除。","🗑 未上傳照片的帳戶將於24小時後自動刪除。","🗑 Tài khoản chưa tải ảnh sẽ tự động bị xóa sau 24 giờ."],
        ["features.photos.desc"] = ["Share wedding photos in a gallery and enjoy a slideshow.","Comparte fotos de boda en una galería y disfruta de la presentación.","Partagez vos photos dans une galerie et profitez du diaporama.","Condividi le foto in una galleria e guarda la presentazione.","Compartilhe fotos em uma galeria e veja a apresentação.","웨딩 사진을 갤러리로 공유하고 슬라이드쇼로 감상","写真をギャラリーで共有し、スライドショーで楽しめます。","在画廊中分享婚礼照片并欣赏幻灯片。","在相簿中分享婚禮照片並欣賞投影片。","Chia sẻ ảnh cưới trong thư viện và xem trình chiếu."],
        ["features.map.desc"] = ["Open directions with KakaoMap, Naver, Atlan or T map in one tap.","Abre indicaciones con KakaoMap, Naver, Atlan o T map con un toque.","Ouvrez l’itinéraire avec KakaoMap, Naver, Atlan ou T map en un geste.","Apri le indicazioni con KakaoMap, Naver, Atlan o T map con un tocco.","Abra rotas com KakaoMap, Naver, Atlan ou T map com um toque.","카카오맵·네이버·아틀란·T맵 원터치 길찾기","KakaoMap・Naver・Atlan・T mapでワンタップ経路検索。","一键使用 KakaoMap、Naver、Atlan 或 T map 导航。","一鍵使用 KakaoMap、Naver、Atlan 或 T map 導航。","Mở chỉ đường bằng KakaoMap, Naver, Atlan hoặc T map chỉ với một chạm."],
        ["features.music.desc"] = ["Set your favorite music as the background.","Usa tu música favorita como fondo.","Choisissez votre musique préférée en fond sonore.","Imposta la tua musica preferita come sottofondo.","Defina sua música favorita como fundo.","좋아하는 음악을 배경으로 설정","お気に入りの音楽をBGMに設定できます。","将喜欢的音乐设为背景音乐。","將喜歡的音樂設為背景音樂。","Đặt bài nhạc yêu thích làm nhạc nền."],
        ["features.guestbook.desc"] = ["Receive congratulatory messages from guests online.","Recibe mensajes de felicitación de los invitados en línea.","Recevez en ligne les messages de félicitations de vos invités.","Ricevi online i messaggi di auguri degli invitati.","Receba online mensagens de felicitações dos convidados.","하객들의 축하 메시지를 온라인으로 받기","ゲストからのお祝いメッセージをオンラインで受け取れます。","在线接收宾客的祝福留言。","線上接收賓客的祝福留言。","Nhận lời chúc của khách mời trực tuyến."],
        ["features.accounts.desc"] = ["Copy the couple’s and parents’ payment details with one tap.","Copia con un toque los datos de pago de la pareja y sus padres.","Copiez en un geste les informations de paiement du couple et des parents.","Copia con un tocco i dati di pagamento degli sposi e dei genitori.","Copie com um toque os dados de pagamento do casal e dos pais.","신랑·신부·부모님 계좌를 탭 한 번에 복사","新郎新婦・ご両親の口座情報をワンタップでコピーできます。","一键复制新人及父母的收款信息。","一鍵複製新人與父母的收款資訊。","Sao chép thông tin mừng cưới của cô dâu chú rể và cha mẹ chỉ với một chạm."],
        ["features.themes.desc"] = ["Choose Rose Gold, Ivory, Forest, Navy or Blush.","Elige Rose Gold, Ivory, Forest, Navy o Blush.","Choisissez Rose Gold, Ivory, Forest, Navy ou Blush.","Scegli Rose Gold, Ivory, Forest, Navy o Blush.","Escolha Rose Gold, Ivory, Forest, Navy ou Blush.","로즈골드·아이보리·포레스트·네이비·블러쉬","ローズゴールド・アイボリー・フォレスト・ネイビー・ブラッシュから選べます。","可选玫瑰金、象牙白、森林、海军蓝或腮红主题。","可選玫瑰金、象牙白、森林、海軍藍或腮紅主題。","Chọn Rose Gold, Ivory, Forest, Navy hoặc Blush."],
        ["guest.account"] = ["Sign in to connect each invitation directly to your account.","Inicia sesión para vincular cada invitación directamente a tu cuenta.","Connectez-vous pour associer chaque invitation directement à votre compte.","Accedi per collegare ogni invito direttamente al tuo account.","Entre para vincular cada convite diretamente à sua conta.","로그인하면 생성한 청첩장이 내 계정에 바로 연결됩니다.","ログインすると、作成した招待状がアカウントに直接連携されます。","登录后，创建的请柬将直接关联到您的账户。","登入後，建立的喜帖將直接連結到您的帳戶。","Đăng nhập để liên kết thiệp đã tạo trực tiếp với tài khoản của bạn."],
        ["common.login"] = ["Shared sign-in","Acceso compartido","Connexion commune","Accesso condiviso","Login compartilhado","공용 로그인","共通ログイン","统一登录","統一登入","Đăng nhập chung"],
        ["field.slug.hint"] = ["Letters, numbers and hyphens only (for example: hong-gildong)","Solo letras, números y guiones (ej.: hong-gildong)","Lettres, chiffres et tirets uniquement (ex. : hong-gildong)","Solo lettere, numeri e trattini (es.: hong-gildong)","Somente letras, números e hífens (ex.: hong-gildong)","영문·숫자·하이픈만 (예: hong-gildong)","英字・数字・ハイフンのみ（例: hong-gildong）","仅限字母、数字和连字符（例如：hong-gildong）","僅限字母、數字與連字號（例如：hong-gildong）","Chỉ dùng chữ cái, số và dấu gạch nối (ví dụ: hong-gildong)"],
        ["field.couple.placeholder"] = ["Alex ♥ Jamie","Alex ♥ Jamie","Alex ♥ Jamie","Alex ♥ Jamie","Alex ♥ Jamie","홍길동 ♥ 김영희","太郎 ♥ 花子","新郎 ♥ 新娘","新郎 ♥ 新娘","Minh ♥ Lan"],
        ["field.password.hint"] = ["Used to edit the invitation","Se usa para editar la invitación","Utilisé pour modifier l’invitation","Usata per modificare l’invito","Usada para editar o convite","청첩장 편집 시 사용","招待状の編集に使用","用于编辑请柬","用於編輯喜帖","Dùng để chỉnh sửa thiệp"],
        ["field.password.placeholder"] = ["Eight or more characters recommended","Se recomiendan 8 caracteres o más","8 caractères ou plus recommandés","Consigliati almeno 8 caratteri","Recomendados 8 caracteres ou mais","8자 이상 권장","8文字以上を推奨","建议至少8个字符","建議至少8個字元","Nên dùng từ 8 ký tự"],
        ["create.notice"] = ["After creation, configure photos, music, maps and more at /{slug}/admin.","Después de crearla, configura fotos, música, mapas y más en /{slug}/admin.","Après création, configurez photos, musique, cartes et plus sur /{slug}/admin.","Dopo la creazione, configura foto, musica, mappe e altro in /{slug}/admin.","Após criar, configure fotos, música, mapas e mais em /{slug}/admin.","생성 후 /{슬러그}/admin에서 사진·음악·지도 등을 설정할 수 있습니다.","作成後、/{slug}/admin で写真・音楽・地図などを設定できます。","创建后，可在 /{slug}/admin 配置照片、音乐、地图等。","建立後，可在 /{slug}/admin 設定照片、音樂、地圖等。","Sau khi tạo, hãy cấu hình ảnh, nhạc, bản đồ và nhiều nội dung khác tại /{slug}/admin."],
        ["manage.open"] = ["Open management →","Abrir gestión →","Ouvrir la gestion →","Apri gestione →","Abrir gerenciamento →","관리 열기 →","管理を開く →","打开管理 →","開啟管理 →","Mở quản lý →"],
        ["admin.dashboard"] = ["Dashboard","Panel","Tableau de bord","Dashboard","Painel","대시보드","ダッシュボード","仪表板","儀表板","Bảng điều khiển"],
        ["admin.invitations"] = ["Invitations","Invitaciones","Invitations","Inviti","Convites","청첩장 관리","招待状管理","请柬管理","喜帖管理","Quản lý thiệp"],
        ["admin.accounts"] = ["Accounts","Cuentas","Comptes","Account","Contas","계정 관리","アカウント管理","账户管理","帳戶管理","Quản lý tài khoản"],
        ["admin.media"] = ["Media","Multimedia","Médias","Media","Mídia","미디어 관리","メディア管理","媒体管理","媒體管理","Quản lý media"],
        ["admin.layouts"] = ["Layout catalog","Catálogo de diseños","Catalogue des mises en page","Catalogo layout","Catálogo de layouts","레이아웃 카탈로그","レイアウトカタログ","布局目录","版面目錄","Danh mục bố cục"],
        ["admin.settings"] = ["Settings","Ajustes","Paramètres","Impostazioni","Configurações","설정","設定","设置","設定","Cài đặt"],
        ["admin.integrated"] = ["Wedding administration","Administración de Wedding","Administration Wedding","Amministrazione Wedding","Administração Wedding","Wedding 통합 어드민","Wedding 統合管理","Wedding 综合管理","Wedding 整合管理","Quản trị Wedding"],
        ["admin.integrated.desc"] = ["Manage registered couples and create invitations.","Gestiona parejas registradas y crea invitaciones.","Gérez les couples inscrits et créez des invitations.","Gestisci le coppie registrate e crea inviti.","Gerencie casais cadastrados e crie convites.","등록된 커플 계정을 관리하고 새 청첩장을 만듭니다.","登録済みカップルを管理し、招待状を作成します。","管理已注册新人并创建请柬。","管理已登記新人並建立喜帖。","Quản lý các cặp đôi và tạo thiệp cưới."],
        ["admin.search"] = ["Search","Buscar","Rechercher","Cerca","Pesquisar","검색","検索","搜索","搜尋","Tìm kiếm"],
        ["admin.search.placeholder"] = ["Search couple, URL or email","Buscar pareja, URL o correo","Rechercher couple, URL ou e-mail","Cerca coppia, URL o email","Pesquisar casal, URL ou e-mail","커플 이름, 슬러그, 이메일 검색","カップル名、URL、メールを検索","搜索新人、网址或邮箱","搜尋新人、網址或信箱","Tìm cặp đôi, URL hoặc email"],
        ["admin.refresh"] = ["Refresh","Actualizar","Actualiser","Aggiorna","Atualizar","새로고침","更新","刷新","重新整理","Làm mới"],
        ["admin.super"] = ["Super administrator","Superadministrador","Super administrateur","Super amministratore","Super administrador","최고 관리자","スーパー管理者","超级管理员","超級管理員","Quản trị viên cấp cao"],
        ["admin.summary"] = ["Summary","Resumen","Résumé","Riepilogo","Resumo","요약","概要","摘要","摘要","Tóm tắt"],
        ["admin.total.accounts"] = ["Total accounts","Cuentas totales","Total des comptes","Account totali","Total de contas","전체 계정 수","総アカウント数","账户总数","帳戶總數","Tổng tài khoản"],
        ["admin.registered.couples"] = ["Registered couples","Parejas registradas","Couples inscrits","Coppie registrate","Casais cadastrados","등록된 커플","登録済みカップル","已注册新人","已登記新人","Cặp đôi đã đăng ký"],
        ["admin.home.visible"] = ["Shown on home","Visible en inicio","Visible à l’accueil","Visibile in home","Visível no início","메인 노출","ホーム掲載","首页展示","首頁顯示","Hiển thị trang chủ"],
        ["admin.premium.active"] = ["Premium active","Premium activo","Premium actif","Premium attivo","Premium ativo","Premium 활성","Premium 有効","Premium 已启用","Premium 已啟用","Premium đang bật"],
        ["admin.storage"] = ["Storage","Almacenamiento","Stockage","Archiviazione","Armazenamento","저장 용량","ストレージ","存储空间","儲存空間","Dung lượng"],
        ["admin.video.usage"] = ["Video usage","Uso de vídeo","Utilisation vidéo","Utilizzo video","Uso de vídeo","동영상 사용량","動画使用量","视频用量","影片用量","Dung lượng video"],
        ["admin.registered"] = ["Registered","Registrado","Inscrit","Registrato","Cadastrado","등록됨","登録済み","已注册","已登記","Đã đăng ký"],
        ["admin.signin"] = ["Administrator sign in","Acceso de administrador","Connexion administrateur","Accesso amministratore","Login do administrador","관리자 로그인","管理者ログイン","管理员登录","管理員登入","Đăng nhập quản trị"],
        ["admin.checking"] = ["Checking management access.","Comprobando acceso de gestión.","Vérification de l’accès.","Verifica accesso gestione.","Verificando acesso de gestão.","관리 권한을 확인하고 있습니다.","管理権限を確認しています。","正在检查管理权限。","正在檢查管理權限。","Đang kiểm tra quyền quản lý."],
        ["admin.save"] = ["Save settings","Guardar ajustes","Enregistrer","Salva impostazioni","Salvar configurações","설정 저장","設定を保存","保存设置","儲存設定","Lưu cài đặt"],
        ["admin.share"] = ["Share","Compartir","Partager","Condividi","Compartilhar","공유하기","共有","分享","分享","Chia sẻ"],
        ["admin.open.invite"] = ["Open invitation","Abrir invitación","Ouvrir l’invitation","Apri invito","Abrir convite","청첩장 열기","招待状を開く","打开请柬","開啟喜帖","Mở thiệp cưới"],
        ["admin.basic"] = ["Basic information","Información básica","Informations de base","Informazioni di base","Informações básicas","기본 정보","基本情報","基本信息","基本資訊","Thông tin cơ bản"],
        ["admin.notice"] = ["Ceremony notice","Aviso de ceremonia","Informations de cérémonie","Avviso cerimonia","Aviso da cerimônia","예식 안내","挙式案内","婚礼说明","婚禮說明","Thông báo lễ cưới"],
        ["admin.design"] = ["Design","Diseño","Design","Design","Design","디자인","デザイン","设计","設計","Thiết kế"],
        ["admin.story"] = ["Story chapters","Capítulos de historia","Chapitres de l’histoire","Capitoli della storia","Capítulos da história","스토리 챕터","ストーリーチャプター","故事章节","故事章節","Chương câu chuyện"],
        ["admin.photobook"] = ["Photo book pages","Páginas del álbum","Pages de l’album","Pagine fotolibro","Páginas do álbum","포토북 페이지","フォトブックページ","相册页面","相簿頁面","Trang album ảnh"],
        ["admin.cards"] = ["Card highlights","Tarjetas destacadas","Cartes mises en avant","Schede in evidenza","Cartões em destaque","카드 강조","カード強調","卡片重点","卡片重點","Thẻ nổi bật"],
        ["admin.content"] = ["Photos and videos","Fotos y vídeos","Photos et vidéos","Foto e video","Fotos e vídeos","사진·동영상","写真・動画","照片和视频","照片與影片","Ảnh và video"],
        ["admin.map"] = ["Map","Mapa","Carte","Mappa","Mapa","지도","地図","地图","地圖","Bản đồ"],
        ["admin.payment"] = ["Payment details","Datos de pago","Informations de paiement","Dati di pagamento","Dados de pagamento","계좌 안내","ご祝儀口座案内","收款信息","收款資訊","Thông tin mừng cưới"],
        ["admin.sharing"] = ["Sharing settings","Ajustes para compartir","Paramètres de partage","Impostazioni condivisione","Configurações de compartilhamento","공유 설정","共有設定","分享设置","分享設定","Cài đặt chia sẻ"],
        ["admin.manage"] = ["Manage","Gestionar","Gérer","Gestisci","Gerenciar","관리","管理","管理","管理","Quản lý"],
        ["admin.close.menu"] = ["Close menu","Cerrar menú","Fermer le menu","Chiudi menu","Fechar menu","메뉴 닫기","メニューを閉じる","关闭菜单","關閉選單","Đóng menu"],
        ["admin.open.menu"] = ["Open menu","Abrir menú","Ouvrir le menu","Apri menu","Abrir menu","메뉴 열기","メニューを開く","打开菜单","開啟選單","Mở menu"],
        ["admin.open.thankyou"] = ["Open thank-you page","Abrir página de agradecimiento","Ouvrir la page de remerciement","Apri pagina di ringraziamento","Abrir página de agradecimento","감사장 열기","お礼状を開く","打开感谢页","開啟感謝頁","Mở trang cảm ơn"],
        ["admin.preview"] = ["Preview","Vista previa","Aperçu","Anteprima","Prévia","미리보기","プレビュー","预览","預覽","Xem trước"],
        ["admin.open.preview"] = ["Open preview","Abrir vista previa","Ouvrir l’aperçu","Apri anteprima","Abrir prévia","미리보기 열기","プレビューを開く","打开预览","開啟預覽","Mở xem trước"],
        ["admin.expand.preview"] = ["Expand preview","Ampliar vista previa","Déployer l’aperçu","Espandi anteprima","Expandir prévia","미리보기 펼치기","プレビューを展開","展开预览","展開預覽","Mở rộng xem trước"],
        ["admin.shared.current"] = ["Current shared sign-in","Sesión compartida actual","Connexion commune actuelle","Accesso condiviso attuale","Login compartilhado atual","현재 공용 로그인","現在の共通ログイン","当前统一登录","目前統一登入","Đăng nhập chung hiện tại"],
        ["admin.link.account"] = ["Enter the existing admin password once to add this account as an invitation manager.","Introduce una vez la contraseña de administrador para añadir esta cuenta.","Saisissez une fois le mot de passe administrateur pour ajouter ce compte.","Inserisci una volta la password amministratore per aggiungere questo account.","Digite uma vez a senha de administrador para adicionar esta conta.","기존 관리자 비밀번호를 한 번 입력하면 이 계정이 청첩장 관리자로 추가됩니다.","既存の管理パスワードを一度入力すると、このアカウントが管理者に追加されます。","输入一次现有管理员密码即可将此账户添加为请柬管理员。","輸入一次現有管理員密碼即可將此帳戶加入為喜帖管理員。","Nhập mật khẩu quản trị hiện tại một lần để thêm tài khoản này làm quản trị viên thiệp."],
        ["admin.login.first"] = ["Sign in to CodeMaru/Dreamine first, then confirm the existing password to connect this wedding site.","Inicia sesión en CodeMaru/Dreamine y confirma la contraseña existente para conectar este sitio.","Connectez-vous d’abord à CodeMaru/Dreamine puis confirmez le mot de passe existant.","Accedi prima a CodeMaru/Dreamine e conferma la password esistente.","Entre primeiro no CodeMaru/Dreamine e confirme a senha existente.","CodeMaru/Dreamine 계정으로 먼저 로그인하면 기존 비밀번호 확인 후 이 웨딩 사이트를 연결할 수 있습니다.","先にCodeMaru/Dreamineへログインし、既存パスワードを確認してこのサイトを連携します。","请先登录 CodeMaru/Dreamine，再确认现有密码以关联婚礼网站。","請先登入 CodeMaru/Dreamine，再確認現有密碼以連結婚禮網站。","Hãy đăng nhập CodeMaru/Dreamine trước, sau đó xác nhận mật khẩu hiện tại để liên kết trang cưới."],
        ["admin.owner"] = ["Primary administrator","Administrador principal","Administrateur principal","Amministratore principale","Administrador principal","대표 관리자","代表管理者","主要管理员","主要管理員","Quản trị viên chính"],
        ["admin.manager"] = ["Administrator","Administrador","Administrateur","Amministratore","Administrador","관리자","管理者","管理员","管理員","Quản trị viên"],
        ["admin.super.session"] = ["Managing this invitation with super-administrator access:","Gestionando esta invitación con acceso de superadministrador:","Gestion de cette invitation avec un accès super administrateur :","Gestione dell’invito con accesso super amministratore:","Gerenciando este convite com acesso de super administrador:","최고 관리자 권한으로 관리 중인 청첩장:","スーパー管理者権限で管理中の招待状:","正在以超级管理员权限管理请柬：","正在以超級管理員權限管理喜帖：","Đang quản lý thiệp bằng quyền quản trị viên cấp cao:"],
        ["admin.basic.hero"] = ["Top title","Título superior","Titre supérieur","Titolo superiore","Título superior","상단 타이틀 문구","上部タイトル","顶部标题","頂部標題","Tiêu đề trên cùng"],
        ["admin.basic.time"] = ["Wedding time","Hora de la boda","Heure du mariage","Ora del matrimonio","Horário do casamento","결혼 시간","挙式時間","婚礼时间","婚禮時間","Giờ cưới"],
        ["admin.basic.time.placeholder"] = ["e.g. 12:00 PM","p. ej. 12:00","ex. 12:00","es. 12:00","ex.: 12:00","예: PM 12:00","例: 12:00","例如：12:00","例如：12:00","VD: 12:00"],
        ["admin.basic.venue"] = ["Venue name","Nombre del lugar","Nom du lieu","Nome della sede","Nome do local","예식장 이름","式場名","婚礼场地名称","婚禮場地名稱","Tên địa điểm cưới"],
        ["admin.basic.address"] = ["Venue address","Dirección del lugar","Adresse du lieu","Indirizzo della sede","Endereço do local","예식장 주소","式場住所","婚礼场地地址","婚禮場地地址","Địa chỉ địa điểm cưới"],
        ["admin.basic.story.ko"] = ["Story (Korean)","Historia (coreano)","Histoire (coréen)","Storia (coreano)","História (coreano)","스토리 (한국어)","ストーリー（韓国語）","故事（韩语）","故事（韓語）","Câu chuyện (tiếng Hàn)"],
        ["admin.basic.story.other"] = ["Story (other language)","Historia (otro idioma)","Histoire (autre langue)","Storia (altra lingua)","História (outro idioma)","스토리 (기타 언어)","ストーリー（その他の言語）","故事（其他语言）","故事（其他語言）","Câu chuyện (ngôn ngữ khác)"],
        ["admin.notice.desc"] = ["Optional text shown in the ceremony notice section. Leave blank to hide it.","Texto opcional de la sección de ceremonia. Déjalo vacío para ocultarlo.","Texte facultatif de la section cérémonie. Laissez vide pour le masquer.","Testo facoltativo della sezione cerimonia. Lascia vuoto per nasconderlo.","Texto opcional da seção da cerimônia. Deixe em branco para ocultar.","청첩장 안내 섹션에 표시할 추가 문구입니다. 비워두면 표시하지 않습니다.","挙式案内に表示する任意の文章です。空欄の場合は表示しません。","这是婚礼说明区显示的可选文字，留空则不显示。","這是婚禮說明區顯示的選填文字，留空則不顯示。","Nội dung tùy chọn hiển thị trong phần thông báo lễ cưới. Để trống để ẩn."],
        ["admin.notice.ai"] = ["You can ask a web AI for text in the tone you want, then paste it here.","Puedes pedir a una IA el tono que desees y pegar el texto aquí.","Demandez à une IA le ton souhaité puis collez le texte ici.","Chiedi a un’IA il tono desiderato e incolla qui il testo.","Peça a uma IA o tom desejado e cole o texto aqui.","Markdown이나 HTML이 익숙하지 않아도 웹 AI에게 원하는 분위기의 문구를 받아 붙여넣을 수 있습니다.","MarkdownやHTMLに不慣れでも、AIに希望の雰囲気を伝えて文章を貼り付けられます。","即使不熟悉 Markdown 或 HTML，也可让 AI 生成所需语气的文案后粘贴。","即使不熟悉 Markdown 或 HTML，也可讓 AI 產生所需語氣的文案後貼上。","Nếu chưa quen Markdown hoặc HTML, bạn có thể nhờ AI viết theo phong cách mong muốn rồi dán vào đây."],
        ["admin.notice.examples"] = ["Ceremony notice examples","Ejemplos de aviso","Exemples d’avis","Esempi di avviso","Exemplos de aviso","예식 안내 예시","挙式案内の例","婚礼说明示例","婚禮說明範例","Ví dụ thông báo lễ cưới"],
        ["admin.notice.warm"] = ["Warm tone","Tono cálido","Ton chaleureux","Tono caloroso","Tom acolhedor","따뜻한 톤","温かいトーン","温馨语气","溫馨語氣","Giọng ấm áp"],
        ["admin.notice.formal"] = ["Formal tone","Tono formal","Ton formel","Tono formale","Tom formal","정중한 톤","丁寧なトーン","正式语气","正式語氣","Giọng trang trọng"],
        ["admin.notice.simple"] = ["Concise tone","Tono conciso","Ton concis","Tono conciso","Tom conciso","간결한 톤","簡潔なトーン","简洁语气","簡潔語氣","Giọng ngắn gọn"],
        ["admin.notice.ai.example"] = ["AI prompt example","Ejemplo para IA","Exemple de requête IA","Esempio prompt IA","Exemplo para IA","AI 요청 예시","AI依頼例","AI 提示示例","AI 提示範例","Ví dụ yêu cầu AI"],
        ["admin.notice.markdown"] = ["Markdown (recommended)","Markdown (recomendado)","Markdown (recommandé)","Markdown (consigliato)","Markdown (recomendado)","Markdown (추천)","Markdown（推奨）","Markdown（推荐）","Markdown（建議）","Markdown (khuyên dùng)"],
        ["admin.notice.markdown.placeholder"] = ["## Ceremony notice\n\nEnter a message for your guests.","## Aviso de ceremonia\n\nEscribe un mensaje para los invitados.","## Informations de cérémonie\n\nSaisissez un message pour vos invités.","## Avviso cerimonia\n\nInserisci un messaggio per gli invitati.","## Aviso da cerimônia\n\nDigite uma mensagem para os convidados.","## 예식 안내\n\n하객분들께 전할 안내 문구를 입력하세요.","## 挙式案内\n\nゲストへの案内文を入力してください。","## 婚礼说明\n\n请输入给宾客的说明。","## 婚禮說明\n\n請輸入給賓客的說明。","## Thông báo lễ cưới\n\nNhập lời nhắn dành cho khách mời."],
        ["admin.notice.markdown.hint"] = ["Markdown — **bold**, *italic*, ## heading; blank lines separate paragraphs.","Markdown — **negrita**, *cursiva*, ## título; líneas vacías separan párrafos.","Markdown — **gras**, *italique*, ## titre ; les lignes vides séparent les paragraphes.","Markdown — **grassetto**, *corsivo*, ## titolo; righe vuote separano i paragrafi.","Markdown — **negrito**, *itálico*, ## título; linhas vazias separam parágrafos.","마크다운 — **굵게**, *기울임*, ## 제목, 빈 줄로 문단 구분.","Markdown — **太字**、*斜体*、## 見出し、空行で段落を区切ります。","Markdown — **粗体**、*斜体*、## 标题，空行分段。","Markdown — **粗體**、*斜體*、## 標題，空行分段。","Markdown — **đậm**, *nghiêng*, ## tiêu đề; dòng trống ngăn cách đoạn."],
        ["admin.notice.html.placeholder"] = ["<p>Enter a message for your guests.</p>","<p>Escribe un mensaje para los invitados.</p>","<p>Saisissez un message pour vos invités.</p>","<p>Inserisci un messaggio per gli invitati.</p>","<p>Digite uma mensagem para os convidados.</p>","<p>하객분들께 전할 안내 문구를 입력하세요.</p>","<p>ゲストへの案内文を入力してください。</p>","<p>请输入给宾客的说明。</p>","<p>請輸入給賓客的說明。</p>","<p>Nhập lời nhắn dành cho khách mời.</p>"],
        ["admin.notice.html.hint"] = ["Enter HTML tags directly.","Introduce etiquetas HTML directamente.","Saisissez directement les balises HTML.","Inserisci direttamente i tag HTML.","Digite as tags HTML diretamente.","HTML 태그를 직접 입력합니다.","HTMLタグを直接入力します。","直接输入 HTML 标签。","直接輸入 HTML 標籤。","Nhập trực tiếp thẻ HTML."],
        ["admin.notice.html.preview"] = ["HTML preview","Vista previa HTML","Aperçu HTML","Anteprima HTML","Prévia HTML","HTML 미리보기","HTMLプレビュー","HTML 预览","HTML 預覽","Xem trước HTML"],
        ["admin.notice.preview.empty"] = ["Your content will appear here.","El contenido aparecerá aquí.","Votre contenu apparaîtra ici.","Il contenuto apparirà qui.","Seu conteúdo aparecerá aqui.","입력한 내용이 여기에 표시됩니다.","入力内容がここに表示されます。","输入内容将显示在这里。","輸入內容將顯示在這裡。","Nội dung sẽ hiển thị tại đây."],
        ["common.current"] = ["Current","Actual","Actuel","Attuale","Atual","현재","現在","当前","目前","Hiện tại"],
        ["common.remove"] = ["Remove","Quitar","Retirer","Rimuovi","Remover","제거","削除","移除","移除","Xóa"],
        ["common.delete"] = ["Delete","Eliminar","Supprimer","Elimina","Excluir","삭제","削除","删除","刪除","Xóa"],
        ["common.uploading"] = ["Uploading...","Subiendo...","Téléversement...","Caricamento...","Enviando...","업로드 중...","アップロード中...","正在上传...","正在上傳...","Đang tải lên..."],
        ["common.seconds"] = ["seconds","segundos","secondes","secondi","segundos","초","秒","秒","秒","giây"],
        ["admin.media.music"] = ["Background music","Música de fondo","Musique de fond","Musica di sottofondo","Música de fundo","배경 음악","BGM","背景音乐","背景音樂","Nhạc nền"],
        ["admin.media.music.empty"] = ["Upload an mp3, ogg or m4a file (max 30 MB).","Sube un archivo mp3, ogg o m4a (máx. 30 MB).","Importez un fichier mp3, ogg ou m4a (30 Mo max).","Carica un file mp3, ogg o m4a (max 30 MB).","Envie um arquivo mp3, ogg ou m4a (máx. 30 MB).","배경 음악이 없습니다. mp3·ogg·m4a 파일을 업로드하세요. (최대 30MB)","mp3・ogg・m4aファイルをアップロードしてください（最大30MB）。","请上传 mp3、ogg 或 m4a 文件（最大30MB）。","請上傳 mp3、ogg 或 m4a 檔案（最大30MB）。","Tải lên tệp mp3, ogg hoặc m4a (tối đa 30 MB)."],
        ["admin.media.position"] = ["Music button position","Posición del botón de música","Position du bouton musique","Posizione pulsante musica","Posição do botão de música","음악 버튼 위치","音楽ボタンの位置","音乐按钮位置","音樂按鈕位置","Vị trí nút nhạc"],
        ["admin.media.position.hint"] = ["Drag the music button in the preview to save its position.","Arrastra el botón en la vista previa para guardar su posición.","Faites glisser le bouton dans l’aperçu pour enregistrer sa position.","Trascina il pulsante nell’anteprima per salvarne la posizione.","Arraste o botão na prévia para salvar a posição.","오른쪽 미리보기의 음악 버튼을 원하는 위치로 끌어 놓으면 자동 저장됩니다.","プレビューの音楽ボタンをドラッグすると位置が保存されます。","拖动预览中的音乐按钮即可保存位置。","拖曳預覽中的音樂按鈕即可儲存位置。","Kéo nút nhạc trong bản xem trước để lưu vị trí."],
        ["admin.media.default.position"] = ["Default position","Posición predeterminada","Position par défaut","Posizione predefinita","Posição padrão","기본 위치","初期位置","默认位置","預設位置","Vị trí mặc định"],
        ["admin.media.video"] = ["Our video","Nuestro vídeo","Notre vidéo","Il nostro video","Nosso vídeo","우리의 영상","私たちの動画","我们的视频","我們的影片","Video của chúng tôi"],
        ["admin.media.gallery"] = ["Gallery photos","Fotos de la galería","Photos de la galerie","Foto della galleria","Fotos da galeria","갤러리 사진","ギャラリー写真","相册照片","相簿照片","Ảnh thư viện"],
        ["admin.media.interval"] = ["Autoplay interval","Intervalo de reproducción","Intervalle de lecture","Intervallo automatico","Intervalo automático","자동재생 간격","自動再生間隔","自动播放间隔","自動播放間隔","Khoảng tự động phát"],
        ["admin.map.coordinates"] = ["Map coordinates","Coordenadas del mapa","Coordonnées de la carte","Coordinate mappa","Coordenadas do mapa","지도 좌표","地図座標","地图坐标","地圖座標","Tọa độ bản đồ"],
        ["admin.map.latlng"] = ["Latitude · Longitude","Latitud · Longitud","Latitude · Longitude","Latitudine · Longitudine","Latitude · Longitude","위도 · 경도","緯度・経度","纬度 · 经度","緯度 · 經度","Vĩ độ · Kinh độ"],
        ["admin.map.search"] = ["Find coordinates","Buscar coordenadas","Rechercher les coordonnées","Trova coordinate","Buscar coordenadas","좌표 자동 검색","座標を検索","查找坐标","查找座標","Tìm tọa độ"],
        ["admin.map.searching"] = ["Searching...","Buscando...","Recherche...","Ricerca...","Pesquisando...","검색 중...","検索中...","正在搜索...","正在搜尋...","Đang tìm..."],
        ["admin.map.latitude"] = ["Latitude","Latitud","Latitude","Latitudine","Latitude","위도","緯度","纬度","緯度","Vĩ độ"],
        ["admin.map.longitude"] = ["Longitude","Longitud","Longitude","Longitudine","Longitude","경도","経度","经度","經度","Kinh độ"],
        ["admin.map.links"] = ["Map app links","Enlaces de mapas","Liens vers les cartes","Link alle mappe","Links de mapas","지도 앱 링크","地図アプリリンク","地图应用链接","地圖應用程式連結","Liên kết ứng dụng bản đồ"],
        ["admin.map.generate"] = ["Generate automatically","Generar automáticamente","Générer automatiquement","Genera automaticamente","Gerar automaticamente","자동 생성","自動生成","自动生成","自動產生","Tạo tự động"],
        ["admin.map.roadmap"] = ["Directions image","Imagen de acceso","Plan d’accès","Immagine indicazioni","Imagem de acesso","약도 이미지","案内図画像","路线图图片","路線圖圖片","Ảnh chỉ đường"],
        ["admin.payment.title"] = ["Where to send your wishes","Dónde enviar los regalos","Où envoyer vos vœux","Dove inviare gli auguri","Onde enviar presentes","마음 전하실 곳","ご祝儀のご案内","礼金信息","禮金資訊","Nơi gửi lời chúc"],
        ["admin.payment.hint"] = ["Add up to eight people. A payment account or contact alone is enough.","Añade hasta ocho personas. Basta una cuenta o contacto.","Ajoutez jusqu’à huit personnes. Un compte ou contact suffit.","Aggiungi fino a otto persone. Basta un conto o contatto.","Adicione até oito pessoas. Uma conta ou contato é suficiente.","신랑·신부·부모님 등 최대 8명까지 등록할 수 있습니다. 계좌 또는 연락처만 입력해도 됩니다.","最大8名まで登録できます。口座または連絡先のみでも構いません。","最多可添加8人，仅填写账户或联系方式也可以。","最多可新增8人，只填帳戶或聯絡方式也可以。","Thêm tối đa 8 người; chỉ cần tài khoản hoặc liên hệ."],
        ["admin.payment.label"] = ["Label (display name)","Etiqueta (nombre visible)","Libellé (nom affiché)","Etichetta (nome visualizzato)","Rótulo (nome exibido)","레이블 (표시 이름)","ラベル（表示名）","标签（显示名称）","標籤（顯示名稱）","Nhãn (tên hiển thị)"],
        ["admin.payment.custom"] = ["Custom","Personalizado","Personnalisé","Personalizzato","Personalizado","직접 입력","カスタム","自定义","自訂","Tùy chỉnh"],
        ["admin.payment.groom"] = ["Groom","Novio","Marié","Sposo","Noivo","신랑","新郎","新郎","新郎","Chú rể"],
        ["admin.payment.bride"] = ["Bride","Novia","Mariée","Sposa","Noiva","신부","新婦","新娘","新娘","Cô dâu"],
        ["admin.payment.name"] = ["Name","Nombre","Nom","Nome","Nome","이름","名前","姓名","姓名","Tên"],
        ["admin.payment.contact"] = ["Contact","Contacto","Contact","Contatto","Contato","연락처","連絡先","联系方式","聯絡方式","Liên hệ"],
        ["admin.payment.bank"] = ["Bank","Banco","Banque","Banca","Banco","은행명","銀行名","银行","銀行","Ngân hàng"],
        ["admin.payment.number"] = ["Account number","Número de cuenta","Numéro de compte","Numero conto","Número da conta","계좌번호","口座番号","账号","帳號","Số tài khoản"],
        ["admin.payment.holder"] = ["Account holder","Titular","Titulaire","Intestatario","Titular","예금주","口座名義","账户持有人","帳戶持有人","Chủ tài khoản"],
        ["admin.payment.add"] = ["Add account / contact","Añadir cuenta / contacto","Ajouter compte / contact","Aggiungi conto / contatto","Adicionar conta / contato","계좌 / 연락처 추가","口座／連絡先を追加","添加账户/联系方式","新增帳戶／聯絡方式","Thêm tài khoản / liên hệ"],
        ["admin.share.mode"] = ["Site mode","Modo del sitio","Mode du site","Modalità sito","Modo do site","사이트 모드","サイトモード","网站模式","網站模式","Chế độ trang"],
        ["admin.share.invite"] = ["Invitation","Invitación","Invitation","Invito","Convite","청첩장 (예식 안내)","招待状","婚礼请柬","婚禮喜帖","Thiệp cưới"],
        ["admin.share.thankyou"] = ["Thank-you page","Página de agradecimiento","Page de remerciement","Pagina di ringraziamento","Página de agradecimento","감사장 (예식 후)","お礼状","感谢页","感謝頁","Trang cảm ơn"],
        ["admin.share.both"] = ["Invitation + thank-you","Invitación + agradecimiento","Invitation + remerciement","Invito + ringraziamento","Convite + agradecimento","청첩장 + 감사장","招待状＋お礼状","请柬 + 感谢页","喜帖＋感謝頁","Thiệp cưới + cảm ơn"],
        ["admin.share.home"] = ["Show on home","Mostrar en inicio","Afficher à l’accueil","Mostra in home","Mostrar no início","메인 페이지 노출","ホームに表示","在首页显示","顯示於首頁","Hiển thị trang chủ"],
        ["admin.share.seo"] = ["Search engine visibility","Visibilidad en buscadores","Visibilité dans les moteurs","Visibilità motori di ricerca","Visibilidade nos buscadores","검색 사이트 외부 노출","検索エンジン公開","搜索引擎可见性","搜尋引擎可見性","Hiển thị trên công cụ tìm kiếm"],
        ["admin.share.search.title"] = ["Search result title","Título del resultado","Titre du résultat","Titolo risultato","Título do resultado","검색 결과 제목","検索結果タイトル","搜索结果标题","搜尋結果標題","Tiêu đề kết quả tìm kiếm"],
        ["admin.share.search.description"] = ["Search result description","Descripción del resultado","Description du résultat","Descrizione risultato","Descrição do resultado","검색 결과 설명","検索結果の説明","搜索结果描述","搜尋結果說明","Mô tả kết quả tìm kiếm"],
        ["admin.share.og"] = ["Invitation link preview (OG)","Vista previa del enlace (OG)","Aperçu du lien (OG)","Anteprima link (OG)","Prévia do link (OG)","청첩장 링크 미리보기 (OG)","招待状リンクプレビュー（OG）","请柬链接预览（OG）","喜帖連結預覽（OG）","Xem trước liên kết thiệp (OG)"],
        ["admin.share.og.thankyou"] = ["Thank-you link preview (OG)","Vista previa de agradecimiento (OG)","Aperçu du lien de remerciement (OG)","Anteprima ringraziamento (OG)","Prévia de agradecimento (OG)","자동 감사장 링크 미리보기 (OG)","お礼状リンクプレビュー（OG）","感谢页链接预览（OG）","感謝頁連結預覽（OG）","Xem trước liên kết cảm ơn (OG)"],
        ["admin.share.og.title"] = ["Preview title","Título de vista previa","Titre de l’aperçu","Titolo anteprima","Título da prévia","미리보기 제목","プレビュータイトル","预览标题","預覽標題","Tiêu đề xem trước"],
        ["admin.share.og.description"] = ["Preview description","Descripción de vista previa","Description de l’aperçu","Descrizione anteprima","Descrição da prévia","미리보기 설명","プレビュー説明","预览描述","預覽說明","Mô tả xem trước"],
        ["admin.share.og.image"] = ["Preview image","Imagen de vista previa","Image d’aperçu","Immagine anteprima","Imagem da prévia","미리보기 이미지","プレビュー画像","预览图片","預覽圖片","Ảnh xem trước"],
        ["admin.share.users"] = ["Administrators","Administradores","Administrateurs","Amministratori","Administradores","관리자 계정","管理者アカウント","管理员账户","管理員帳戶","Tài khoản quản trị"],
        ["admin.share.password"] = ["Admin password","Contraseña de administración","Mot de passe administrateur","Password amministratore","Senha de administração","어드민 비밀번호","管理パスワード","管理员密码","管理員密碼","Mật khẩu quản trị"],
        ["admin.preview.phone"] = ["Phone","Móvil","Téléphone","Telefono","Telefone","폰","スマホ","手机","手機","Điện thoại"],
        ["admin.preview.refresh"] = ["Refresh preview","Actualizar vista previa","Actualiser l’aperçu","Aggiorna anteprima","Atualizar prévia","미리보기 새로고침","プレビューを更新","刷新预览","重新整理預覽","Làm mới xem trước"],
        ["admin.preview.newtab"] = ["Open in new tab","Abrir en una pestaña nueva","Ouvrir dans un nouvel onglet","Apri in nuova scheda","Abrir em nova guia","새 탭에서 열기","新しいタブで開く","在新标签页中打开","在新分頁開啟","Mở trong tab mới"],
        ["admin.preview.hint"] = ["The preview refreshes automatically after layout, theme or settings changes.","La vista previa se actualiza automáticamente tras los cambios.","L’aperçu s’actualise automatiquement après les modifications.","L’anteprima si aggiorna automaticamente dopo le modifiche.","A prévia atualiza automaticamente após alterações.","레이아웃 적용·테마 변경·설정 저장 시 자동으로 새로고침됩니다.","レイアウト・テーマ・設定の変更後に自動更新されます。","布局、主题或设置更改后会自动刷新预览。","版面、主題或設定變更後會自動重新整理預覽。","Bản xem trước tự làm mới sau khi đổi bố cục, giao diện hoặc cài đặt."],
        ["admin.preview.title"] = ["Invitation preview","Vista previa de la invitación","Aperçu de l’invitation","Anteprima invito","Prévia do convite","청첩장 미리보기","招待状プレビュー","请柬预览","喜帖預覽","Xem trước thiệp cưới"],
        ["admin.preview.splitter"] = ["Drag to resize; double-click to reset","Arrastra para ajustar; doble clic para restablecer","Faites glisser pour redimensionner ; double-cliquez pour réinitialiser","Trascina per ridimensionare; doppio clic per ripristinare","Arraste para redimensionar; clique duas vezes para redefinir","드래그: 폭 조정 · 더블클릭: 기본값 복원","ドラッグで幅調整・ダブルクリックでリセット","拖动调整宽度，双击重置","拖曳調整寬度，雙擊重設","Kéo để đổi kích thước; nhấp đúp để đặt lại"],
        ["admin.super.connected"] = ["Connected with super-administrator access.","Conectado con acceso de superadministrador.","Connecté avec un accès super administrateur.","Connesso con accesso super amministratore.","Conectado com acesso de super administrador.","슈퍼관리자 권한으로 접속했습니다.","スーパー管理者権限で接続しました。","已使用超级管理员权限连接。","已使用超級管理員權限連線。","Đã kết nối bằng quyền quản trị viên cấp cao."],
        ["admin.design.layout"] = ["Invitation layout","Diseño de invitación","Mise en page de l’invitation","Layout invito","Layout do convite","청첩장 레이아웃","招待状レイアウト","请柬布局","喜帖版面","Bố cục thiệp cưới"],
        ["admin.design.layout.hint"] = ["Choose a layout to update the preview; save settings to publish it.","Elige un diseño para actualizar la vista previa; guarda para publicarlo.","Choisissez une mise en page pour actualiser l’aperçu, puis enregistrez.","Scegli un layout per aggiornare l’anteprima, quindi salva.","Escolha um layout para atualizar a prévia e salve para publicar.","레이아웃을 적용하면 미리보기에 즉시 반영되며 설정 저장 시 공개 화면에 확정됩니다.","レイアウトを選ぶとプレビューに反映され、保存すると公開されます。","选择布局后预览会立即更新，保存设置后发布。","選擇版面後預覽會立即更新，儲存設定後發佈。","Chọn bố cục để cập nhật xem trước; lưu cài đặt để xuất bản."],
        ["admin.design.select"] = ["Select layout","Seleccionar diseño","Choisir la mise en page","Seleziona layout","Selecionar layout","레이아웃 선택","レイアウトを選択","选择布局","選擇版面","Chọn bố cục"],
        ["admin.design.none"] = ["No layouts available","No hay diseños disponibles","Aucune mise en page disponible","Nessun layout disponibile","Nenhum layout disponível","선택 가능한 레이아웃 없음","利用可能なレイアウトがありません","没有可用布局","沒有可用版面","Không có bố cục"],
        ["admin.design.search"] = ["Search layouts","Buscar diseños","Rechercher les mises en page","Cerca layout","Pesquisar layouts","레이아웃 검색","レイアウト検索","搜索布局","搜尋版面","Tìm bố cục"],
        ["admin.design.noresults"] = ["No results.","Sin resultados.","Aucun résultat.","Nessun risultato.","Nenhum resultado.","검색 결과가 없습니다.","検索結果がありません。","没有结果。","沒有結果。","Không có kết quả."],
        ["admin.design.applied"] = ["Applied","Aplicado","Appliqué","Applicato","Aplicado","적용됨","適用済み","已应用","已套用","Đã áp dụng"],
        ["admin.design.preparing"] = ["Coming soon","Próximamente","Bientôt disponible","In preparazione","Em breve","준비 중","準備中","即将推出","準備中","Sắp ra mắt"],
        ["admin.design.locked"] = ["Locked","Bloqueado","Verrouillé","Bloccato","Bloqueado","잠금","ロック","已锁定","已鎖定","Đã khóa"],
        ["admin.design.sections"] = ["Mobile section order","Orden de secciones móviles","Ordre des sections mobiles","Ordine sezioni mobile","Ordem das seções móveis","모바일 섹션 순서","モバイルセクション順","移动端区块顺序","行動版區塊順序","Thứ tự mục trên di động"],
        ["admin.design.recommended"] = ["Recommended order","Orden recomendado","Ordre recommandé","Ordine consigliato","Ordem recomendada","추천 순서","推奨順序","推荐顺序","建議順序","Thứ tự đề xuất"],
        ["admin.design.fixed"] = ["Fixed","Fijo","Fixe","Fisso","Fixo","고정","固定","固定","固定","Cố định"],
        ["admin.design.up"] = ["Up","Subir","Monter","Su","Subir","위","上","上移","上移","Lên"],
        ["admin.design.down"] = ["Down","Bajar","Descendre","Giù","Descer","아래","下","下移","下移","Xuống"],
        ["admin.design.hide"] = ["Hide","Ocultar","Masquer","Nascondi","Ocultar","숨김","非表示","隐藏","隱藏","Ẩn"],
        ["admin.design.show"] = ["Show","Mostrar","Afficher","Mostra","Mostrar","표시","表示","显示","顯示","Hiện"],
        ["admin.design.colors"] = ["Theme colors","Colores del tema","Couleurs du thème","Colori tema","Cores do tema","테마 색상","テーマカラー","主题颜色","主題色彩","Màu giao diện"]
    };

    public string Language { get; private set; } = "ko";
    public string HtmlLanguage => Languages.First(x => x.Code == Language).HtmlLanguage;
    public event Action? Changed;

    public string this[string key]
    {
        get
        {
            if (!Texts.TryGetValue(key, out var values)) return key;
            var index = Array.IndexOf(Codes, Language);
            return values[index < 0 ? 5 : index];
        }
    }

    public void SetLanguage(string? language)
    {
        var normalized = language?.Trim().ToLowerInvariant().Replace('_', '-');
        if (!Codes.Contains(normalized)) normalized = "ko";
        if (Language == normalized) return;
        Language = normalized!;
        Changed?.Invoke();
    }
}
