using System.Reflection;
using Dreamine.Database.Abstractions.Mapping;
using Dreamine.Database.Core.Mapping;
using Dreamine.Database.MySql;
using Dreamine.Database.Oracle;
using Dreamine.Database.SqlServer;
using Dreamine.Database.Sqlite;

namespace Dreamine.FullKit.Tests.Database;

public sealed class DatabaseProviderDialectTests
{
    [Fact]
    public void SqliteProvider_BuildsSqliteCreateTableSql()
    {
        var sql = BuildCreateTableSql(new SqliteDatabaseProvider("Data Source=:memory:"));

        Assert.Contains("\"DialectSamples\"", sql);
        Assert.Contains("\"Id\" INTEGER PRIMARY KEY AUTOINCREMENT", sql);
        Assert.Contains("\"Name\" TEXT", sql);
    }

    [Fact]
    public void MySqlProvider_BuildsMySqlCreateTableSql()
    {
        var sql = BuildCreateTableSql(new MySqlDatabaseProvider("Server=localhost;Database=dreamine;User Id=user;Password=password;"));

        Assert.Contains("`DialectSamples`", sql);
        Assert.Contains("`Id` INT AUTO_INCREMENT PRIMARY KEY", sql);
        Assert.Contains("`Name` TEXT", sql);
    }

    [Fact]
    public void OracleProvider_BuildsOracleCreateTableSql()
    {
        var sql = BuildCreateTableSql(new OracleDatabaseProvider("User Id=user;Password=password;Data Source=localhost/XEPDB1;"));

        Assert.Contains("\"DIALECTSAMPLES\"", sql);
        Assert.Contains("\"ID\" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql);
        Assert.Contains("\"NAME\" NVARCHAR2(2000)", sql);
    }

    [Fact]
    public void SqlServerProvider_BuildsSqlServerCreateTableSql()
    {
        var sql = BuildCreateTableSql(new SqlServerDatabaseProvider("Server=localhost;Database=dreamine;User Id=user;Password=password;TrustServerCertificate=True;"));

        Assert.Contains("IF OBJECT_ID", sql);
        Assert.Contains("[DialectSamples]", sql);
        Assert.Contains("[Id] INT IDENTITY(1,1) PRIMARY KEY", sql);
        Assert.Contains("[Name] NVARCHAR(MAX)", sql);
    }

    [Fact]
    public void DatabaseEntityMap_CachesMapsPerEntityType()
    {
        var first = DatabaseEntityMap.Create<DialectSample>();
        var second = DatabaseEntityMap.Create<DialectSample>();

        Assert.Same(first, second);
        Assert.Same(first.InsertableProperties, second.InsertableProperties);
        Assert.Same(first.UpdatableProperties, second.UpdatableProperties);
    }

    [Fact]
    public void DatabaseProviderBase_SqlCache_ReturnsSameStringReferenceOnSubsequentCalls()
    {
        // GetOrBuildSql<T> caches INSERT/UPDATE/DELETE SQL strings per (entity type, provider kind).
        // Calling the method twice must return the same string reference — no redundant rebuild.
        var provider = new SqliteDatabaseProvider("Data Source=:memory:");

        // GetOrBuildSql is declared on the abstract base class — search the hierarchy.
        var baseType = provider.GetType().BaseType
            ?? throw new InvalidOperationException("DatabaseProviderBase not found.");
        var getOrBuildSql = baseType
            .GetMethod("GetOrBuildSql", BindingFlags.Instance | BindingFlags.NonPublic)
            ?.MakeGenericMethod(typeof(DialectSample))
            ?? throw new InvalidOperationException("GetOrBuildSql<T> not found via reflection.");

        // SqlKind is a private nested enum on the abstract base class.
        var sqlKindType = baseType.GetNestedType("SqlKind", BindingFlags.NonPublic)
            ?? throw new InvalidOperationException("SqlKind enum not found on base type.");
        var insertKind = Enum.ToObject(sqlKindType, 0); // 0 = Insert

        var first  = (string)getOrBuildSql.Invoke(provider, [insertKind])!;
        var second = (string)getOrBuildSql.Invoke(provider, [insertKind])!;

        Assert.Same(first, second);
    }

    private static string BuildCreateTableSql(object provider)
    {
        var method = provider
            .GetType()
            .GetMethod("BuildCreateTableSql", BindingFlags.Instance | BindingFlags.NonPublic)
            ?? throw new InvalidOperationException("BuildCreateTableSql was not found.");

        var map = DatabaseEntityMap.Create<DialectSample>();
        return (string)method.Invoke(provider, [map])!;
    }

    [DatabaseTable("DialectSamples")]
    private sealed class DialectSample
    {
        [DatabaseKey]
        [DatabaseGenerated]
        public int Id { get; set; }

        public string Name { get; set; } = string.Empty;

        public DateTime CreatedAt { get; set; }
    }
}
