using System.Reflection;
using Dreamine.Database.Abstractions.Mapping;
using Dreamine.Database.Core.Mapping;
using Dreamine.Database.MySql;
using Dreamine.Database.Oracle;
using Dreamine.Database.SqlServer;
using Dreamine.Database.Sqlite;

namespace Dreamine.FullKit.Tests.Database;

public sealed class DatabaseProviderDialectTests
{
    [Fact]
    public void SqliteProvider_BuildsSqliteCreateTableSql()
    {
        var sql = BuildCreateTableSql(new SqliteDatabaseProvider("Data Source=:memory:"));

        Assert.Contains("\"DialectSamples\"", sql);
        Assert.Contains("\"Id\" INTEGER PRIMARY KEY AUTOINCREMENT", sql);
        Assert.Contains("\"Name\" TEXT", sql);
    }

    [Fact]
    public void MySqlProvider_BuildsMySqlCreateTableSql()
    {
        var sql = BuildCreateTableSql(new MySqlDatabaseProvider("Server=localhost;Database=dreamine;User Id=user;Password=password;"));

        Assert.Contains("`DialectSamples`", sql);
        Assert.Contains("`Id` INT AUTO_INCREMENT PRIMARY KEY", sql);
        Assert.Contains("`Name` TEXT", sql);
    }

    [Fact]
    public void OracleProvider_BuildsOracleCreateTableSql()
    {
        var sql = BuildCreateTableSql(new OracleDatabaseProvider("User Id=user;Password=password;Data Source=localhost/XEPDB1;"));

        Assert.Contains("\"DIALECTSAMPLES\"", sql);
        Assert.Contains("\"ID\" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql);
        Assert.Contains("\"NAME\" NVARCHAR2(2000)", sql);
    }

    [Fact]
    public void SqlServerProvider_BuildsSqlServerCreateTableSql()
    {
        var sql = BuildCreateTableSql(new SqlServerDatabaseProvider("Server=localhost;Database=dreamine;User Id=user;Password=password;TrustServerCertificate=True;"));

        Assert.Contains("IF OBJECT_ID", sql);
        Assert.Contains("[DialectSamples]", sql);
        Assert.Contains("[Id] INT IDENTITY(1,1) PRIMARY KEY", sql);
        Assert.Contains("[Name] NVARCHAR(MAX)", sql);
    }

    private static string BuildCreateTableSql(object provider)
    {
        var method = provider
            .GetType()
            .GetMethod("BuildCreateTableSql", BindingFlags.Instance | BindingFlags.NonPublic)
            ?? throw new InvalidOperationException("BuildCreateTableSql was not found.");

        var map = DatabaseEntityMap.Create<DialectSample>();
        return (string)method.Invoke(provider, [map])!;
    }

    [DatabaseTable("DialectSamples")]
    private sealed class DialectSample
    {
        [DatabaseKey]
        [DatabaseGenerated]
        public int Id { get; set; }

        public string Name { get; set; } = string.Empty;

        public DateTime CreatedAt { get; set; }
    }
}
