classDiagram
    class EventToCommandBehavior {
        +string EventName
        +IRelayCommand Command
        +object CommandParameter
        #OnAttached() void
        -OnEventRaised(object, EventArgs) void
    }
    class DoubleClickBehavior {
        +IRelayCommand Command
        +object CommandParameter
        #OnAttached() void
    }
    class KeyBindingBehavior {
        +Key Key
        +ModifierKeys Modifiers
        +IRelayCommand Command
        #OnAttached() void
    }
    class ValidationBehavior {
        +string PropertyName
        +string ErrorMessage
        #OnAttached() void
        +Validate() bool
    }
    class BehaviorBase~T~ {
        <<abstract>>
    }
    BehaviorBase~T~ <|-- EventToCommandBehavior
    BehaviorBase~T~ <|-- DoubleClickBehavior
    BehaviorBase~T~ <|-- KeyBindingBehavior
    BehaviorBase~T~ <|-- ValidationBehavior