namespace ShopPlatform.Services;

/// <summary>Localized copy used by the shop and platform administration screens.</summary>
public static class ShopAdminText
{
    private static readonly string[] Codes = ["en", "es", "fr", "it", "pt", "ko", "ja", "zh-hans", "zh-hant", "vi"];

    private static readonly Dictionary<string, string[]> Common = new(StringComparer.OrdinalIgnoreCase)
    {
        ["common.active"] = ["Active", "Activo", "Actif", "Attivo", "Ativo", "운영 중", "稼働中", "运营中", "營運中", "Đang hoạt động"],
        ["common.address"] = ["Address", "Dirección", "Adresse", "Indirizzo", "Endereço", "주소", "住所", "地址", "地址", "Địa chỉ"],
        ["common.admin"] = ["Admin", "Administrador", "Administration", "Amministrazione", "Administrador", "어드민", "管理", "管理后台", "管理後台", "Quản trị"],
        ["common.administrators"] = ["Administrators", "Administradores", "Administrateurs", "Amministratori", "Administradores", "관리자", "管理者", "管理员", "管理員", "Quản trị viên"],
        ["common.cancel"] = ["Cancel", "Cancelar", "Annuler", "Annulla", "Cancelar", "취소", "キャンセル", "取消", "取消", "Hủy"],
        ["common.create"] = ["Create", "Crear", "Créer", "Crea", "Criar", "생성", "作成", "创建", "建立", "Tạo"],
        ["common.createdAt"] = ["Created", "Creado", "Créé le", "Creato il", "Criado em", "생성일", "作成日", "创建日期", "建立日期", "Ngày tạo"],
        ["common.delete"] = ["Delete", "Eliminar", "Supprimer", "Elimina", "Excluir", "삭제", "削除", "删除", "刪除", "Xóa"],
        ["common.description"] = ["Description", "Descripción", "Description", "Descrizione", "Descrição", "설명", "説明", "说明", "說明", "Mô tả"],
        ["common.edit"] = ["Edit", "Editar", "Modifier", "Modifica", "Editar", "수정", "編集", "编辑", "編輯", "Sửa"],
        ["common.email"] = ["Email", "Correo electrónico", "E-mail", "Email", "E-mail", "이메일", "メール", "电子邮箱", "電子郵件", "Email"],
        ["common.errorWithMessage"] = ["Error: {0}", "Error: {0}", "Erreur : {0}", "Errore: {0}", "Erro: {0}", "오류: {0}", "エラー: {0}", "错误：{0}", "錯誤：{0}", "Lỗi: {0}"],
        ["common.image"] = ["Image", "Imagen", "Image", "Immagine", "Imagem", "이미지", "画像", "图片", "圖片", "Hình ảnh"],
        ["common.inactive"] = ["Inactive", "Inactivo", "Inactif", "Non attivo", "Inativo", "비활성", "無効", "未启用", "未啟用", "Không hoạt động"],
        ["common.test"] = ["Test", "Prueba", "Test", "Test", "Teste", "테스트", "テスト", "测试", "測試", "Thử nghiệm"],
        ["common.live"] = ["Live", "Producción", "Production", "Produzione", "Produção", "운영", "本番", "正式", "正式", "Thực tế"],
        ["common.invalidPassword"] = ["The password is incorrect.", "La contraseña es incorrecta.", "Le mot de passe est incorrect.", "La password non è corretta.", "A senha está incorreta.", "비밀번호가 올바르지 않습니다.", "パスワードが正しくありません。", "密码不正确。", "密碼不正確。", "Mật khẩu không đúng."],
        ["common.krw"] = ["KRW", "KRW", "KRW", "KRW", "KRW", "원", "ウォン", "韩元", "韓元", "KRW"],
        ["common.loading"] = ["Loading…", "Cargando…", "Chargement…", "Caricamento…", "Carregando…", "로딩 중…", "読み込み中…", "加载中…", "載入中…", "Đang tải…"],
        ["common.manage"] = ["Manage", "Gestionar", "Gérer", "Gestisci", "Gerenciar", "관리", "管理", "管理", "管理", "Quản lý"],
        ["common.name"] = ["Name", "Nombre", "Nom", "Nome", "Nome", "이름", "名前", "姓名", "姓名", "Tên"],
        ["common.notConfigured"] = ["Not configured", "Sin configurar", "Non configuré", "Non configurato", "Não configurado", "미설정", "未設定", "未配置", "未設定", "Chưa cấu hình"],
        ["common.password"] = ["Password", "Contraseña", "Mot de passe", "Password", "Senha", "비밀번호", "パスワード", "密码", "密碼", "Mật khẩu"],
        ["common.payment"] = ["Payment", "Pago", "Paiement", "Pagamento", "Pagamento", "결제", "決済", "支付", "付款", "Thanh toán"],
        ["common.phone"] = ["Phone", "Teléfono", "Téléphone", "Telefono", "Telefone", "전화", "電話", "电话", "電話", "Điện thoại"],
        ["common.preview"] = ["Preview", "Vista previa", "Aperçu", "Anteprima", "Prévia", "미리보기", "プレビュー", "预览", "預覽", "Xem trước"],
        ["common.remove"] = ["Remove", "Quitar", "Retirer", "Rimuovi", "Remover", "제거", "削除", "移除", "移除", "Gỡ bỏ"],
        ["common.save"] = ["Save", "Guardar", "Enregistrer", "Salva", "Salvar", "저장", "保存", "保存", "儲存", "Lưu"],
        ["common.saved"] = ["Saved.", "Guardado.", "Enregistré.", "Salvato.", "Salvo.", "저장되었습니다.", "保存しました。", "已保存。", "已儲存。", "Đã lưu."],
        ["common.saveFailed"] = ["Save failed: {0}", "Error al guardar: {0}", "Échec de l’enregistrement : {0}", "Salvataggio non riuscito: {0}", "Falha ao salvar: {0}", "저장 실패: {0}", "保存に失敗しました: {0}", "保存失败：{0}", "儲存失敗：{0}", "Lưu thất bại: {0}"],
        ["common.shop"] = ["Online store", "Tienda en línea", "Boutique en ligne", "Negozio online", "Loja virtual", "쇼핑몰", "オンラインショップ", "网上商城", "網路商店", "Cửa hàng trực tuyến"],
        ["common.shopName"] = ["Store name", "Nombre de la tienda", "Nom de la boutique", "Nome del negozio", "Nome da loja", "쇼핑몰 이름", "ショップ名", "商城名称", "商店名稱", "Tên cửa hàng"],
        ["common.signIn"] = ["Sign in", "Iniciar sesión", "Se connecter", "Accedi", "Entrar", "로그인", "ログイン", "登录", "登入", "Đăng nhập"],
        ["common.signOut"] = ["Sign out", "Cerrar sesión", "Se déconnecter", "Esci", "Sair", "로그아웃", "ログアウト", "退出登录", "登出", "Đăng xuất"],
        ["common.status"] = ["Status", "Estado", "Statut", "Stato", "Status", "상태", "状態", "状态", "狀態", "Trạng thái"],
        ["common.uploadFailed"] = ["Upload failed: {0}", "Error al subir: {0}", "Échec de l’import : {0}", "Caricamento non riuscito: {0}", "Falha no upload: {0}", "업로드 실패: {0}", "アップロードに失敗しました: {0}", "上传失败：{0}", "上傳失敗：{0}", "Tải lên thất bại: {0}"],
        ["common.uploading"] = ["Uploading…", "Subiendo…", "Import en cours…", "Caricamento…", "Enviando…", "업로드 중…", "アップロード中…", "上传中…", "上傳中…", "Đang tải lên…"],
        ["common.view"] = ["View", "Ver", "Voir", "Visualizza", "Ver", "보기", "表示", "查看", "查看", "Xem"]
    };

    private static readonly Dictionary<string, string[]> Administration = new(StringComparer.OrdinalIgnoreCase)
    {
        ["shopAdmin.pageTitle"] = ["Admin", "Administración", "Administration", "Amministrazione", "Administração", "어드민", "管理", "管理后台", "管理後台", "Quản trị"],
        ["shopAdmin.notFound"] = ["This online store does not exist.", "Esta tienda en línea no existe.", "Cette boutique en ligne n’existe pas.", "Questo negozio online non esiste.", "Esta loja virtual não existe.", "존재하지 않는 쇼핑몰입니다.", "このオンラインショップは存在しません。", "该网上商城不存在。", "此網路商店不存在。", "Cửa hàng trực tuyến này không tồn tại."],
        ["shopAdmin.headingSuffix"] = ["admin", "administración", "administration", "amministrazione", "administração", "어드민", "管理", "管理", "管理", "quản trị"],
        ["shopAdmin.signInHelp"] = ["Sign in with your CodeMaru account to manage this store.", "Inicia sesión con tu cuenta de CodeMaru para gestionar esta tienda.", "Connectez-vous avec votre compte CodeMaru pour gérer cette boutique.", "Accedi con il tuo account CodeMaru per gestire il negozio.", "Entre com sua conta CodeMaru para gerenciar esta loja.", "CodeMaru 계정으로 로그인하면 쇼핑몰을 관리할 수 있습니다.", "CodeMaruアカウントでログインするとショップを管理できます。", "使用 CodeMaru 账户登录即可管理商城。", "使用 CodeMaru 帳戶登入即可管理商店。", "Đăng nhập bằng tài khoản CodeMaru để quản lý cửa hàng."],
        ["shopAdmin.signInWithCodeMaru"] = ["Sign in with CodeMaru", "Iniciar sesión con CodeMaru", "Se connecter avec CodeMaru", "Accedi con CodeMaru", "Entrar com CodeMaru", "CodeMaru 계정으로 로그인", "CodeMaruでログイン", "使用 CodeMaru 登录", "使用 CodeMaru 登入", "Đăng nhập bằng CodeMaru"],
        ["shopAdmin.currentAccount"] = ["Current account", "Cuenta actual", "Compte actuel", "Account attuale", "Conta atual", "현재 계정", "現在のアカウント", "当前账户", "目前帳戶", "Tài khoản hiện tại"],
        ["shopAdmin.legacyPassword"] = ["Existing admin password", "Contraseña de administrador actual", "Mot de passe administrateur actuel", "Password amministratore esistente", "Senha atual de administrador", "기존 어드민 비밀번호", "既存の管理パスワード", "原管理员密码", "現有管理員密碼", "Mật khẩu quản trị hiện tại"],
        ["shopAdmin.linkAccount"] = ["Link to current account", "Vincular a la cuenta actual", "Associer au compte actuel", "Collega all’account attuale", "Vincular à conta atual", "현재 계정에 연결", "現在のアカウントに連携", "关联到当前账户", "連結至目前帳戶", "Liên kết với tài khoản hiện tại"],
        ["shopAdmin.manageSuffix"] = ["management", "gestión", "gestion", "gestione", "gerenciamento", "관리", "管理", "管理", "管理", "quản lý"],
        ["shopAdmin.viewShop"] = ["View store", "Ver tienda", "Voir la boutique", "Visualizza negozio", "Ver loja", "쇼핑몰 보기", "ショップを見る", "查看商城", "查看商店", "Xem cửa hàng"],
        ["shopAdmin.productsTab"] = ["Products", "Productos", "Produits", "Prodotti", "Produtos", "상품 관리", "商品管理", "商品管理", "商品管理", "Quản lý sản phẩm"],
        ["shopAdmin.ordersTab"] = ["Orders", "Pedidos", "Commandes", "Ordini", "Pedidos", "주문 관리", "注文管理", "订单管理", "訂單管理", "Quản lý đơn hàng"],
        ["shopAdmin.paymentTab"] = ["Payment settings", "Configuración de pagos", "Paramètres de paiement", "Impostazioni di pagamento", "Configurações de pagamento", "결제 설정", "決済設定", "支付设置", "付款設定", "Cài đặt thanh toán"],
        ["shopAdmin.settingsTab"] = ["Store settings", "Configuración de la tienda", "Paramètres de la boutique", "Impostazioni negozio", "Configurações da loja", "쇼핑몰 설정", "ショップ設定", "商城设置", "商店設定", "Cài đặt cửa hàng"],

        ["superAdmin.pageTitle"] = ["Super admin", "Superadministración", "Super administration", "Super amministrazione", "Superadministração", "슈퍼어드민", "スーパー管理", "超级管理员", "超級管理員", "Quản trị cấp cao"],
        ["superAdmin.heading"] = ["Platform administrator", "Administrador de la plataforma", "Administrateur de la plateforme", "Amministratore della piattaforma", "Administrador da plataforma", "플랫폼 관리자", "プラットフォーム管理者", "平台管理员", "平台管理員", "Quản trị nền tảng"],
        ["superAdmin.manageShops"] = ["Manage stores", "Gestionar tiendas", "Gérer les boutiques", "Gestisci negozi", "Gerenciar lojas", "샵 관리", "ショップ管理", "商城管理", "商店管理", "Quản lý cửa hàng"],
        ["superAdmin.createShop"] = ["Create store", "Crear tienda", "Créer une boutique", "Crea negozio", "Criar loja", "새 샵 생성", "ショップを作成", "创建商城", "建立商店", "Tạo cửa hàng"],
        ["superAdmin.createHeading"] = ["Create a new online store", "Crear una nueva tienda en línea", "Créer une nouvelle boutique en ligne", "Crea un nuovo negozio online", "Criar uma nova loja virtual", "새 쇼핑몰 생성", "新しいオンラインショップを作成", "创建新商城", "建立新網路商店", "Tạo cửa hàng trực tuyến mới"],
        ["superAdmin.slug"] = ["Slug", "Slug", "Slug", "Slug", "Slug", "슬러그", "スラッグ", "网址标识", "網址代稱", "Slug"],
        ["superAdmin.slugHelp"] = ["Use lowercase letters, numbers, and hyphens only. Examples: my-shop, store123", "Usa solo letras minúsculas, números y guiones. Ejemplos: my-shop, store123", "Utilisez uniquement des minuscules, des chiffres et des tirets. Exemples : my-shop, store123", "Usa solo lettere minuscole, numeri e trattini. Esempi: my-shop, store123", "Use apenas letras minúsculas, números e hífens. Exemplos: my-shop, store123", "소문자 영숫자와 하이픈만 사용. 예: my-shop, store123", "小文字の英数字とハイフンのみ使用できます。例: my-shop, store123", "只能使用小写字母、数字和连字符。例如：my-shop、store123", "只能使用小寫英文字母、數字與連字號。例如：my-shop、store123", "Chỉ dùng chữ thường, số và dấu gạch nối. Ví dụ: my-shop, store123"],
        ["superAdmin.adminPassword"] = ["Admin password", "Contraseña de administrador", "Mot de passe administrateur", "Password amministratore", "Senha de administrador", "어드민 비밀번호", "管理パスワード", "管理员密码", "管理員密碼", "Mật khẩu quản trị"],
        ["superAdmin.noShops"] = ["No stores are registered. Create a new store to get started.", "No hay tiendas registradas. Crea una nueva para comenzar.", "Aucune boutique n’est enregistrée. Créez-en une pour commencer.", "Non ci sono negozi registrati. Creane uno per iniziare.", "Nenhuma loja foi cadastrada. Crie uma nova para começar.", "등록된 쇼핑몰이 없습니다. 새 샵을 생성해 보세요.", "登録済みのショップはありません。新しいショップを作成してください。", "暂无已注册的商城。请创建一个新商城。", "尚無已登錄的商店。請建立新商店。", "Chưa có cửa hàng nào. Hãy tạo cửa hàng mới."],
        ["superAdmin.invalidPasswordLength"] = ["The password is incorrect. ({0} characters entered)", "La contraseña es incorrecta. ({0} caracteres introducidos)", "Le mot de passe est incorrect. ({0} caractères saisis)", "La password non è corretta. ({0} caratteri inseriti)", "A senha está incorreta. ({0} caracteres digitados)", "비밀번호가 올바르지 않습니다. (입력: {0}자)", "パスワードが正しくありません。（入力: {0}文字）", "密码不正确。（已输入 {0} 个字符）", "密碼不正確。（已輸入 {0} 個字元）", "Mật khẩu không đúng. (Đã nhập {0} ký tự)"],
        ["superAdmin.invalidSlug"] = ["The slug may contain only lowercase letters, numbers, and hyphens.", "El slug solo puede contener letras minúsculas, números y guiones.", "Le slug ne peut contenir que des minuscules, des chiffres et des tirets.", "Lo slug può contenere solo lettere minuscole, numeri e trattini.", "O slug pode conter apenas letras minúsculas, números e hífens.", "슬러그는 소문자 영숫자와 하이픈만 사용 가능합니다.", "スラッグには小文字の英数字とハイフンのみ使用できます。", "网址标识只能包含小写字母、数字和连字符。", "網址代稱只能包含小寫英文字母、數字與連字號。", "Slug chỉ được chứa chữ thường, số và dấu gạch nối."],
        ["superAdmin.slugExists"] = ["This slug already exists.", "Este slug ya existe.", "Ce slug existe déjà.", "Questo slug esiste già.", "Este slug já existe.", "이미 존재하는 슬러그입니다.", "このスラッグは既に存在します。", "该网址标识已存在。", "此網址代稱已存在。", "Slug này đã tồn tại."],
        ["superAdmin.passwordRequired"] = ["Enter an admin password.", "Introduce una contraseña de administrador.", "Saisissez un mot de passe administrateur.", "Inserisci una password amministratore.", "Digite uma senha de administrador.", "어드민 비밀번호를 입력해 주세요.", "管理パスワードを入力してください。", "请输入管理员密码。", "請輸入管理員密碼。", "Hãy nhập mật khẩu quản trị."],
        ["superAdmin.passwordMinLength"] = ["The admin password must be at least 8 characters.", "La contraseña de administrador debe tener al menos 8 caracteres.", "Le mot de passe administrateur doit comporter au moins 8 caractères.", "La password amministratore deve contenere almeno 8 caratteri.", "A senha de administrador deve ter pelo menos 8 caracteres.", "어드민 비밀번호는 8자 이상이어야 합니다.", "管理パスワードは8文字以上必要です。", "管理员密码至少需要 8 个字符。", "管理員密碼至少需要 8 個字元。", "Mật khẩu quản trị phải có ít nhất 8 ký tự."],

        ["orders.title"] = ["Orders", "Pedidos", "Commandes", "Ordini", "Pedidos", "주문 목록", "注文一覧", "订单列表", "訂單列表", "Danh sách đơn hàng"],
        ["orders.empty"] = ["There are no orders yet.", "Aún no hay pedidos.", "Il n’y a pas encore de commandes.", "Non ci sono ancora ordini.", "Ainda não há pedidos.", "아직 주문이 없습니다.", "まだ注文はありません。", "暂无订单。", "尚無訂單。", "Chưa có đơn hàng nào."],
        ["orders.number"] = ["Order number", "N.º de pedido", "N° de commande", "Numero ordine", "Número do pedido", "주문번호", "注文番号", "订单编号", "訂單編號", "Mã đơn hàng"],
        ["orders.customer"] = ["Customer", "Cliente", "Client", "Cliente", "Cliente", "고객명", "顧客名", "客户姓名", "客戶姓名", "Khách hàng"],
        ["orders.total"] = ["Total", "Total", "Total", "Totale", "Total", "합계", "合計", "合计", "合計", "Tổng cộng"],
        ["orders.dateTime"] = ["Date and time", "Fecha y hora", "Date et heure", "Data e ora", "Data e hora", "일시", "日時", "日期和时间", "日期與時間", "Ngày giờ"],
        ["orders.transactionId"] = ["Transaction ID", "ID de transacción", "ID de transaction", "ID transazione", "ID da transação", "거래 ID", "取引ID", "交易 ID", "交易 ID", "Mã giao dịch"],
        ["orders.statusPaid"] = ["Paid", "Pagado", "Payée", "Pagato", "Pago", "결제 완료", "支払済み", "已支付", "已付款", "Đã thanh toán"],
        ["orders.statusPending"] = ["Pending", "Pendiente", "En attente", "In attesa", "Pendente", "대기 중", "保留中", "待处理", "待處理", "Đang chờ"],
        ["orders.statusCancelled"] = ["Cancelled", "Cancelado", "Annulée", "Annullato", "Cancelado", "취소됨", "キャンセル済み", "已取消", "已取消", "Đã hủy"],

        ["paymentSettings.title"] = ["Payment settings", "Configuración de pagos", "Paramètres de paiement", "Impostazioni di pagamento", "Configurações de pagamento", "결제 설정", "決済設定", "支付设置", "付款設定", "Cài đặt thanh toán"],
        ["paymentSettings.keyGuideTitle"] = ["How to issue Toss Payments API keys:", "Cómo obtener claves de API de Toss Payments:", "Comment obtenir les clés API Toss Payments :", "Come ottenere le chiavi API di Toss Payments:", "Como emitir chaves de API do Toss Payments:", "토스페이먼츠 API 키 발급 방법:", "Toss Payments APIキーの発行方法:", "如何获取 Toss Payments API 密钥：", "如何取得 Toss Payments API 金鑰：", "Cách cấp khóa API Toss Payments:"],
        ["paymentSettings.developerConsole"] = ["Toss Payments developer console", "Consola para desarrolladores de Toss Payments", "Console développeur Toss Payments", "Console sviluppatori Toss Payments", "Console de desenvolvedores Toss Payments", "토스페이먼츠 개발자 콘솔", "Toss Payments開発者コンソール", "Toss Payments 开发者控制台", "Toss Payments 開發者主控台", "Bảng điều khiển nhà phát triển Toss Payments"],
        ["paymentSettings.openConsole"] = ["Open it", "Ábrela", "Ouvrez-la", "Aprila", "Acesse-o", "접속", "にアクセス", "并打开", "並開啟", "Truy cập"],
        ["paymentSettings.keyGuideStep2"] = ["After signing up, open “My Applications” and issue API keys.", "Tras registrarte, abre «Mis aplicaciones» y genera las claves de API.", "Après inscription, ouvrez « Mes applications » et générez les clés API.", "Dopo la registrazione, apri “Le mie applicazioni” e genera le chiavi API.", "Após o cadastro, abra “Meus aplicativos” e gere as chaves de API.", "가입 후 ‘내 애플리케이션’ → API 키 발급", "登録後、「マイアプリケーション」からAPIキーを発行します。", "注册后，打开“我的应用程序”并获取 API 密钥。", "註冊後，開啟「我的應用程式」並取得 API 金鑰。", "Sau khi đăng ký, mở “Ứng dụng của tôi” và cấp khóa API."],
        ["paymentSettings.testKeys"] = ["Test keys", "Claves de prueba", "Clés de test", "Chiavi di test", "Chaves de teste", "테스트 키", "テストキー", "测试密钥", "測試金鑰", "Khóa thử nghiệm"],
        ["paymentSettings.liveKeyStep"] = ["Live keys are issued after Toss approval.", "Las claves de producción se emiten tras la aprobación de Toss.", "Les clés de production sont émises après validation par Toss.", "Le chiavi di produzione vengono emesse dopo l’approvazione di Toss.", "As chaves de produção são emitidas após a aprovação da Toss.", "운영 키: 토스 심사 후 발급", "本番キーはTossの審査後に発行されます。", "正式密钥将在 Toss 审核后发放。", "正式金鑰將在 Toss 審核後發放。", "Khóa thật được cấp sau khi Toss phê duyệt."],
        ["paymentSettings.settlementNote"] = ["※ Payments are settled directly to your Toss account.", "※ Los pagos se liquidan directamente en tu cuenta de Toss.", "※ Les paiements sont versés directement sur votre compte Toss.", "※ I pagamenti vengono accreditati direttamente sul tuo account Toss.", "※ Os pagamentos são liquidados diretamente na sua conta Toss.", "※ 결제는 귀하의 토스 계정으로 직접 정산됩니다.", "※ 売上はお客様のTossアカウントへ直接精算されます。", "※ 款项将直接结算到您的 Toss 账户。", "※ 款項將直接結算至您的 Toss 帳戶。", "※ Khoản thanh toán được đối soát trực tiếp vào tài khoản Toss của bạn."],
        ["paymentSettings.enable"] = ["Enable payments", "Activar pagos", "Activer les paiements", "Abilita pagamenti", "Ativar pagamentos", "결제 활성화", "決済を有効化", "启用支付", "啟用付款", "Bật thanh toán"],
        ["paymentSettings.testMode"] = ["Test mode", "Modo de prueba", "Mode test", "Modalità test", "Modo de teste", "테스트 모드", "テストモード", "测试模式", "測試模式", "Chế độ thử nghiệm"],
        ["paymentSettings.clientKey"] = ["Client key", "Clave de cliente", "Clé client", "Chiave client", "Chave do cliente", "클라이언트 키", "クライアントキー", "客户端密钥", "用戶端金鑰", "Khóa máy khách"],
        ["paymentSettings.clientKeyHelp"] = ["Used to load the payment widget in the browser.", "Se usa para cargar el widget de pago en el navegador.", "Utilisée pour charger le widget de paiement dans le navigateur.", "Usata per caricare il widget di pagamento nel browser.", "Usada para carregar o widget de pagamento no navegador.", "브라우저에서 결제 위젯을 로드할 때 사용합니다.", "ブラウザーで決済ウィジェットを読み込む際に使用します。", "用于在浏览器中加载支付组件。", "用於在瀏覽器中載入付款元件。", "Dùng để tải tiện ích thanh toán trong trình duyệt."],
        ["paymentSettings.secretKey"] = ["Secret key", "Clave secreta", "Clé secrète", "Chiave segreta", "Chave secreta", "시크릿 키", "シークレットキー", "密钥", "祕密金鑰", "Khóa bí mật"],
        ["paymentSettings.secretKeyHelp"] = ["Used by the server to approve payments. It is stored encrypted.", "El servidor la usa para aprobar pagos. Se almacena cifrada.", "Utilisée par le serveur pour approuver les paiements. Elle est stockée chiffrée.", "Usata dal server per approvare i pagamenti. Viene salvata crittografata.", "Usada pelo servidor para aprovar pagamentos. É armazenada de forma criptografada.", "서버에서 결제 승인 시 사용합니다. 암호화되어 저장됩니다.", "サーバーで決済を承認する際に使用し、暗号化して保存されます。", "服务器用于确认支付，并加密保存。", "伺服器用於核准付款，並加密儲存。", "Máy chủ dùng để phê duyệt thanh toán và được lưu dưới dạng mã hóa."],
        ["paymentSettings.newKeyEntered"] = ["A new key was entered. Saving will replace the existing key.", "Se ha introducido una clave nueva. Al guardar se sustituirá la actual.", "Une nouvelle clé a été saisie. L’enregistrement remplacera la clé actuelle.", "È stata inserita una nuova chiave. Il salvataggio sostituirà quella esistente.", "Uma nova chave foi inserida. Ao salvar, ela substituirá a chave atual.", "새 키를 입력했습니다. 저장 시 기존 키를 덮어씁니다.", "新しいキーが入力されました。保存すると既存のキーを上書きします。", "已输入新密钥，保存后将覆盖现有密钥。", "已輸入新金鑰，儲存後將覆蓋現有金鑰。", "Đã nhập khóa mới. Khi lưu, khóa hiện tại sẽ bị thay thế."],
        ["paymentSettings.existingKey"] = ["A saved key already exists. Enter a new key to change it.", "Ya hay una clave guardada. Introduce una nueva para cambiarla.", "Une clé est déjà enregistrée. Saisissez-en une nouvelle pour la modifier.", "Esiste già una chiave salvata. Inseriscine una nuova per cambiarla.", "Já existe uma chave salva. Digite uma nova para alterá-la.", "기존 저장된 키가 있습니다. 변경하려면 새 키를 입력하세요.", "保存済みのキーがあります。変更する場合は新しいキーを入力してください。", "已有保存的密钥。如需更改，请输入新密钥。", "已有儲存的金鑰。如需變更，請輸入新金鑰。", "Đã có khóa được lưu. Hãy nhập khóa mới để thay đổi."],
        ["paymentSettings.save"] = ["Save payment settings", "Guardar configuración de pagos", "Enregistrer les paramètres de paiement", "Salva impostazioni di pagamento", "Salvar configurações de pagamento", "설정 저장", "決済設定を保存", "保存支付设置", "儲存付款設定", "Lưu cài đặt thanh toán"],
        ["paymentSettings.saved"] = ["Payment settings were saved.", "La configuración de pagos se ha guardado.", "Les paramètres de paiement ont été enregistrés.", "Le impostazioni di pagamento sono state salvate.", "As configurações de pagamento foram salvas.", "결제 설정이 저장되었습니다.", "決済設定を保存しました。", "支付设置已保存。", "付款設定已儲存。", "Đã lưu cài đặt thanh toán."]
    };

    private static readonly Dictionary<string, string[]> Products = new(StringComparer.OrdinalIgnoreCase)
    {
        ["products.title"] = ["Products", "Productos", "Produits", "Prodotti", "Produtos", "상품 목록", "商品一覧", "商品列表", "商品列表", "Danh sách sản phẩm"],
        ["products.add"] = ["Add product", "Añadir producto", "Ajouter un produit", "Aggiungi prodotto", "Adicionar produto", "상품 추가", "商品を追加", "添加商品", "新增商品", "Thêm sản phẩm"],
        ["products.editHeading"] = ["Edit product", "Editar producto", "Modifier le produit", "Modifica prodotto", "Editar produto", "상품 수정", "商品を編集", "编辑商品", "編輯商品", "Sửa sản phẩm"],
        ["products.newHeading"] = ["New product", "Nuevo producto", "Nouveau produit", "Nuovo prodotto", "Novo produto", "새 상품", "新しい商品", "新商品", "新商品", "Sản phẩm mới"],
        ["products.name"] = ["Product name", "Nombre del producto", "Nom du produit", "Nome prodotto", "Nome do produto", "상품명", "商品名", "商品名称", "商品名稱", "Tên sản phẩm"],
        ["products.price"] = ["Price", "Precio", "Prix", "Prezzo", "Preço", "가격", "価格", "价格", "價格", "Giá"],
        ["products.stock"] = ["Stock", "Existencias", "Stock", "Scorte", "Estoque", "재고", "在庫", "库存", "庫存", "Tồn kho"],
        ["products.unlimited"] = ["Unlimited", "Ilimitado", "Illimité", "Illimitato", "Ilimitado", "무한", "無制限", "不限", "不限", "Không giới hạn"],
        ["products.category"] = ["Category", "Categoría", "Catégorie", "Categoria", "Categoria", "카테고리", "カテゴリー", "分类", "分類", "Danh mục"],
        ["products.sortOrder"] = ["Display order", "Orden de visualización", "Ordre d’affichage", "Ordine di visualizzazione", "Ordem de exibição", "노출 순서", "表示順", "显示顺序", "顯示順序", "Thứ tự hiển thị"],
        ["products.lowerFirst"] = ["lower numbers appear first", "los números menores aparecen primero", "les nombres les plus bas apparaissent en premier", "i numeri più bassi vengono mostrati prima", "números menores aparecem primeiro", "낮을수록 먼저", "小さい数字ほど先", "数字越小越靠前", "數字越小越靠前", "số nhỏ hơn hiển thị trước"],
        ["products.featured"] = ["Featured product", "Producto destacado", "Produit vedette", "Prodotto in evidenza", "Produto em destaque", "추천 상품", "おすすめ商品", "推荐商品", "推薦商品", "Sản phẩm nổi bật"],
        ["products.video"] = ["Video", "Vídeo", "Vidéo", "Video", "Vídeo", "동영상", "動画", "视频", "影片", "Video"],
        ["products.videoUploadHelp"] = ["Upload an MP4/WEBM file (maximum 200 MB)", "Sube un archivo MP4/WEBM (máximo 200 MB)", "Importez un fichier MP4/WEBM (200 Mo maximum)", "Carica un file MP4/WEBM (massimo 200 MB)", "Envie um arquivo MP4/WEBM (máximo de 200 MB)", "MP4/WEBM 파일 업로드 (최대 200MB)", "MP4/WEBMファイルをアップロード（最大200MB）", "上传 MP4/WEBM 文件（最大 200 MB）", "上傳 MP4/WEBM 檔案（最大 200 MB）", "Tải tệp MP4/WEBM lên (tối đa 200 MB)"],
        ["products.youtubePlaceholder"] = ["Or enter a YouTube URL: https://youtu.be/...", "O introduce una URL de YouTube: https://youtu.be/...", "Ou saisissez une URL YouTube : https://youtu.be/...", "Oppure inserisci un URL YouTube: https://youtu.be/...", "Ou insira uma URL do YouTube: https://youtu.be/...", "또는 유튜브 URL: https://youtu.be/...", "またはYouTube URL: https://youtu.be/...", "或输入 YouTube 网址：https://youtu.be/...", "或輸入 YouTube 網址：https://youtu.be/...", "Hoặc nhập URL YouTube: https://youtu.be/..."],
        ["products.detailImages"] = ["Detail images", "Imágenes de detalle", "Images détaillées", "Immagini di dettaglio", "Imagens de detalhes", "상세 이미지", "詳細画像", "详情图片", "詳細圖片", "Hình ảnh chi tiết"],
        ["products.multipleAllowed"] = ["multiple images allowed", "se permiten varias imágenes", "plusieurs images autorisées", "sono consentite più immagini", "várias imagens permitidas", "여러 장 업로드 가능", "複数枚アップロード可能", "可上传多张", "可上傳多張", "có thể tải nhiều ảnh"],
        ["products.detailImageAlt"] = ["Product detail image", "Imagen de detalle del producto", "Image détaillée du produit", "Immagine di dettaglio del prodotto", "Imagem de detalhes do produto", "상품 상세 이미지", "商品詳細画像", "商品详情图片", "商品詳細圖片", "Hình ảnh chi tiết sản phẩm"],
        ["products.removeDetailImage"] = ["Remove detail image", "Quitar imagen de detalle", "Retirer l’image détaillée", "Rimuovi immagine di dettaglio", "Remover imagem de detalhes", "상세 이미지 제거", "詳細画像を削除", "移除详情图片", "移除詳細圖片", "Gỡ hình ảnh chi tiết"],
        ["products.detailText"] = ["Detailed description", "Descripción detallada", "Description détaillée", "Descrizione dettagliata", "Descrição detalhada", "상세 텍스트", "詳細説明", "详细说明", "詳細說明", "Mô tả chi tiết"],
        ["products.detailTextHint"] = ["optional · Markdown or plain text", "opcional · Markdown o texto sin formato", "facultatif · Markdown ou texte brut", "facoltativo · Markdown o testo normale", "opcional · Markdown ou texto simples", "선택 · 마크다운 또는 일반 텍스트", "任意・Markdownまたはプレーンテキスト", "可选 · Markdown 或纯文本", "選填 · Markdown 或純文字", "tùy chọn · Markdown hoặc văn bản thuần"],
        ["products.itemExample"] = ["Item", "Elemento", "Élément", "Voce", "Item", "항목", "項目", "项目", "項目", "Mục"],
        ["products.listSyntax"] = ["list", "lista", "liste", "elenco", "lista", "목록", "リスト", "列表", "清單", "danh sách"],
        ["products.boldExample"] = ["bold", "negrita", "gras", "grassetto", "negrito", "굵게", "太字", "粗体", "粗體", "in đậm"],
        ["products.subheadingExample"] = ["Subheading", "Subtítulo", "Sous-titre", "Sottotitolo", "Subtítulo", "소제목", "小見出し", "小标题", "小標題", "Tiêu đề phụ"],
        ["products.blankLineHelp"] = ["blank line = new paragraph", "línea en blanco = nuevo párrafo", "ligne vide = nouveau paragraphe", "riga vuota = nuovo paragrafo", "linha em branco = novo parágrafo", "빈 줄 = 문단 나누기", "空行 = 段落区切り", "空行 = 新段落", "空白行 = 新段落", "dòng trống = đoạn mới"],
        ["products.imageOnlyHelp"] = ["Leave blank when using images only", "Déjalo en blanco si solo usas imágenes", "Laissez vide si vous utilisez uniquement des images", "Lascia vuoto se usi solo immagini", "Deixe em branco se usar apenas imagens", "이미지만 올릴 경우 비워도 됩니다", "画像のみの場合は空欄にできます", "仅使用图片时可留空", "僅使用圖片時可留空", "Có thể để trống nếu chỉ dùng hình ảnh"],
        ["products.detailPlaceholder"] = ["## Product features\n- Describe the first feature\n- Emphasize **important details**\n\n## Notes\n- Add storage or usage guidance", "## Características del producto\n- Describe la primera característica\n- Destaca los **detalles importantes**\n\n## Notas\n- Añade instrucciones de conservación o uso", "## Caractéristiques du produit\n- Décrivez la première caractéristique\n- Mettez en valeur les **détails importants**\n\n## Remarques\n- Ajoutez des conseils de conservation ou d’utilisation", "## Caratteristiche del prodotto\n- Descrivi la prima caratteristica\n- Evidenzia i **dettagli importanti**\n\n## Note\n- Aggiungi indicazioni per conservazione o utilizzo", "## Características do produto\n- Descreva a primeira característica\n- Destaque os **detalhes importantes**\n\n## Observações\n- Adicione orientações de armazenamento ou uso", "## 상품 특징\n- 첫 번째 특징을 입력하세요\n- **중요한 내용**을 강조하세요\n\n## 주의사항\n- 보관 또는 사용 안내를 입력하세요", "## 商品の特徴\n- 1つ目の特徴を入力してください\n- **重要な内容**を強調します\n\n## 注意事項\n- 保管・使用方法を入力してください", "## 商品特点\n- 填写第一项特点\n- 突出显示**重要信息**\n\n## 注意事项\n- 填写储存或使用说明", "## 商品特色\n- 填寫第一項特色\n- 強調**重要資訊**\n\n## 注意事項\n- 填寫保存或使用說明", "## Đặc điểm sản phẩm\n- Mô tả đặc điểm đầu tiên\n- Nhấn mạnh **thông tin quan trọng**\n\n## Lưu ý\n- Thêm hướng dẫn bảo quản hoặc sử dụng"],
        ["products.image"] = ["Product image", "Imagen del producto", "Image du produit", "Immagine prodotto", "Imagem do produto", "상품 이미지", "商品画像", "商品图片", "商品圖片", "Hình ảnh sản phẩm"],
        ["products.imageUploadHelp"] = ["JPG/PNG/WEBP, maximum 5 MB", "JPG/PNG/WEBP, máximo 5 MB", "JPG/PNG/WEBP, 5 Mo maximum", "JPG/PNG/WEBP, massimo 5 MB", "JPG/PNG/WEBP, máximo de 5 MB", "JPG/PNG/WEBP, 최대 5MB", "JPG/PNG/WEBP、最大5MB", "JPG/PNG/WEBP，最大 5 MB", "JPG/PNG/WEBP，最大 5 MB", "JPG/PNG/WEBP, tối đa 5 MB"],
        ["products.imageUrlPlaceholder"] = ["Or enter an image URL", "O introduce una URL de imagen", "Ou saisissez une URL d’image", "Oppure inserisci un URL immagine", "Ou insira uma URL de imagem", "또는 이미지 URL 직접 입력", "または画像URLを入力", "或输入图片网址", "或輸入圖片網址", "Hoặc nhập URL hình ảnh"],
        ["products.removeImage"] = ["Remove image", "Quitar imagen", "Retirer l’image", "Rimuovi immagine", "Remover imagem", "이미지 제거", "画像を削除", "移除图片", "移除圖片", "Gỡ hình ảnh"],
        ["products.enableSales"] = ["Enable sales", "Activar venta", "Activer la vente", "Abilita vendita", "Ativar vendas", "판매 활성화", "販売を有効化", "启用销售", "啟用銷售", "Bật bán hàng"],
        ["products.empty"] = ["No products are registered.", "No hay productos registrados.", "Aucun produit n’est enregistré.", "Non ci sono prodotti registrati.", "Nenhum produto foi cadastrado.", "등록된 상품이 없습니다.", "登録済みの商品はありません。", "暂无已注册商品。", "尚無已登錄商品。", "Chưa có sản phẩm nào."],
        ["products.order"] = ["Order", "Orden", "Ordre", "Ordine", "Ordem", "순서", "順序", "顺序", "順序", "Thứ tự"],
        ["products.featuredShort"] = ["Featured", "Destacado", "Vedette", "In evidenza", "Destaque", "추천", "おすすめ", "推荐", "推薦", "Nổi bật"],
        ["products.unfeature"] = ["Remove from featured", "Quitar de destacados", "Retirer des produits vedettes", "Rimuovi dai prodotti in evidenza", "Remover dos destaques", "추천 해제", "おすすめを解除", "取消推荐", "取消推薦", "Bỏ nổi bật"],
        ["products.feature"] = ["Mark as featured", "Marcar como destacado", "Mettre en vedette", "Metti in evidenza", "Marcar como destaque", "추천 설정", "おすすめに設定", "设为推荐", "設為推薦", "Đặt làm nổi bật"],
        ["products.onSale"] = ["On sale", "En venta", "En vente", "In vendita", "À venda", "판매중", "販売中", "销售中", "銷售中", "Đang bán"],
        ["products.hidden"] = ["Hidden", "Oculto", "Masqué", "Nascosto", "Oculto", "숨김", "非表示", "已隐藏", "已隱藏", "Đã ẩn"],
        ["products.featuredTableHelp"] = ["⭐ Highlighted rows are featured products. Lower order numbers appear first.", "⭐ Las filas resaltadas son productos destacados. Los números de orden menores aparecen primero.", "⭐ Les lignes surlignées sont les produits vedettes. Les numéros d’ordre les plus bas apparaissent en premier.", "⭐ Le righe evidenziate sono prodotti in primo piano. I numeri d’ordine più bassi appaiono prima.", "⭐ As linhas destacadas são produtos em destaque. Números de ordem menores aparecem primeiro.", "⭐ 강조 표시된 행이 추천 상품입니다. 순서 숫자가 낮을수록 먼저 노출됩니다.", "⭐ 強調表示された行がおすすめ商品です。順序の数字が小さいほど先に表示されます。", "⭐ 高亮行是推荐商品。顺序数字越小越靠前。", "⭐ 反白列為推薦商品。順序數字越小越靠前。", "⭐ Hàng được tô nổi là sản phẩm nổi bật. Số thứ tự nhỏ hơn sẽ hiển thị trước."],
        ["products.imageTooLarge"] = ["The image must be 5 MB or smaller.", "La imagen debe tener 5 MB o menos.", "L’image doit faire 5 Mo ou moins.", "L’immagine deve essere di massimo 5 MB.", "A imagem deve ter no máximo 5 MB.", "파일 크기는 5MB 이하여야 합니다.", "画像は5MB以下にしてください。", "图片大小不得超过 5 MB。", "圖片大小不得超過 5 MB。", "Hình ảnh phải có dung lượng tối đa 5 MB."],
        ["products.invalidImageType"] = ["Only JPG, PNG, WEBP, and GIF files are allowed.", "Solo se permiten archivos JPG, PNG, WEBP y GIF.", "Seuls les fichiers JPG, PNG, WEBP et GIF sont autorisés.", "Sono consentiti solo file JPG, PNG, WEBP e GIF.", "Apenas arquivos JPG, PNG, WEBP e GIF são permitidos.", "JPG, PNG, WEBP, GIF 파일만 가능합니다.", "JPG、PNG、WEBP、GIFファイルのみ使用できます。", "仅支持 JPG、PNG、WEBP 和 GIF 文件。", "僅支援 JPG、PNG、WEBP 與 GIF 檔案。", "Chỉ chấp nhận tệp JPG, PNG, WEBP và GIF."],
        ["products.invalidVideoType"] = ["Only MP4, WEBM, and OGG files are allowed.", "Solo se permiten archivos MP4, WEBM y OGG.", "Seuls les fichiers MP4, WEBM et OGG sont autorisés.", "Sono consentiti solo file MP4, WEBM e OGG.", "Apenas arquivos MP4, WEBM e OGG são permitidos.", "MP4/WEBM/OGG 파일만 가능합니다.", "MP4、WEBM、OGGファイルのみ使用できます。", "仅支持 MP4、WEBM 和 OGG 文件。", "僅支援 MP4、WEBM 與 OGG 檔案。", "Chỉ chấp nhận tệp MP4, WEBM và OGG."],
        ["products.videoTooLarge"] = ["The video must be 200 MB or smaller.", "El vídeo debe tener 200 MB o menos.", "La vidéo doit faire 200 Mo ou moins.", "Il video deve essere di massimo 200 MB.", "O vídeo deve ter no máximo 200 MB.", "200MB 이하 파일만 업로드 가능합니다.", "動画は200MB以下にしてください。", "视频大小不得超过 200 MB。", "影片大小不得超過 200 MB。", "Video phải có dung lượng tối đa 200 MB."]
    };

    private static readonly Dictionary<string, string[]> Settings = new(StringComparer.OrdinalIgnoreCase)
    {
        ["shopSettings.basicInfo"] = ["Store information", "Información de la tienda", "Informations de la boutique", "Informazioni negozio", "Informações da loja", "쇼핑몰 기본 정보", "ショップ基本情報", "商城基本信息", "商店基本資訊", "Thông tin cửa hàng"],
        ["shopSettings.descriptionLabel"] = ["Description (shown above the product list)", "Descripción (se muestra sobre la lista de productos)", "Description (affichée au-dessus de la liste des produits)", "Descrizione (mostrata sopra l’elenco prodotti)", "Descrição (exibida acima da lista de produtos)", "설명 (상품 목록 상단에 표시)", "説明（商品一覧の上部に表示）", "说明（显示在商品列表上方）", "說明（顯示於商品列表上方）", "Mô tả (hiển thị phía trên danh sách sản phẩm)"],
        ["shopSettings.enableShop"] = ["Keep the store active", "Mantener la tienda activa", "Maintenir la boutique active", "Mantieni il negozio attivo", "Manter a loja ativa", "쇼핑몰 운영 활성화", "ショップ運営を有効化", "启用商城运营", "啟用商店營運", "Bật hoạt động cửa hàng"],
        ["shopSettings.showPlatformHome"] = ["Show the ShopStore home button in the store", "Mostrar el botón de inicio de ShopStore en la tienda", "Afficher le bouton d’accueil ShopStore dans la boutique", "Mostra il pulsante Home di ShopStore nel negozio", "Mostrar o botão inicial da ShopStore na loja", "쇼핑몰 화면에 ShopStore 홈 버튼 표시", "ショップ画面にShopStoreホームボタンを表示", "在商城中显示 ShopStore 首页按钮", "在商店中顯示 ShopStore 首頁按鈕", "Hiển thị nút trang chủ ShopStore trong cửa hàng"],
        ["shopSettings.showPlatformHomeHelp"] = ["Lets customers go from this store to the main ShopStore page at https://shop.codemaru.co.kr/.", "Permite a los clientes ir de esta tienda a la página principal de ShopStore en https://shop.codemaru.co.kr/.", "Permet aux clients de passer de cette boutique à l’accueil ShopStore sur https://shop.codemaru.co.kr/.", "Consente ai clienti di passare da questo negozio alla pagina principale ShopStore su https://shop.codemaru.co.kr/.", "Permite que os clientes acessem a página principal da ShopStore em https://shop.codemaru.co.kr/.", "고객이 현재 쇼핑몰에서 https://shop.codemaru.co.kr/ 메인으로 이동할 수 있는 버튼입니다.", "このショップから https://shop.codemaru.co.kr/ のShopStoreトップへ移動できるボタンです。", "让顾客可从当前商城前往 https://shop.codemaru.co.kr/ 的 ShopStore 首页。", "讓顧客可從目前商店前往 https://shop.codemaru.co.kr/ 的 ShopStore 首頁。", "Cho phép khách hàng đi từ cửa hàng này đến trang chính ShopStore tại https://shop.codemaru.co.kr/."],
        ["shopSettings.heroSettings"] = ["Hero banner settings", "Configuración del banner principal", "Paramètres de la bannière principale", "Impostazioni banner principale", "Configurações do banner principal", "히어로 배너 설정", "ヒーローバナー設定", "主横幅设置", "主視覺橫幅設定", "Cài đặt biểu ngữ chính"],
        ["shopSettings.heroText"] = ["Main banner text", "Texto principal del banner", "Texte principal de la bannière", "Testo principale del banner", "Texto principal do banner", "배너 메인 문구", "バナーのメイン文", "横幅主文案", "橫幅主文案", "Nội dung chính biểu ngữ"],
        ["shopSettings.heroTextPlaceholder"] = ["Example: Fresh produce delivered directly to you", "Ejemplo: Productos frescos entregados directamente", "Exemple : Des produits frais livrés directement chez vous", "Esempio: Prodotti freschi consegnati direttamente a te", "Exemplo: Produtos frescos entregues diretamente a você", "예) 신선한 농산물을 직접 배송합니다", "例）新鮮な農産物を直接お届けします", "示例：新鲜农产品直送到家", "範例：新鮮農產品直接配送到府", "Ví dụ: Giao nông sản tươi trực tiếp đến bạn"],
        ["shopSettings.heroSubText"] = ["Banner subtext", "Texto secundario del banner", "Sous-texte de la bannière", "Testo secondario del banner", "Texto secundário do banner", "배너 서브 문구", "バナーのサブ文", "横幅副文案", "橫幅副文案", "Nội dung phụ biểu ngữ"],
        ["shopSettings.heroSubTextPlaceholder"] = ["Example: Harvested today · Nationwide delivery", "Ejemplo: Cosechado hoy · Envíos a todo el país", "Exemple : Récolté aujourd’hui · Livraison nationale", "Esempio: Raccolto oggi · Consegna nazionale", "Exemplo: Colhido hoje · Entrega nacional", "예) 당일 수확 · 전국 택배 가능", "例）当日収穫・全国配送対応", "示例：当日采收 · 全国配送", "範例：當日採收 · 全國配送", "Ví dụ: Thu hoạch trong ngày · Giao hàng toàn quốc"],
        ["shopSettings.bannerUrl"] = ["Banner background image URL", "URL de la imagen de fondo del banner", "URL de l’image d’arrière-plan de la bannière", "URL immagine di sfondo del banner", "URL da imagem de fundo do banner", "배너 배경 이미지 URL", "バナー背景画像URL", "横幅背景图片网址", "橫幅背景圖片網址", "URL hình nền biểu ngữ"],
        ["shopSettings.urlPlaceholder"] = ["https://... or /shop-img/{slug}/images/...", "https://... o /shop-img/{slug}/images/...", "https://... ou /shop-img/{slug}/images/...", "https://... oppure /shop-img/{slug}/images/...", "https://... ou /shop-img/{slug}/images/...", "https://... 또는 /shop-img/{slug}/images/...", "https://... または /shop-img/{slug}/images/...", "https://... 或 /shop-img/{slug}/images/...", "https://... 或 /shop-img/{slug}/images/...", "https://... hoặc /shop-img/{slug}/images/..."],
        ["shopSettings.defaultGradientHelp"] = ["Leave blank to use the default gradient background.", "Déjalo en blanco para usar el fondo degradado predeterminado.", "Laissez vide pour utiliser l’arrière-plan dégradé par défaut.", "Lascia vuoto per usare lo sfondo sfumato predefinito.", "Deixe em branco para usar o fundo em degradê padrão.", "비워두면 기본 그라데이션 배경이 사용됩니다.", "空欄の場合は既定のグラデーション背景を使用します。", "留空将使用默认渐变背景。", "留空將使用預設漸層背景。", "Để trống để dùng nền chuyển màu mặc định."],
        ["shopSettings.uploadBanner"] = ["Upload banner background image", "Subir imagen de fondo del banner", "Importer l’image d’arrière-plan de la bannière", "Carica immagine di sfondo del banner", "Enviar imagem de fundo do banner", "배너 배경 이미지 업로드", "バナー背景画像をアップロード", "上传横幅背景图片", "上傳橫幅背景圖片", "Tải hình nền biểu ngữ lên"],
        ["shopSettings.featuredCount"] = ["Number of featured products", "Número de productos destacados", "Nombre de produits vedettes", "Numero di prodotti in evidenza", "Número de produtos em destaque", "추천 상품 표시 개수", "おすすめ商品の表示数", "推荐商品数量", "推薦商品數量", "Số sản phẩm nổi bật"],
        ["shopSettings.itemCount"] = ["{0} items", "{0} elementos", "{0} articles", "{0} articoli", "{0} itens", "{0}개", "{0}件", "{0} 件", "{0} 件", "{0} mục"],
        ["shopSettings.logoImage"] = ["Logo image", "Imagen del logotipo", "Image du logo", "Immagine del logo", "Imagem do logotipo", "로고 이미지", "ロゴ画像", "标志图片", "標誌圖片", "Hình ảnh logo"],
        ["shopSettings.logoAlt"] = ["Store logo", "Logotipo de la tienda", "Logo de la boutique", "Logo del negozio", "Logotipo da loja", "쇼핑몰 로고", "ショップロゴ", "商城标志", "商店標誌", "Logo cửa hàng"],
        ["shopSettings.logoUrl"] = ["Logo image URL", "URL de la imagen del logotipo", "URL de l’image du logo", "URL immagine del logo", "URL da imagem do logotipo", "로고 이미지 URL", "ロゴ画像URL", "标志图片网址", "標誌圖片網址", "URL hình ảnh logo"],
        ["shopSettings.logoUrlPlaceholder"] = ["https://... or /shop-img/...", "https://... o /shop-img/...", "https://... ou /shop-img/...", "https://... oppure /shop-img/...", "https://... ou /shop-img/...", "https://... 또는 /shop-img/...", "https://... または /shop-img/...", "https://... 或 /shop-img/...", "https://... 或 /shop-img/...", "https://... hoặc /shop-img/..."],
        ["shopSettings.uploadLogo"] = ["Upload logo image", "Subir imagen del logotipo", "Importer l’image du logo", "Carica immagine del logo", "Enviar imagem do logotipo", "로고 이미지 업로드", "ロゴ画像をアップロード", "上传标志图片", "上傳標誌圖片", "Tải hình ảnh logo lên"],
        ["shopSettings.businessInfo"] = ["Business information (shown in footer)", "Información comercial (se muestra en el pie)", "Informations légales (affichées dans le pied de page)", "Informazioni aziendali (mostrate nel footer)", "Informações comerciais (exibidas no rodapé)", "사업자 정보 (푸터 표시)", "事業者情報（フッターに表示）", "商家信息（显示在页脚）", "商家資訊（顯示於頁尾）", "Thông tin doanh nghiệp (hiển thị ở chân trang)"],
        ["shopSettings.companyName"] = ["Company name", "Razón social", "Raison sociale", "Ragione sociale", "Razão social", "상호명", "商号", "公司名称", "商號", "Tên doanh nghiệp"],
        ["shopSettings.companyPlaceholder"] = ["Example: CodeMaru Store", "Ejemplo: Tienda CodeMaru", "Exemple : Boutique CodeMaru", "Esempio: Negozio CodeMaru", "Exemplo: Loja CodeMaru", "예) CodeMaru 스토어", "例）CodeMaruストア", "示例：CodeMaru 商店", "範例：CodeMaru 商店", "Ví dụ: Cửa hàng CodeMaru"],
        ["shopSettings.representative"] = ["Representative", "Representante", "Représentant", "Rappresentante", "Representante", "대표자명", "代表者名", "负责人", "負責人", "Người đại diện"],
        ["shopSettings.personPlaceholder"] = ["Example: Alex Kim", "Ejemplo: Alex Kim", "Exemple : Alex Kim", "Esempio: Alex Kim", "Exemplo: Alex Kim", "예) 홍길동", "例）山田太郎", "示例：张伟", "範例：王小明", "Ví dụ: Nguyễn An"],
        ["shopSettings.businessNumber"] = ["Business registration number", "Número de registro comercial", "Numéro d’immatriculation", "Numero di registrazione aziendale", "Número de registro empresarial", "사업자등록번호", "事業者登録番号", "营业执照编号", "商業登記號碼", "Mã số doanh nghiệp"],
        ["shopSettings.businessNumberPlaceholder"] = ["Example: 000-00-00000", "Ejemplo: 000-00-00000", "Exemple : 000-00-00000", "Esempio: 000-00-00000", "Exemplo: 000-00-00000", "예) 000-00-00000", "例）000-00-00000", "示例：000-00-00000", "範例：000-00-00000", "Ví dụ: 000-00-00000"],
        ["shopSettings.phonePlaceholder"] = ["Example: 010-0000-0000", "Ejemplo: 010-0000-0000", "Exemple : 010-0000-0000", "Esempio: 010-0000-0000", "Exemplo: 010-0000-0000", "예) 010-0000-0000", "例）010-0000-0000", "示例：010-0000-0000", "範例：010-0000-0000", "Ví dụ: 010-0000-0000"],
        ["shopSettings.addressPlaceholder"] = ["Example: Enter the business address", "Ejemplo: Introduce la dirección comercial", "Exemple : Saisissez l’adresse de l’entreprise", "Esempio: Inserisci l’indirizzo dell’attività", "Exemplo: Digite o endereço da empresa", "예) 사업장 주소를 입력하세요", "例）事業所の住所を入力してください", "示例：请输入经营地址", "範例：請輸入營業地址", "Ví dụ: Nhập địa chỉ doanh nghiệp"],
        ["shopSettings.operationsManager"] = ["Operations manager", "Responsable de operaciones", "Responsable d’exploitation", "Responsabile operativo", "Gerente operacional", "운영관리자", "運営管理者", "运营管理员", "營運管理員", "Quản lý vận hành"],
        ["shopSettings.managerPlaceholder"] = ["Example: Alex Kim (nickname)", "Ejemplo: Alex Kim (apodo)", "Exemple : Alex Kim (pseudonyme)", "Esempio: Alex Kim (nickname)", "Exemplo: Alex Kim (apelido)", "예) 홍길동 (닉네임)", "例）山田太郎（ニックネーム）", "示例：张伟（昵称）", "範例：王小明（暱稱）", "Ví dụ: Nguyễn An (biệt danh)"],
        ["shopSettings.emailPlaceholder"] = ["Example: admin@example.com", "Ejemplo: admin@example.com", "Exemple : admin@example.com", "Esempio: admin@example.com", "Exemplo: admin@example.com", "예) admin@example.com", "例）admin@example.com", "示例：admin@example.com", "範例：admin@example.com", "Ví dụ: admin@example.com"],
        ["shopSettings.taxType"] = ["Tax classification text", "Texto de clasificación fiscal", "Texte de classification fiscale", "Testo della classificazione fiscale", "Texto da classificação tributária", "세금 유형 문구", "税区分の文言", "税务类型文字", "稅務類型文字", "Nội dung loại thuế"],
        ["shopSettings.taxPlaceholder"] = ["Example: Small business taxpayer", "Ejemplo: Pequeño contribuyente", "Exemple : Régime de petite entreprise", "Esempio: Regime fiscale per piccole imprese", "Exemplo: Regime de pequena empresa", "예) 간이과세자", "例）簡易課税事業者", "示例：小规模纳税人", "範例：小規模營業人", "Ví dụ: Hộ kinh doanh nộp thuế đơn giản"],
        ["shopSettings.copyrightText"] = ["Copyright text (footer bottom)", "Texto de copyright (parte inferior del pie)", "Texte de copyright (bas du pied de page)", "Testo copyright (fondo del footer)", "Texto de direitos autorais (final do rodapé)", "저작권 문구 (푸터 하단)", "著作権表示（フッター下部）", "版权文字（页脚底部）", "版權文字（頁尾底部）", "Nội dung bản quyền (cuối chân trang)"],
        ["shopSettings.copyrightPlaceholder"] = ["Example: © 2026 CodeMaru Store / Dreamine Framework", "Ejemplo: © 2026 Tienda CodeMaru / Dreamine Framework", "Exemple : © 2026 Boutique CodeMaru / Dreamine Framework", "Esempio: © 2026 Negozio CodeMaru / Dreamine Framework", "Exemplo: © 2026 Loja CodeMaru / Dreamine Framework", "예) © 2026 CodeMaru 스토어 / Dreamine Framework", "例）© 2026 CodeMaruストア / Dreamine Framework", "示例：© 2026 CodeMaru 商店 / Dreamine Framework", "範例：© 2026 CodeMaru 商店 / Dreamine Framework", "Ví dụ: © 2026 Cửa hàng CodeMaru / Dreamine Framework"],
        ["shopSettings.policies"] = ["Refund · exchange/return · shipping policies", "Políticas de reembolso · cambio/devolución · envío", "Politiques de remboursement · échange/retour · livraison", "Politiche di rimborso · cambio/reso · spedizione", "Políticas de reembolso · troca/devolução · entrega", "환불 · 교환/반품 · 배송 정책", "返金・交換/返品・配送ポリシー", "退款 · 换货/退货 · 配送政策", "退款 · 換貨/退貨 · 配送政策", "Chính sách hoàn tiền · đổi/trả · giao hàng"],
        ["shopSettings.markdownHelp"] = ["Write in Markdown or plain text.", "Escribe en Markdown o texto sin formato.", "Rédigez en Markdown ou en texte brut.", "Scrivi in Markdown o testo normale.", "Escreva em Markdown ou texto simples.", "마크다운(Markdown) 또는 일반 텍스트로 작성하세요.", "Markdownまたはプレーンテキストで入力してください。", "请使用 Markdown 或纯文本编写。", "請使用 Markdown 或純文字編寫。", "Viết bằng Markdown hoặc văn bản thuần."],
        ["shopSettings.bulletList"] = ["bulleted list", "lista con viñetas", "liste à puces", "elenco puntato", "lista com marcadores", "글머리 목록", "箇条書き", "项目符号列表", "項目符號清單", "danh sách dấu đầu dòng"],
        ["shopSettings.titleExample"] = ["Title", "Título", "Titre", "Titolo", "Título", "제목", "見出し", "标题", "標題", "Tiêu đề"],
        ["shopSettings.blankLineParagraph"] = ["Separate paragraphs with a blank line", "Separa los párrafos con una línea en blanco", "Séparez les paragraphes par une ligne vide", "Separa i paragrafi con una riga vuota", "Separe os parágrafos com uma linha em branco", "빈 줄로 문단 구분", "空行で段落を区切ります", "用空行分隔段落", "以空白行分隔段落", "Tách đoạn bằng một dòng trống"],
        ["shopSettings.refundPolicy"] = ["Refund policy", "Política de reembolso", "Politique de remboursement", "Politica di rimborso", "Política de reembolso", "환불 정책", "返金ポリシー", "退款政策", "退款政策", "Chính sách hoàn tiền"],
        ["shopSettings.refundPlaceholder"] = ["- Refund requests accepted within **7 days** of receipt\n- Change of mind: customer pays round-trip shipping\n- Defect or quality issue: seller provides a full refund", "- Se aceptan solicitudes de reembolso dentro de los **7 días** siguientes a la recepción\n- Cambio de opinión: el cliente paga el envío de ida y vuelta\n- Defecto o problema de calidad: el vendedor realiza un reembolso completo", "- Demande de remboursement possible dans les **7 jours** suivant la réception\n- Changement d’avis : frais d’aller-retour à la charge du client\n- Défaut ou problème de qualité : remboursement intégral par le vendeur", "- Richiesta di rimborso entro **7 giorni** dalla ricezione\n- Ripensamento: spedizione di andata e ritorno a carico del cliente\n- Difetto o problema di qualità: rimborso completo da parte del venditore", "- Solicitações de reembolso em até **7 dias** após o recebimento\n- Arrependimento: frete de ida e volta por conta do cliente\n- Defeito ou problema de qualidade: reembolso integral pelo vendedor", "- 수령 후 **7일 이내** 환불 신청 가능\n- 단순 변심: 왕복 배송비 고객 부담\n- 하자/품질 문제: 판매자 부담으로 전액 환불", "- 受取後**7日以内**は返金申請可能\n- お客様都合: 往復送料はお客様負担\n- 不良・品質問題: 販売者負担で全額返金", "- 收货后 **7 天内**可申请退款\n- 个人原因退货：往返运费由顾客承担\n- 瑕疵或质量问题：卖家全额退款", "- 收貨後 **7 天內**可申請退款\n- 個人因素退貨：來回運費由顧客負擔\n- 瑕疵或品質問題：賣家全額退款", "- Có thể yêu cầu hoàn tiền trong vòng **7 ngày** sau khi nhận\n- Đổi ý: khách hàng chịu phí vận chuyển hai chiều\n- Lỗi hoặc vấn đề chất lượng: người bán hoàn tiền toàn bộ"],
        ["shopSettings.exchangePolicy"] = ["Exchange and return information", "Información sobre cambios y devoluciones", "Informations sur les échanges et retours", "Informazioni su cambi e resi", "Informações sobre trocas e devoluções", "교환 · 반품 안내", "交換・返品案内", "换货与退货说明", "換貨與退貨說明", "Hướng dẫn đổi và trả hàng"],
        ["shopSettings.exchangePlaceholder"] = ["- How to request: by email or phone\n- Return address: enter the address\n- Software and digital products cannot be exchanged or returned after delivery", "- Cómo solicitarlo: por correo electrónico o teléfono\n- Dirección de devolución: introduce la dirección\n- El software y los productos digitales no pueden cambiarse ni devolverse tras la entrega", "- Demande : par e-mail ou téléphone\n- Adresse de retour : saisissez l’adresse\n- Les logiciels et produits numériques ne peuvent être échangés ou retournés après livraison", "- Come richiedere: via email o telefono\n- Indirizzo di reso: inserisci l’indirizzo\n- Software e prodotti digitali non possono essere cambiati o resi dopo la consegna", "- Como solicitar: por e-mail ou telefone\n- Endereço de devolução: informe o endereço\n- Software e produtos digitais não podem ser trocados ou devolvidos após a entrega", "- 신청 방법: 이메일 또는 전화 접수\n- 반품 주소: 주소를 입력하세요\n- 소프트웨어·디지털 상품은 제공 후 교환/반품 불가", "- 申請方法: メールまたは電話\n- 返品先: 住所を入力してください\n- ソフトウェア・デジタル商品は提供後の交換・返品不可", "- 申请方式：电子邮件或电话\n- 退货地址：请输入地址\n- 软件及数字商品交付后不可换货或退货", "- 申請方式：電子郵件或電話\n- 退貨地址：請輸入地址\n- 軟體及數位商品交付後不可換貨或退貨", "- Cách yêu cầu: qua email hoặc điện thoại\n- Địa chỉ trả hàng: nhập địa chỉ\n- Phần mềm và sản phẩm kỹ thuật số không được đổi/trả sau khi cung cấp"],
        ["shopSettings.deliveryPolicy"] = ["Shipping information", "Información de envío", "Informations de livraison", "Informazioni sulla spedizione", "Informações de entrega", "배송 안내", "配送案内", "配送说明", "配送說明", "Hướng dẫn giao hàng"],
        ["shopSettings.deliveryPlaceholder"] = ["- Carrier: enter the carrier\n- Standard shipping fee: enter the amount and free-shipping threshold\n- Delivery time: 2–5 days after payment (excluding weekends and holidays)", "- Transportista: introduce el transportista\n- Gastos de envío estándar: indica el importe y el umbral de envío gratuito\n- Plazo de entrega: 2–5 días después del pago (excepto fines de semana y festivos)", "- Transporteur : saisissez le transporteur\n- Frais standard : indiquez le montant et le seuil de gratuité\n- Délai : 2 à 5 jours après paiement (hors week-ends et jours fériés)", "- Corriere: inserisci il corriere\n- Spese standard: indica importo e soglia per la spedizione gratuita\n- Tempi: 2–5 giorni dal pagamento (esclusi weekend e festivi)", "- Transportadora: informe a transportadora\n- Frete padrão: informe o valor e o limite para frete grátis\n- Prazo: 2–5 dias após o pagamento (exceto fins de semana e feriados)", "- 배송업체: 배송업체를 입력하세요\n- 기본 배송비: 금액과 무료 배송 기준을 입력하세요\n- 배송기간: 결제일 기준 2~5일 (주말·공휴일 제외)", "- 配送業者: 配送業者を入力\n- 基本送料: 金額と送料無料条件を入力\n- 配送期間: 決済日から2〜5日（週末・祝日を除く）", "- 承运商：请输入承运商\n- 标准运费：请输入金额和包邮门槛\n- 配送时间：付款后 2–5 天（周末和节假日除外）", "- 承運商：請輸入承運商\n- 標準運費：請輸入金額與免運門檻\n- 配送時間：付款後 2–5 天（週末及假日除外）", "- Đơn vị vận chuyển: nhập đơn vị vận chuyển\n- Phí tiêu chuẩn: nhập mức phí và ngưỡng miễn phí\n- Thời gian giao: 2–5 ngày sau thanh toán (không tính cuối tuần và ngày lễ)"],
        ["shopSettings.linkPreview"] = ["Link preview settings", "Configuración de vista previa del enlace", "Paramètres d’aperçu du lien", "Impostazioni anteprima link", "Configurações de prévia do link", "링크 미리보기 설정", "リンクプレビュー設定", "链接预览设置", "連結預覽設定", "Cài đặt xem trước liên kết"],
        ["shopSettings.linkPreviewHelp"] = ["The title, description, and image shown when the store link is shared in messages or social apps.", "El título, la descripción y la imagen que aparecen al compartir el enlace de la tienda en mensajes o redes sociales.", "Le titre, la description et l’image affichés lorsque le lien de la boutique est partagé dans une messagerie ou sur les réseaux sociaux.", "Titolo, descrizione e immagine mostrati quando il link del negozio viene condiviso in messaggi o social.", "Título, descrição e imagem exibidos ao compartilhar o link da loja em mensagens ou redes sociais.", "카카오톡·문자 등으로 쇼핑몰 링크를 공유할 때 표시되는 제목·설명·이미지입니다.", "メッセージやSNSでショップのリンクを共有した際に表示されるタイトル・説明・画像です。", "在消息或社交应用中分享商城链接时显示的标题、说明和图片。", "在訊息或社群應用程式中分享商店連結時顯示的標題、說明與圖片。", "Tiêu đề, mô tả và hình ảnh hiển thị khi chia sẻ liên kết cửa hàng qua tin nhắn hoặc mạng xã hội."],
        ["shopSettings.previewTitle"] = ["Preview title", "Título de vista previa", "Titre de l’aperçu", "Titolo anteprima", "Título da prévia", "미리보기 제목", "プレビュータイトル", "预览标题", "預覽標題", "Tiêu đề xem trước"],
        ["shopSettings.previewTitlePlaceholder"] = ["Leave blank to use the store name", "Déjalo en blanco para usar el nombre de la tienda", "Laissez vide pour utiliser le nom de la boutique", "Lascia vuoto per usare il nome del negozio", "Deixe em branco para usar o nome da loja", "비우면 쇼핑몰 이름이 사용됩니다", "空欄の場合はショップ名を使用します", "留空将使用商城名称", "留空將使用商店名稱", "Để trống để dùng tên cửa hàng"],
        ["shopSettings.previewDescription"] = ["Preview description", "Descripción de vista previa", "Description de l’aperçu", "Descrizione anteprima", "Descrição da prévia", "미리보기 설명", "プレビュー説明", "预览说明", "預覽說明", "Mô tả xem trước"],
        ["shopSettings.previewDescriptionPlaceholder"] = ["Leave blank to use the store description", "Déjalo en blanco para usar la descripción de la tienda", "Laissez vide pour utiliser la description de la boutique", "Lascia vuoto per usare la descrizione del negozio", "Deixe em branco para usar a descrição da loja", "비우면 쇼핑몰 설명이 사용됩니다", "空欄の場合はショップの説明を使用します", "留空将使用商城说明", "留空將使用商店說明", "Để trống để dùng mô tả cửa hàng"],
        ["shopSettings.previewImage"] = ["Preview image", "Imagen de vista previa", "Image d’aperçu", "Immagine anteprima", "Imagem da prévia", "미리보기 이미지", "プレビュー画像", "预览图片", "預覽圖片", "Hình ảnh xem trước"],
        ["shopSettings.ogImageAlt"] = ["Link preview image", "Imagen de vista previa del enlace", "Image d’aperçu du lien", "Immagine anteprima link", "Imagem de prévia do link", "링크 미리보기 이미지", "リンクプレビュー画像", "链接预览图片", "連結預覽圖片", "Hình ảnh xem trước liên kết"],
        ["shopSettings.previewImageHelp"] = ["Recommended size: 1200×630 px (landscape). Messaging apps may cache link previews, so changes might not appear immediately.", "Tamaño recomendado: 1200×630 px (horizontal). Las aplicaciones de mensajería pueden almacenar la vista previa en caché, por lo que los cambios pueden tardar.", "Taille recommandée : 1200×630 px (paysage). Les applications de messagerie peuvent mettre l’aperçu en cache, les changements peuvent donc tarder à apparaître.", "Dimensione consigliata: 1200×630 px (orizzontale). Le app di messaggistica possono memorizzare l’anteprima nella cache, quindi le modifiche potrebbero non apparire subito.", "Tamanho recomendado: 1200×630 px (horizontal). Aplicativos de mensagens podem armazenar a prévia em cache, então as alterações podem demorar a aparecer.", "권장 크기: 1200×630px (가로형). 메시지 앱은 링크 미리보기를 캐시하므로 변경 사항이 바로 반영되지 않을 수 있습니다.", "推奨サイズ: 1200×630px（横長）。メッセージアプリはリンクプレビューをキャッシュするため、変更がすぐに反映されない場合があります。", "建议尺寸：1200×630 像素（横向）。消息应用可能会缓存链接预览，因此更改可能不会立即显示。", "建議尺寸：1200×630 像素（橫向）。訊息應用程式可能會快取連結預覽，因此變更可能不會立即顯示。", "Kích thước đề xuất: 1200×630 px (ngang). Ứng dụng nhắn tin có thể lưu bộ nhớ đệm nên thay đổi có thể chưa hiển thị ngay."],
        ["shopSettings.adminHelp"] = ["Store administration uses administrator accounts linked to the shared CodeMaru sign-in.", "La administración de la tienda usa cuentas de administrador vinculadas al inicio de sesión compartido de CodeMaru.", "L’administration de la boutique utilise des comptes administrateur liés à la connexion partagée CodeMaru.", "La gestione del negozio usa account amministratore collegati all’accesso condiviso CodeMaru.", "A administração da loja usa contas de administrador vinculadas ao login compartilhado da CodeMaru.", "쇼핑몰 관리는 CodeMaru 공용 로그인에 연결된 관리자 계정으로 진행합니다.", "ショップ管理はCodeMaru共通ログインに連携した管理者アカウントで行います。", "商城管理使用与 CodeMaru 统一登录关联的管理员账户。", "商店管理使用與 CodeMaru 共用登入連結的管理員帳戶。", "Quản trị cửa hàng sử dụng tài khoản quản trị liên kết với đăng nhập chung CodeMaru."],
        ["shopSettings.noAdmins"] = ["No administrator account is linked yet.", "Aún no hay ninguna cuenta de administrador vinculada.", "Aucun compte administrateur n’est encore associé.", "Non è ancora collegato alcun account amministratore.", "Nenhuma conta de administrador está vinculada ainda.", "아직 연결된 관리자 계정이 없습니다.", "まだ管理者アカウントが連携されていません。", "尚未关联管理员账户。", "尚未連結管理員帳戶。", "Chưa có tài khoản quản trị nào được liên kết."],
        ["shopSettings.role"] = ["Role", "Rol", "Rôle", "Ruolo", "Função", "권한", "権限", "角色", "角色", "Vai trò"],
        ["roles.owner"] = ["Owner", "Propietario", "Propriétaire", "Proprietario", "Proprietário", "소유자", "所有者", "所有者", "擁有者", "Chủ sở hữu"],
        ["roles.admin"] = ["Admin", "Administrador", "Administrateur", "Amministratore", "Administrador", "관리자", "管理者", "管理员", "管理員", "Quản trị viên"],
        ["shopSettings.invalidImageType"] = ["Only JPG, PNG, WEBP, and GIF images are allowed.", "Solo se permiten imágenes JPG, PNG, WEBP y GIF.", "Seules les images JPG, PNG, WEBP et GIF sont autorisées.", "Sono consentite solo immagini JPG, PNG, WEBP e GIF.", "Apenas imagens JPG, PNG, WEBP e GIF são permitidas.", "JPG, PNG, WEBP, GIF 이미지만 가능합니다.", "JPG、PNG、WEBP、GIF画像のみ使用できます。", "仅支持 JPG、PNG、WEBP 和 GIF 图片。", "僅支援 JPG、PNG、WEBP 與 GIF 圖片。", "Chỉ chấp nhận hình ảnh JPG, PNG, WEBP và GIF."],
        ["shopSettings.imageTooLarge"] = ["The image must be 5 MB or smaller.", "La imagen debe tener 5 MB o menos.", "L’image doit faire 5 Mo ou moins.", "L’immagine deve essere di massimo 5 MB.", "A imagem deve ter no máximo 5 MB.", "5MB 이하만 업로드 가능합니다.", "画像は5MB以下にしてください。", "图片大小不得超过 5 MB。", "圖片大小不得超過 5 MB。", "Chỉ được tải hình ảnh tối đa 5 MB."],
        ["shopSettings.lastOwnerRoleError"] = ["The last Owner cannot be changed to Admin.", "El último propietario no puede cambiarse a administrador.", "Le dernier propriétaire ne peut pas devenir administrateur.", "L’ultimo proprietario non può essere cambiato in amministratore.", "O último proprietário não pode ser alterado para administrador.", "마지막 Owner 권한은 Admin으로 변경할 수 없습니다.", "最後のOwnerをAdminに変更することはできません。", "不能将最后一位 Owner 更改为 Admin。", "不能將最後一位 Owner 變更為 Admin。", "Không thể đổi Owner cuối cùng thành Admin."],
        ["shopSettings.removeOwnerError"] = ["You cannot remove yourself or the last Owner.", "No puedes eliminarte a ti mismo ni al último propietario.", "Vous ne pouvez pas vous supprimer ni supprimer le dernier propriétaire.", "Non puoi rimuovere te stesso o l’ultimo proprietario.", "Você não pode remover a si mesmo nem o último proprietário.", "자기 자신 또는 마지막 Owner는 삭제할 수 없습니다.", "自分自身または最後のOwnerは削除できません。", "不能删除自己或最后一位 Owner。", "不能刪除自己或最後一位 Owner。", "Bạn không thể xóa chính mình hoặc Owner cuối cùng."],
    };

    public static string Get(string key, string? language)
    {
        var code = Normalize(language);
        var index = Array.IndexOf(Codes, code);
        if (index < 0) index = 0;

        foreach (var table in new[] { Common, Administration, Products, Settings })
        {
            if (table.TryGetValue(key, out var values) && index < values.Length)
            {
                return values[index];
            }
        }

        return key;
    }

    private static string Normalize(string? language)
    {
        var value = language?.Trim().ToLowerInvariant().Replace('_', '-') ?? "en";
        return value switch
        {
            "zh" or "zh-cn" or "zh-sg" => "zh-hans",
            "zh-tw" or "zh-hk" or "zh-mo" => "zh-hant",
            _ => value
        };
    }
}
