using System.Globalization;

namespace ShopPlatform.Services;

/// <summary>Localized copy for the ShopStore landing, application, and owned-shop pages.</summary>
public static class ShopPlatformText
{
    // Values are ordered: en, es, fr, it, pt, ko, ja, zh-Hans, zh-Hant, vi.
    private static readonly Dictionary<string, string[]> Texts = new(StringComparer.OrdinalIgnoreCase)
    {
        ["index.pageTitle"] = ["ShopPlatform — Your own online store", "ShopPlatform — Tu propia tienda en línea", "ShopPlatform — Votre propre boutique en ligne", "ShopPlatform — Il tuo negozio online", "ShopPlatform — Sua própria loja virtual", "ShopPlatform — 나만의 쇼핑몰", "ShopPlatform — あなただけのオンラインショップ", "ShopPlatform — 您的专属网店", "ShopPlatform — 您的專屬網店", "ShopPlatform — Cửa hàng trực tuyến của riêng bạn"],
        ["index.hero.badge"] = ["Start for free", "Empieza gratis", "Commencez gratuitement", "Inizia gratis", "Comece gratuitamente", "무료로 시작하세요", "無料で始めましょう", "免费开始", "免費開始", "Bắt đầu miễn phí"],
        ["index.hero.title"] = ["Build it yourself:", "Crea tú mismo tu", "Créez vous-même votre", "Crea con le tue mani il tuo", "Crie você mesmo a sua", "내 손으로 만드는", "自分でつくる", "亲手打造您的", "親手打造您的", "Tự tay tạo nên"],
        ["index.hero.accent"] = ["Your online store", "tienda en línea", "boutique en ligne", "negozio online", "loja virtual", "온라인 쇼핑몰", "オンラインショップ", "在线商店", "線上商店", "cửa hàng trực tuyến"],
        ["index.hero.description1"] = ["From listing products to accepting payments in just five minutes.", "De publicar productos a aceptar pagos en solo cinco minutos.", "De la mise en ligne des produits au paiement en seulement cinq minutes.", "Dalla pubblicazione dei prodotti ai pagamenti in soli cinque minuti.", "Do cadastro de produtos aos pagamentos em apenas cinco minutos.", "상품 등록부터 결제까지, 5분이면 충분합니다.", "商品登録から決済まで、わずか5分。", "从上架商品到收款，只需五分钟。", "從上架商品到收款，只需五分鐘。", "Từ đăng sản phẩm đến nhận thanh toán chỉ trong năm phút."],
        ["index.hero.description2"] = ["Connect payments immediately with only your Toss Payments API keys—no separate contract required.", "Conecta los pagos al instante solo con tus claves API de Toss Payments, sin contratos adicionales.", "Connectez immédiatement les paiements avec vos clés API Toss Payments, sans contrat supplémentaire.", "Collega subito i pagamenti con le sole chiavi API di Toss Payments, senza contratti separati.", "Conecte os pagamentos imediatamente apenas com suas chaves de API da Toss Payments, sem contrato adicional.", "별도 계약 없이 토스페이먼츠 API 키만 있으면 바로 결제 연동 완료.", "別途契約なしで、Toss PaymentsのAPIキーだけですぐに決済を連携できます。", "无需另签合同，仅凭 Toss Payments API 密钥即可立即接入支付。", "無需另簽合約，只要 Toss Payments API 金鑰即可立即串接付款。", "Kết nối thanh toán ngay chỉ với khóa API Toss Payments, không cần hợp đồng riêng."],
        ["index.hero.apply"] = ["Request a store", "Solicitar una tienda", "Demander l’ouverture d’une boutique", "Richiedi l’apertura del negozio", "Solicitar uma loja", "쇼핑몰 개설 신청하기", "ショップ開設を申し込む", "申请开店", "申請開店", "Đăng ký mở cửa hàng"],
        ["index.hero.existing"] = ["Already running a store?", "¿Ya administras una tienda?", "Vous gérez déjà une boutique ?", "Gestisci già un negozio?", "Já administra uma loja?", "이미 운영 중이신가요?", "すでにショップを運営していますか？", "已经在经营店铺？", "已經在經營商店？", "Bạn đã vận hành cửa hàng?"],
        ["index.hero.manage"] = ["Manage my stores", "Administrar mis tiendas", "Gérer mes boutiques", "Gestisci i miei negozi", "Gerenciar minhas lojas", "내 쇼핑몰 관리", "自分のショップを管理", "管理我的店铺", "管理我的商店", "Quản lý cửa hàng của tôi"],
        ["index.mock.shop"] = ["My Shop", "Mi tienda", "Ma boutique", "Il mio negozio", "Minha loja", "내 쇼핑몰", "マイショップ", "我的店铺", "我的商店", "Cửa hàng của tôi"],
        ["index.shops.title"] = ["Stores now open", "Tiendas abiertas", "Boutiques en activité", "Negozi attivi", "Lojas em operação", "운영 중인 쇼핑몰", "営業中のショップ", "正在营业的店铺", "營運中的商店", "Cửa hàng đang hoạt động"],
        ["index.shops.description"] = ["Visit one now and start shopping.", "Visítalas ahora y disfruta de tus compras.", "Visitez-les dès maintenant et faites vos achats.", "Visitali ora e inizia lo shopping.", "Visite agora e aproveite suas compras.", "지금 바로 방문하고 쇼핑을 즐겨보세요.", "今すぐ訪れてショッピングをお楽しみください。", "立即访问，畅享购物。", "立即造訪，享受購物樂趣。", "Ghé thăm ngay và tận hưởng mua sắm."],
        ["index.feature.url.title"] = ["Your address, your store", "Tu dirección, tu tienda", "Votre adresse, votre boutique", "Il tuo indirizzo, il tuo negozio", "Seu endereço, sua loja", "내 주소, 내 쇼핑몰", "自分のアドレス、自分のショップ", "您的地址，您的店铺", "您的網址，您的商店", "Địa chỉ riêng, cửa hàng riêng"],
        ["index.feature.url.prefix"] = ["A unique URL in the form shop.codemaru.co.kr/", "Obtén una URL única con el formato shop.codemaru.co.kr/", "Une URL unique au format shop.codemaru.co.kr/", "Ricevi un URL univoco nel formato shop.codemaru.co.kr/", "Receba uma URL exclusiva no formato shop.codemaru.co.kr/", "shop.codemaru.co.kr/", "shop.codemaru.co.kr/", "您将获得形如 shop.codemaru.co.kr/", "您將取得如 shop.codemaru.co.kr/", "Bạn sẽ có URL riêng dạng shop.codemaru.co.kr/"],
        ["index.feature.url.suffix"] = [" is created for you. Share the link and start selling.", ". Comparte el enlace y empieza a vender.", " est créée pour vous. Partagez le lien et commencez à vendre.", " viene creato per te. Condividi il link e inizia a vendere.", " é criada para você. Compartilhe o link e comece a vender.", " 형태로 고유 URL이 생성됩니다. 링크만 공유하면 바로 판매 시작.", " 形式の専用URLが作成されます。リンクを共有すれば、すぐに販売開始。", " 的专属网址。分享链接即可开始销售。", " 的專屬網址。分享連結即可開始銷售。", ". Chỉ cần chia sẻ liên kết là có thể bắt đầu bán."],
        ["index.feature.settlement.title"] = ["Get paid directly", "Cobra directamente", "Recevez directement vos paiements", "Ricevi direttamente i pagamenti", "Receba diretamente", "내 계좌로 직접 정산", "自分の口座へ直接入金", "款项直接结算至您的账户", "款項直接結算至您的帳戶", "Nhận tiền trực tiếp"],
        ["index.feature.settlement.description"] = ["Sign up with Toss Payments and issue API keys to have payments deposited directly into your account. The platform does not act as an intermediary.", "Regístrate directamente en Toss Payments y genera claves API para recibir los pagos en tu cuenta. La plataforma no interviene como intermediaria.", "Inscrivez-vous directement auprès de Toss Payments et obtenez vos clés API pour recevoir les paiements sur votre compte. La plateforme n’intervient pas.", "Registrati direttamente su Toss Payments e ottieni le chiavi API per ricevere i pagamenti sul tuo conto. La piattaforma non fa da intermediario.", "Cadastre-se diretamente na Toss Payments e gere chaves de API para receber os pagamentos em sua conta. A plataforma não atua como intermediária.", "토스페이먼츠에 직접 가입해 API 키를 발급하면 결제 금액이 내 계좌로 바로 입금됩니다. 플랫폼이 중간에 개입하지 않습니다.", "Toss Paymentsに直接登録してAPIキーを発行すると、決済代金がご自身の口座へ直接入金されます。プラットフォームは仲介しません。", "直接注册 Toss Payments 并获取 API 密钥，付款将直接存入您的账户，平台不参与中间结算。", "直接註冊 Toss Payments 並取得 API 金鑰，款項將直接匯入您的帳戶，平台不介入結算。", "Đăng ký trực tiếp với Toss Payments và nhận khóa API để tiền thanh toán chuyển thẳng vào tài khoản của bạn. Nền tảng không làm trung gian."],
        ["index.feature.manage.title"] = ["Products and orders", "Productos y pedidos", "Produits et commandes", "Prodotti e ordini", "Produtos e pedidos", "상품·주문 관리", "商品・注文管理", "商品与订单管理", "商品與訂單管理", "Quản lý sản phẩm và đơn hàng"],
        ["index.feature.manage.description"] = ["Add, edit, and delete products, manage stock, and review orders from a single admin panel.", "Añade, edita y elimina productos, gestiona el inventario y revisa pedidos desde un solo panel.", "Ajoutez, modifiez et supprimez des produits, gérez les stocks et consultez les commandes depuis un seul panneau.", "Aggiungi, modifica ed elimina prodotti, gestisci le scorte e controlla gli ordini da un unico pannello.", "Cadastre, edite e exclua produtos, gerencie o estoque e confira pedidos em um único painel.", "상품 등록·수정·삭제, 재고 관리, 주문 내역 확인까지 어드민 패널 하나로 처리합니다.", "商品の登録・編集・削除、在庫管理、注文確認まで、1つの管理パネルで行えます。", "在一个管理面板中完成商品添加、修改、删除、库存管理和订单查看。", "透過單一管理面板完成商品新增、修改、刪除、庫存管理與訂單查看。", "Thêm, sửa, xóa sản phẩm, quản lý tồn kho và xem đơn hàng trong một bảng quản trị."],
        ["index.feature.security.title"] = ["Encrypted payment keys", "Claves de pago cifradas", "Clés de paiement chiffrées", "Chiavi di pagamento cifrate", "Chaves de pagamento criptografadas", "결제 키 암호화 보관", "決済キーを暗号化して保管", "支付密钥加密存储", "付款金鑰加密保存", "Mã hóa khóa thanh toán"],
        ["index.feature.security.description"] = ["Your secret key is encrypted on the server before storage and cannot be viewed by others.", "Tu clave secreta se cifra en el servidor antes de guardarse y nadie más puede verla.", "Votre clé secrète est chiffrée côté serveur avant d’être stockée et reste inaccessible aux tiers.", "La chiave segreta viene cifrata sul server prima di essere salvata e non è visibile ad altri.", "Sua chave secreta é criptografada no servidor antes de ser armazenada e não pode ser vista por terceiros.", "입력한 시크릿 키는 서버 측에서 암호화되어 저장됩니다. 타인이 열람할 수 없습니다.", "入力したシークレットキーはサーバー側で暗号化して保存され、第三者は閲覧できません。", "您输入的密钥会在服务器端加密后存储，他人无法查看。", "您輸入的密鑰會在伺服器端加密後保存，其他人無法查看。", "Khóa bí mật được mã hóa trên máy chủ trước khi lưu và người khác không thể xem."],
        ["index.steps.title"] = ["Open your store in three steps", "Abre tu tienda en tres pasos", "Ouvrez votre boutique en trois étapes", "Apri il negozio in tre passaggi", "Abra sua loja em três etapas", "3단계로 쇼핑몰 오픈", "3ステップでショップを開設", "三步开店", "三步開店", "Mở cửa hàng trong ba bước"],
        ["index.steps.apply.title"] = ["Request your store", "Solicita tu tienda", "Demandez votre boutique", "Richiedi il negozio", "Solicite sua loja", "개설 신청", "開設を申し込む", "申请开店", "申請開店", "Đăng ký mở cửa hàng"],
        ["index.steps.apply.description"] = ["Sign in with your CodeMaru account, choose a URL and store name, and your store opens immediately.", "Inicia sesión con tu cuenta de CodeMaru, elige una URL y un nombre, y tu tienda se abrirá al instante.", "Connectez-vous avec votre compte CodeMaru, choisissez une URL et un nom, et votre boutique ouvre immédiatement.", "Accedi con il tuo account CodeMaru, scegli URL e nome e il negozio sarà subito attivo.", "Entre com sua conta CodeMaru, escolha a URL e o nome, e sua loja será aberta imediatamente.", "CodeMaru 계정으로 로그인하고 원하는 URL과 쇼핑몰 이름을 입력하면 바로 개설됩니다.", "CodeMaruアカウントでログインし、希望のURLとショップ名を入力するとすぐに開設されます。", "登录 CodeMaru 账户并输入所需网址和店铺名称，即可立即开店。", "登入 CodeMaru 帳戶並輸入所需網址與商店名稱，即可立即開店。", "Đăng nhập bằng tài khoản CodeMaru, chọn URL và tên cửa hàng để mở ngay."],
        ["index.steps.setup.title"] = ["Add products and payment keys", "Añade productos y claves de pago", "Ajoutez les produits et les clés de paiement", "Aggiungi prodotti e chiavi di pagamento", "Cadastre produtos e chaves de pagamento", "상품 등록 & 결제 키 설정", "商品登録と決済キー設定", "添加商品并设置支付密钥", "新增商品並設定付款金鑰", "Thêm sản phẩm và khóa thanh toán"],
        ["index.steps.setup.description"] = ["Add your products in the admin page and enter your Toss API keys.", "Añade tus productos en la página de administración e introduce tus claves API de Toss.", "Ajoutez vos produits sur la page d’administration et saisissez vos clés API Toss.", "Aggiungi i prodotti nella pagina di amministrazione e inserisci le chiavi API Toss.", "Cadastre seus produtos na página administrativa e informe as chaves de API da Toss.", "어드민 페이지에서 상품을 등록하고, 토스 API 키를 입력합니다.", "管理ページで商品を登録し、Toss APIキーを入力します。", "在管理页面添加商品并输入 Toss API 密钥。", "在管理頁面新增商品並輸入 Toss API 金鑰。", "Thêm sản phẩm trong trang quản trị và nhập khóa API Toss."],
        ["index.steps.share.title"] = ["Share the link and start selling", "Comparte el enlace y empieza a vender", "Partagez le lien et commencez à vendre", "Condividi il link e inizia a vendere", "Compartilhe o link e comece a vender", "링크 공유 → 판매 시작", "リンクを共有して販売開始", "分享链接，开始销售", "分享連結，開始銷售", "Chia sẻ liên kết và bắt đầu bán"],
        ["index.steps.share.description"] = ["Share your shop.codemaru.co.kr/my-shop link on social media and start selling immediately.", "Comparte tu enlace shop.codemaru.co.kr/my-shop en redes sociales y empieza a vender de inmediato.", "Partagez votre lien shop.codemaru.co.kr/my-shop sur les réseaux sociaux et commencez à vendre immédiatement.", "Condividi il link shop.codemaru.co.kr/my-shop sui social e inizia subito a vendere.", "Compartilhe o link shop.codemaru.co.kr/my-shop nas redes sociais e comece a vender imediatamente.", "shop.codemaru.co.kr/my-shop 링크를 SNS에 공유하면 즉시 판매됩니다.", "shop.codemaru.co.kr/my-shop のリンクをSNSで共有すれば、すぐに販売できます。", "在社交媒体分享 shop.codemaru.co.kr/my-shop 链接，即可立即销售。", "在社群媒體分享 shop.codemaru.co.kr/my-shop 連結，即可立即銷售。", "Chia sẻ liên kết shop.codemaru.co.kr/my-shop lên mạng xã hội để bán hàng ngay."],
        ["index.notice.title"] = ["Service information", "Información del servicio", "Informations sur le service", "Informazioni sul servizio", "Informações do serviço", "서비스 이용 안내", "サービス利用案内", "服务使用说明", "服務使用說明", "Thông tin sử dụng dịch vụ"],
        ["index.notice.expiry.title"] = ["Automatic deletion if no product is added within 24 hours", "Eliminación automática si no añades productos en 24 horas", "Suppression automatique sans produit ajouté sous 24 heures", "Eliminazione automatica se non aggiungi prodotti entro 24 ore", "Exclusão automática se nenhum produto for cadastrado em 24 horas", "24시간 내 상품 미등록 시 자동 삭제", "24時間以内に商品未登録の場合は自動削除", "24 小时内未添加商品将自动删除", "24 小時內未新增商品將自動刪除", "Tự động xóa nếu không thêm sản phẩm trong 24 giờ"],
        ["index.notice.expiry.description"] = ["Your store is automatically deleted if you do not add at least one product within 24 hours of opening it.", "Tu tienda se eliminará automáticamente si no añades al menos un producto en las 24 horas posteriores a su apertura.", "Votre boutique est automatiquement supprimée si vous n’ajoutez pas au moins un produit dans les 24 heures suivant son ouverture.", "Il negozio viene eliminato automaticamente se non aggiungi almeno un prodotto entro 24 ore dall’apertura.", "Sua loja será excluída automaticamente se você não cadastrar ao menos um produto em até 24 horas após a abertura.", "개설 후 24시간 이내에 상품을 1개 이상 등록하지 않으면 쇼핑몰이 자동으로 삭제됩니다.", "開設後24時間以内に商品を1件以上登録しない場合、ショップは自動的に削除されます。", "开店后 24 小时内若未添加至少一件商品，店铺将被自动删除。", "開店後 24 小時內若未新增至少一件商品，商店將自動刪除。", "Cửa hàng sẽ tự động bị xóa nếu bạn không thêm ít nhất một sản phẩm trong 24 giờ sau khi mở."],
        ["index.notice.outage.title"] = ["Temporary interruptions may occur with this free service", "El servicio gratuito puede sufrir interrupciones temporales", "Ce service gratuit peut connaître des interruptions temporaires", "Il servizio gratuito può subire interruzioni temporanee", "O serviço gratuito pode ter interrupções temporárias", "무료 서비스 특성상 일시적 장애 가능", "無料サービスのため一時的な障害が発生する場合があります", "免费服务可能出现临时中断", "免費服務可能發生暫時中斷", "Dịch vụ miễn phí có thể tạm thời gián đoạn"],
        ["index.notice.outage.description"] = ["Because this service is provided free of charge, temporary connection issues or downtime may occur. Thank you for your understanding.", "Como el servicio es gratuito, pueden producirse problemas temporales de conexión o caídas. Gracias por tu comprensión.", "Ce service étant gratuit, des problèmes de connexion ou des interruptions temporaires peuvent survenir. Merci de votre compréhension.", "Poiché il servizio è gratuito, potrebbero verificarsi problemi di connessione o interruzioni temporanee. Grazie per la comprensione.", "Como este serviço é gratuito, podem ocorrer problemas temporários de acesso ou indisponibilidade. Agradecemos a compreensão.", "무료로 제공되는 서비스이므로 일시적인 접속 장애 또는 다운이 발생할 수 있습니다. 이 점 양해 부탁드립니다.", "無料で提供しているため、一時的な接続障害や停止が発生する場合があります。あらかじめご了承ください。", "由于本服务免费提供，可能会暂时无法连接或停机，敬请谅解。", "由於本服務免費提供，可能暫時無法連線或停機，敬請見諒。", "Vì đây là dịch vụ miễn phí, có thể xảy ra sự cố kết nối hoặc ngừng hoạt động tạm thời. Mong bạn thông cảm."],
        ["index.notice.support.title"] = ["We respond quickly when you contact us", "Actuamos con rapidez cuando nos contactas", "Nous intervenons rapidement lorsque vous nous contactez", "Interveniamo rapidamente quando ci contatti", "Agimos rapidamente quando você entra em contato", "문의 시 빠르게 조치해 드립니다", "お問い合わせには迅速に対応します", "联系我们后将尽快处理", "聯絡我們後將儘快處理", "Chúng tôi xử lý nhanh khi bạn liên hệ"],
        ["index.notice.support.prefix"] = ["If you encounter a problem, contact", "Si tienes algún problema, escribe a", "En cas de problème, contactez", "In caso di problemi, contatta", "Se houver algum problema, entre em contato pelo", "문제가 발생하면", "問題が発生した場合は", "如遇问题，请联系", "如遇問題，請聯絡", "Nếu gặp sự cố, hãy liên hệ"],
        ["index.notice.support.suffix"] = [". We will review it as quickly as possible.", ". Lo revisaremos lo antes posible.", ". Nous examinerons votre demande au plus vite.", ". Verificheremo il prima possibile.", ". Verificaremos o mais rápido possível.", "로 연락주세요. 최대한 빠르게 확인하겠습니다.", " までご連絡ください。できるだけ早く確認します。", "。我们会尽快核实处理。", "。我們會儘快確認處理。", ". Chúng tôi sẽ kiểm tra sớm nhất có thể."],
        ["index.footer.by"] = ["by", "por", "par", "di", "por", "제작", "提供", "出品", "製作", "bởi"],

        ["apply.pageTitle"] = ["Request a store — ShopPlatform", "Solicitar una tienda — ShopPlatform", "Demander une boutique — ShopPlatform", "Richiedi un negozio — ShopPlatform", "Solicitar uma loja — ShopPlatform", "쇼핑몰 개설 신청 — ShopPlatform", "ショップ開設申請 — ShopPlatform", "申请开店 — ShopPlatform", "申請開店 — ShopPlatform", "Đăng ký mở cửa hàng — ShopPlatform"],
        ["apply.title"] = ["Request a store", "Solicitar una tienda", "Demander l’ouverture d’une boutique", "Richiedi l’apertura di un negozio", "Solicitar uma loja", "쇼핑몰 개설 신청", "ショップ開設申請", "申请开店", "申請開店", "Đăng ký mở cửa hàng"],
        ["apply.done.title"] = ["Your store is open!", "¡Tu tienda ya está abierta!", "Votre boutique est ouverte !", "Il tuo negozio è aperto!", "Sua loja foi aberta!", "쇼핑몰이 개설되었습니다!", "ショップを開設しました！", "店铺已开通！", "商店已開通！", "Cửa hàng đã được mở!"],
        ["apply.done.description"] = ["You can start adding products right away with your current CodeMaru account.", "Ya puedes añadir productos con tu cuenta actual de CodeMaru.", "Vous pouvez immédiatement ajouter des produits avec votre compte CodeMaru actuel.", "Puoi iniziare subito ad aggiungere prodotti con il tuo account CodeMaru attuale.", "Você já pode cadastrar produtos com sua conta CodeMaru atual.", "현재 CodeMaru 계정으로 바로 상품을 등록할 수 있습니다.", "現在のCodeMaruアカウントですぐに商品を登録できます。", "您可以使用当前 CodeMaru 账户立即添加商品。", "您可以使用目前的 CodeMaru 帳戶立即新增商品。", "Bạn có thể thêm sản phẩm ngay bằng tài khoản CodeMaru hiện tại."],
        ["apply.shopUrl"] = ["Store address", "Dirección de la tienda", "Adresse de la boutique", "Indirizzo del negozio", "Endereço da loja", "쇼핑몰 주소", "ショップURL", "店铺地址", "商店網址", "Địa chỉ cửa hàng"],
        ["apply.adminUrl"] = ["Admin address", "Dirección de administración", "Adresse d’administration", "Indirizzo amministratore", "Endereço administrativo", "어드민 주소", "管理画面URL", "管理地址", "管理網址", "Địa chỉ quản trị"],
        ["apply.done.expiryPrefix"] = ["Your store is automatically deleted unless you ", "Tu tienda se eliminará automáticamente si no ", "Votre boutique sera automatiquement supprimée si vous ne ", "Il negozio verrà eliminato automaticamente se non ", "Sua loja será excluída automaticamente se você não ", "", "", "如果您未能", "若您未能", "Cửa hàng sẽ tự động bị xóa nếu bạn không "],
        ["apply.done.expiryStrong"] = ["add at least one product within 24 hours", "añades al menos un producto en 24 horas", "ajoutez pas au moins un produit sous 24 heures", "aggiungi almeno un prodotto entro 24 ore", "cadastrar ao menos um produto em 24 horas", "24시간 이내에 상품을 1개 이상 등록", "24時間以内に商品を1件以上登録", "在 24 小时内添加至少一件商品", "在 24 小時內新增至少一件商品", "thêm ít nhất một sản phẩm trong 24 giờ"],
        ["apply.done.expirySuffix"] = [".", ".", ".", ".", ".", "하지 않으면 쇼핑몰이 자동 삭제됩니다.", "しない場合、ショップは自動的に削除されます。", "，店铺将被自动删除。", "，商店將自動刪除。", "."],
        ["apply.inquiry"] = ["Contact", "Contacto", "Contact", "Contatti", "Contato", "문의", "お問い合わせ", "联系", "聯絡", "Liên hệ"],
        ["apply.done.openAdmin"] = ["Open admin", "Abrir administración", "Ouvrir l’administration", "Apri amministrazione", "Abrir administração", "어드민 바로가기", "管理画面を開く", "打开管理后台", "開啟管理後台", "Mở quản trị"],
        ["apply.viewShop"] = ["View store", "Ver tienda", "Voir la boutique", "Visualizza negozio", "Ver loja", "쇼핑몰 보기", "ショップを見る", "查看店铺", "查看商店", "Xem cửa hàng"],
        ["apply.login.description"] = ["Sign in with your CodeMaru account to create a store.", "Inicia sesión con tu cuenta de CodeMaru para crear una tienda.", "Connectez-vous avec votre compte CodeMaru pour créer une boutique.", "Accedi con il tuo account CodeMaru per creare un negozio.", "Entre com sua conta CodeMaru para criar uma loja.", "CodeMaru 계정으로 로그인하면 쇼핑몰을 만들 수 있습니다.", "CodeMaruアカウントでログインするとショップを作成できます。", "登录 CodeMaru 账户即可创建店铺。", "登入 CodeMaru 帳戶即可建立商店。", "Đăng nhập bằng tài khoản CodeMaru để tạo cửa hàng."],
        ["apply.login.action"] = ["Sign in with CodeMaru", "Iniciar sesión con CodeMaru", "Se connecter avec CodeMaru", "Accedi con CodeMaru", "Entrar com CodeMaru", "CodeMaru 계정으로 로그인", "CodeMaruアカウントでログイン", "使用 CodeMaru 登录", "使用 CodeMaru 登入", "Đăng nhập bằng CodeMaru"],
        ["apply.account.description"] = ["Create a store with the {0} account.", "Crea una tienda con la cuenta {0}.", "Créez une boutique avec le compte {0}.", "Crea un negozio con l’account {0}.", "Crie uma loja com a conta {0}.", "{0} 계정으로 쇼핑몰을 개설합니다.", "{0} アカウントでショップを開設します。", "使用 {0} 账户开设店铺。", "使用 {0} 帳戶開設商店。", "Mở cửa hàng bằng tài khoản {0}."],
        ["apply.alert.freeStrong"] = ["Completely free", "Totalmente gratis", "Entièrement gratuit", "Completamente gratuito", "Totalmente gratuito", "완전 무료", "完全無料", "完全免费", "完全免費", "Hoàn toàn miễn phí"],
        ["apply.alert.freeSuffix"] = [" with no extra fees.", ", sin cargos adicionales.", ", sans frais supplémentaires.", ", senza costi aggiuntivi.", ", sem taxas adicionais.", "로 운영됩니다. 별도 요금이 없습니다.", "で利用でき、追加料金はありません。", "，不收取额外费用。", "，不收取額外費用。", ", không có phí bổ sung."],
        ["apply.alert.expiryPrefix"] = ["Your store is ", "Tu tienda se ", "Votre boutique sera ", "Il negozio verrà ", "Sua loja será ", "개설 후 ", "開設後、", "开店后若", "開店後若", "Cửa hàng sẽ "],
        ["apply.alert.expiryStrong"] = ["automatically deleted if no product is added within 24 hours", "eliminará automáticamente si no añades productos en 24 horas", "automatiquement supprimée si aucun produit n’est ajouté sous 24 heures", "eliminato automaticamente se non aggiungi prodotti entro 24 ore", "excluída automaticamente se nenhum produto for cadastrado em 24 horas", "24시간 이내 상품 미등록 시 자동 삭제", "24時間以内に商品が登録されない場合は自動削除", "24 小时内未添加商品，将被自动删除", "24 小時內未新增商品，將自動刪除", "tự động bị xóa nếu không thêm sản phẩm trong 24 giờ"],
        ["apply.alert.expirySuffix"] = [".", ".", ".", ".", ".", "됩니다.", "されます。", "。", "。", "."],
        ["apply.alert.outage"] = ["Temporary connection issues may occur because this is a free service.", "Pueden producirse problemas temporales de conexión porque este servicio es gratuito.", "Des problèmes temporaires de connexion peuvent survenir, car ce service est gratuit.", "Potrebbero verificarsi problemi temporanei di connessione perché il servizio è gratuito.", "Podem ocorrer problemas temporários de acesso porque este serviço é gratuito.", "무료 서비스 특성상 일시적 접속 장애가 발생할 수 있습니다.", "無料サービスのため、一時的な接続障害が発生する場合があります。", "由于是免费服务，可能会暂时无法连接。", "由於是免費服務，可能會暫時無法連線。", "Có thể xảy ra sự cố kết nối tạm thời vì đây là dịch vụ miễn phí."],
        ["apply.slug.label"] = ["Preferred store address", "Dirección deseada de la tienda", "Adresse souhaitée de la boutique", "Indirizzo desiderato del negozio", "Endereço desejado da loja", "원하는 쇼핑몰 주소", "希望するショップURL", "所需店铺地址", "想要的商店網址", "Địa chỉ cửa hàng mong muốn"],
        ["apply.slug.available"] = ["This address is available", "Esta dirección está disponible", "Cette adresse est disponible", "Questo indirizzo è disponibile", "Este endereço está disponível", "사용 가능한 주소입니다", "このURLは使用できます", "该地址可以使用", "此網址可以使用", "Địa chỉ này có thể sử dụng"],
        ["apply.slug.help"] = ["Use lowercase letters, numbers, and hyphens (-) only. Examples: my-shop, flower-store", "Usa solo letras minúsculas, números y guiones (-). Ejemplos: my-shop, flower-store", "Utilisez uniquement des lettres minuscules, des chiffres et des tirets (-). Exemples : my-shop, flower-store", "Usa solo lettere minuscole, numeri e trattini (-). Esempi: my-shop, flower-store", "Use apenas letras minúsculas, números e hífens (-). Exemplos: my-shop, flower-store", "영문 소문자, 숫자, 하이픈(-)만 사용. 예: my-shop, flower-store", "英小文字、数字、ハイフン（-）のみ使用できます。例：my-shop、flower-store", "仅可使用小写英文字母、数字和连字符 (-)。例如：my-shop、flower-store", "僅可使用小寫英文字母、數字與連字號 (-)。例如：my-shop、flower-store", "Chỉ dùng chữ thường tiếng Anh, số và dấu gạch nối (-). Ví dụ: my-shop, flower-store"],
        ["apply.name.label"] = ["Store name", "Nombre de la tienda", "Nom de la boutique", "Nome del negozio", "Nome da loja", "쇼핑몰 이름", "ショップ名", "店铺名称", "商店名稱", "Tên cửa hàng"],
        ["apply.name.placeholder"] = ["Example: CodeMaru Flower Shop", "Ejemplo: Floristería CodeMaru", "Exemple : Fleurs CodeMaru", "Esempio: Fiori CodeMaru", "Exemplo: Floricultura CodeMaru", "예: 코드마루 꽃집", "例：CodeMaruフラワーショップ", "例如：CodeMaru 花店", "例如：CodeMaru 花店", "Ví dụ: Cửa hàng hoa CodeMaru"],
        ["apply.email.label"] = ["Contact email", "Correo de contacto", "E-mail de contact", "Email di contatto", "E-mail de contato", "연락처 이메일", "連絡先メール", "联系邮箱", "聯絡電子郵件", "Email liên hệ"],
        ["apply.optional"] = ["optional", "opcional", "facultatif", "facoltativo", "opcional", "선택", "任意", "可选", "選填", "không bắt buộc"],
        ["apply.email.help"] = ["We will send opening confirmation and important notices to this address.", "Enviaremos la confirmación de apertura y avisos importantes a esta dirección.", "Nous enverrons la confirmation d’ouverture et les avis importants à cette adresse.", "Invieremo la conferma di apertura e gli avvisi importanti a questo indirizzo.", "Enviaremos a confirmação de abertura e avisos importantes para este endereço.", "개설 완료 안내 및 중요 공지를 발송합니다.", "開設完了のお知らせや重要なご案内を送信します。", "我们会向此邮箱发送开店确认和重要通知。", "我們會向此信箱傳送開店確認與重要通知。", "Chúng tôi sẽ gửi xác nhận mở cửa hàng và thông báo quan trọng đến địa chỉ này."],
        ["apply.description.label"] = ["Short description", "Descripción breve", "Brève description", "Breve descrizione", "Descrição breve", "간단한 소개", "簡単な紹介", "简短介绍", "簡短介紹", "Giới thiệu ngắn"],
        ["apply.description.placeholder"] = ["Briefly describe what you sell or your store", "Describe brevemente lo que vendes o tu tienda", "Décrivez brièvement vos produits ou votre boutique", "Descrivi brevemente cosa vendi o il tuo negozio", "Descreva brevemente o que você vende ou sua loja", "판매할 상품이나 쇼핑몰에 대해 간단히 적어주세요", "販売する商品やショップについて簡単に入力してください", "请简要介绍您销售的商品或店铺", "請簡要介紹您販售的商品或商店", "Hãy mô tả ngắn gọn sản phẩm bạn bán hoặc cửa hàng"],
        ["apply.terms"] = ["I have read the free-service notice and agree that my store will be automatically deleted if I add no product within 24 hours.", "He leído el aviso del servicio gratuito y acepto que mi tienda se elimine automáticamente si no añado ningún producto en 24 horas.", "J’ai lu les conditions du service gratuit et j’accepte que ma boutique soit automatiquement supprimée si je n’ajoute aucun produit sous 24 heures.", "Ho letto l’avviso sul servizio gratuito e accetto che il negozio venga eliminato automaticamente se non aggiungo prodotti entro 24 ore.", "Li o aviso do serviço gratuito e concordo que minha loja seja excluída automaticamente se eu não cadastrar produtos em 24 horas.", "무료 서비스 이용 안내를 확인했으며, 24시간 내 상품 미등록 시 자동 삭제됨에 동의합니다.", "無料サービスの案内を確認し、24時間以内に商品を登録しない場合は自動削除されることに同意します。", "我已阅读免费服务说明，并同意若 24 小时内未添加商品，店铺将被自动删除。", "我已閱讀免費服務說明，並同意若 24 小時內未新增商品，商店將被自動刪除。", "Tôi đã đọc thông báo dịch vụ miễn phí và đồng ý rằng cửa hàng sẽ tự động bị xóa nếu không thêm sản phẩm trong 24 giờ."],
        ["apply.submitting"] = ["Submitting…", "Enviando…", "Envoi…", "Invio in corso…", "Enviando…", "신청 중...", "申請中…", "正在提交…", "正在提交…", "Đang gửi…"],
        ["apply.submit"] = ["Request my store", "Solicitar mi tienda", "Demander ma boutique", "Richiedi il mio negozio", "Solicitar minha loja", "쇼핑몰 개설 신청하기", "ショップ開設を申し込む", "申请开设我的店铺", "申請開設我的商店", "Đăng ký mở cửa hàng"],
        ["apply.existing"] = ["Already running a store?", "¿Ya administras una tienda?", "Vous gérez déjà une boutique ?", "Gestisci già un negozio?", "Já administra uma loja?", "이미 쇼핑몰을 운영 중이신가요?", "すでにショップを運営していますか？", "已经在经营店铺？", "已經在經營商店？", "Bạn đã vận hành cửa hàng?"],
        ["apply.manage"] = ["Manage my stores", "Administrar mis tiendas", "Gérer mes boutiques", "Gestisci i miei negozi", "Gerenciar minhas lojas", "내 쇼핑몰 관리", "自分のショップを管理", "管理我的店铺", "管理我的商店", "Quản lý cửa hàng của tôi"],
        ["apply.error.slugMin"] = ["Enter at least 2 characters.", "Introduce al menos 2 caracteres.", "Saisissez au moins 2 caractères.", "Inserisci almeno 2 caratteri.", "Digite pelo menos 2 caracteres.", "2자 이상 입력해주세요.", "2文字以上入力してください。", "请输入至少 2 个字符。", "請輸入至少 2 個字元。", "Vui lòng nhập ít nhất 2 ký tự."],
        ["apply.error.slugMax"] = ["Enter no more than 30 characters.", "Introduce un máximo de 30 caracteres.", "Saisissez 30 caractères maximum.", "Inserisci non più di 30 caratteri.", "Digite no máximo 30 caracteres.", "30자 이하로 입력해주세요.", "30文字以内で入力してください。", "请输入不超过 30 个字符。", "請輸入不超過 30 個字元。", "Vui lòng nhập không quá 30 ký tự."],
        ["apply.error.slugReserved"] = ["This address cannot be used.", "Esta dirección no se puede utilizar.", "Cette adresse ne peut pas être utilisée.", "Questo indirizzo non può essere utilizzato.", "Este endereço não pode ser usado.", "사용할 수 없는 주소입니다.", "このURLは使用できません。", "该地址无法使用。", "此網址無法使用。", "Không thể sử dụng địa chỉ này."],
        ["apply.error.slugTaken"] = ["This address is already in use.", "Esta dirección ya está en uso.", "Cette adresse est déjà utilisée.", "Questo indirizzo è già in uso.", "Este endereço já está em uso.", "이미 사용 중인 주소입니다.", "このURLはすでに使用されています。", "该地址已被使用。", "此網址已被使用。", "Địa chỉ này đã được sử dụng."],
        ["apply.error.nameRequired"] = ["Enter a store name.", "Introduce el nombre de la tienda.", "Saisissez le nom de la boutique.", "Inserisci il nome del negozio.", "Digite o nome da loja.", "쇼핑몰 이름을 입력해주세요.", "ショップ名を入力してください。", "请输入店铺名称。", "請輸入商店名稱。", "Vui lòng nhập tên cửa hàng."],
        ["apply.error.emailInvalid"] = ["Enter a valid email address.", "Introduce una dirección de correo válida.", "Saisissez une adresse e-mail valide.", "Inserisci un indirizzo email valido.", "Digite um endereço de e-mail válido.", "올바른 이메일 형식이 아닙니다.", "有効なメールアドレスを入力してください。", "请输入有效的电子邮箱地址。", "請輸入有效的電子郵件地址。", "Vui lòng nhập địa chỉ email hợp lệ."],
        ["apply.error.checkSlug"] = ["Check the store address.", "Comprueba la dirección de la tienda.", "Vérifiez l’adresse de la boutique.", "Controlla l’indirizzo del negozio.", "Verifique o endereço da loja.", "주소를 확인해주세요.", "ショップURLを確認してください。", "请检查店铺地址。", "請檢查商店網址。", "Vui lòng kiểm tra địa chỉ cửa hàng."],
        ["apply.error.verifySlug"] = ["Verify the address first.", "Verifica primero la dirección.", "Vérifiez d’abord l’adresse.", "Verifica prima l’indirizzo.", "Verifique primeiro o endereço.", "주소를 먼저 확인해주세요.", "先にURLを確認してください。", "请先验证地址。", "請先驗證網址。", "Vui lòng xác minh địa chỉ trước."],
        ["apply.error.slugRequired"] = ["Enter a store address.", "Introduce la dirección de la tienda.", "Saisissez l’adresse de la boutique.", "Inserisci l’indirizzo del negozio.", "Digite o endereço da loja.", "쇼핑몰 주소를 입력해주세요.", "ショップURLを入力してください。", "请输入店铺地址。", "請輸入商店網址。", "Vui lòng nhập địa chỉ cửa hàng."],
        ["apply.error.loginRequired"] = ["You need to sign in to CodeMaru.", "Debes iniciar sesión en CodeMaru.", "Vous devez vous connecter à CodeMaru.", "Devi accedere a CodeMaru.", "Você precisa entrar no CodeMaru.", "CodeMaru 로그인이 필요합니다.", "CodeMaruへのログインが必要です。", "需要登录 CodeMaru。", "需要登入 CodeMaru。", "Bạn cần đăng nhập CodeMaru."],
        ["apply.error.slugTakenOther"] = ["This address is already in use. Choose another address.", "Esta dirección ya está en uso. Elige otra.", "Cette adresse est déjà utilisée. Choisissez-en une autre.", "Questo indirizzo è già in uso. Scegline un altro.", "Este endereço já está em uso. Escolha outro.", "이미 사용 중인 주소입니다. 다른 주소를 입력해주세요.", "このURLはすでに使用されています。別のURLを入力してください。", "该地址已被使用，请输入其他地址。", "此網址已被使用，請輸入其他網址。", "Địa chỉ này đã được sử dụng. Vui lòng chọn địa chỉ khác."],
        ["apply.error.create"] = ["An error occurred while opening your store. Contact admin@codemaru.co.kr.", "Se produjo un error al abrir la tienda. Contacta con admin@codemaru.co.kr.", "Une erreur s’est produite lors de l’ouverture de la boutique. Contactez admin@codemaru.co.kr.", "Si è verificato un errore durante l’apertura del negozio. Contatta admin@codemaru.co.kr.", "Ocorreu um erro ao abrir a loja. Entre em contato com admin@codemaru.co.kr.", "개설 중 오류가 발생했습니다. admin@codemaru.co.kr 로 문의해주세요.", "開設中にエラーが発生しました。admin@codemaru.co.kr までお問い合わせください。", "开店时发生错误，请联系 admin@codemaru.co.kr。", "開店時發生錯誤，請聯絡 admin@codemaru.co.kr。", "Đã xảy ra lỗi khi mở cửa hàng. Hãy liên hệ admin@codemaru.co.kr."],

        ["myShops.pageTitle"] = ["Manage my stores — ShopStore", "Administrar mis tiendas — ShopStore", "Gérer mes boutiques — ShopStore", "Gestisci i miei negozi — ShopStore", "Gerenciar minhas lojas — ShopStore", "내 쇼핑몰 관리 — ShopStore", "自分のショップを管理 — ShopStore", "管理我的店铺 — ShopStore", "管理我的商店 — ShopStore", "Quản lý cửa hàng của tôi — ShopStore"],
        ["myShops.title"] = ["Manage my stores", "Administrar mis tiendas", "Gérer mes boutiques", "Gestisci i miei negozi", "Gerenciar minhas lojas", "내 쇼핑몰 관리", "自分のショップを管理", "管理我的店铺", "管理我的商店", "Quản lý cửa hàng của tôi"],
        ["myShops.description"] = ["Manage the stores linked to your shared CodeMaru sign-in.", "Administra las tiendas vinculadas a tu inicio de sesión compartido de CodeMaru.", "Gérez les boutiques liées à votre connexion CodeMaru.", "Gestisci i negozi collegati al tuo accesso condiviso CodeMaru.", "Gerencie as lojas vinculadas ao seu login compartilhado CodeMaru.", "CodeMaru 공통 로그인에 연결된 쇼핑몰을 관리합니다.", "CodeMaru共通ログインに連携されたショップを管理します。", "管理与 CodeMaru 统一登录关联的店铺。", "管理與 CodeMaru 共用登入連結的商店。", "Quản lý các cửa hàng liên kết với đăng nhập chung CodeMaru."],
        ["myShops.home"] = ["ShopStore home", "Inicio de ShopStore", "Accueil ShopStore", "Home ShopStore", "Início do ShopStore", "ShopStore 홈", "ShopStoreホーム", "ShopStore 首页", "ShopStore 首頁", "Trang chủ ShopStore"],
        ["myShops.login.title"] = ["Sign-in required", "Debes iniciar sesión", "Connexion requise", "Accesso richiesto", "Login necessário", "로그인이 필요합니다", "ログインが必要です", "需要登录", "需要登入", "Cần đăng nhập"],
        ["myShops.login.description"] = ["Sign in with your CodeMaru account to see the stores you manage.", "Inicia sesión con tu cuenta de CodeMaru para ver las tiendas que administras.", "Connectez-vous avec votre compte CodeMaru pour voir les boutiques que vous gérez.", "Accedi con il tuo account CodeMaru per vedere i negozi che gestisci.", "Entre com sua conta CodeMaru para ver as lojas que você gerencia.", "관리 중인 쇼핑몰을 확인하려면 CodeMaru 계정으로 로그인해 주세요.", "管理中のショップを確認するには、CodeMaruアカウントでログインしてください。", "请登录 CodeMaru 账户以查看您管理的店铺。", "請登入 CodeMaru 帳戶以查看您管理的商店。", "Đăng nhập bằng tài khoản CodeMaru để xem các cửa hàng bạn quản lý."],
        ["myShops.login.action"] = ["Sign in with CodeMaru", "Iniciar sesión con CodeMaru", "Se connecter avec CodeMaru", "Accedi con CodeMaru", "Entrar com CodeMaru", "CodeMaru 계정으로 로그인", "CodeMaruアカウントでログイン", "使用 CodeMaru 登录", "使用 CodeMaru 登入", "Đăng nhập bằng CodeMaru"],
        ["myShops.loading"] = ["Checking your stores…", "Comprobando tus tiendas…", "Vérification de vos boutiques…", "Controllo dei negozi…", "Verificando suas lojas…", "쇼핑몰을 확인하는 중...", "ショップを確認しています…", "正在检查您的店铺…", "正在檢查您的商店…", "Đang kiểm tra cửa hàng…"],
        ["myShops.empty.title"] = ["No linked stores", "No hay tiendas vinculadas", "Aucune boutique liée", "Nessun negozio collegato", "Nenhuma loja vinculada", "연결된 쇼핑몰이 없습니다", "連携されたショップがありません", "没有关联的店铺", "沒有連結的商店", "Không có cửa hàng được liên kết"],
        ["myShops.empty.description"] = ["This account does not manage any stores yet. Open a new store or link an existing one using its admin password.", "Esta cuenta aún no administra ninguna tienda. Abre una nueva o vincula una existente con su contraseña de administración.", "Ce compte ne gère encore aucune boutique. Ouvrez-en une nouvelle ou liez-en une existante avec son mot de passe administrateur.", "Questo account non gestisce ancora alcun negozio. Aprine uno nuovo o collegane uno esistente con la password amministratore.", "Esta conta ainda não gerencia nenhuma loja. Abra uma nova ou vincule uma existente usando a senha administrativa.", "아직 이 계정으로 관리 중인 쇼핑몰이 없습니다. 새 쇼핑몰을 개설하거나 기존 어드민 비밀번호로 연결해 주세요.", "このアカウントで管理しているショップはまだありません。新しく開設するか、既存の管理者パスワードで連携してください。", "此账户尚未管理任何店铺。请开设新店铺，或使用现有店铺的管理密码进行关联。", "此帳戶尚未管理任何商店。請開設新商店，或使用現有商店的管理密碼進行連結。", "Tài khoản này chưa quản lý cửa hàng nào. Hãy mở cửa hàng mới hoặc liên kết cửa hàng hiện có bằng mật khẩu quản trị."],
        ["myShops.empty.apply"] = ["Open a store", "Abrir una tienda", "Ouvrir une boutique", "Apri un negozio", "Abrir uma loja", "쇼핑몰 개설", "ショップを開設", "开设店铺", "開設商店", "Mở cửa hàng"],
        ["myShops.active"] = ["Active", "Activa", "Active", "Attivo", "Ativa", "운영중", "営業中", "营业中", "營運中", "Đang hoạt động"],
        ["myShops.inactive"] = ["Inactive", "Inactiva", "Inactive", "Non attivo", "Inativa", "비활성", "無効", "未启用", "未啟用", "Không hoạt động"],
        ["myShops.noDescription"] = ["No description.", "Sin descripción.", "Aucune description.", "Nessuna descrizione.", "Sem descrição.", "설명이 없습니다.", "説明はありません。", "暂无介绍。", "暫無介紹。", "Chưa có mô tả."],
        ["myShops.openAdmin"] = ["Open admin", "Abrir administración", "Ouvrir l’administration", "Apri amministrazione", "Abrir administração", "관리 열기", "管理画面を開く", "打开管理后台", "開啟管理後台", "Mở quản trị"],
        ["myShops.viewShop"] = ["View store", "Ver tienda", "Voir la boutique", "Visualizza negozio", "Ver loja", "쇼핑몰 보기", "ショップを見る", "查看店铺", "查看商店", "Xem cửa hàng"]
    };

    public static string Get(string key, string? language)
    {
        if (!Texts.TryGetValue(key, out var values)) return key;
        return values[LanguageIndex(language)];
    }

    public static string Format(string key, string? language, params object?[] args)
    {
        var value = Get(key, language);
        try
        {
            return string.Format(CultureInfo.CurrentCulture, value, args);
        }
        catch (FormatException)
        {
            return value;
        }
    }

    private static int LanguageIndex(string? language)
    {
        var normalized = language?.Trim().ToLowerInvariant().Replace('_', '-');
        return normalized switch
        {
            "en" => 0,
            "es" => 1,
            "fr" => 2,
            "it" => 3,
            "pt" => 4,
            "ja" => 6,
            "zh" or "zh-cn" or "zh-sg" or "zh-hans" => 7,
            "zh-tw" or "zh-hk" or "zh-mo" or "zh-hant" => 8,
            "vi" => 9,
            _ => 5
        };
    }
}
