graph LR
    Abstractions["Communication.Abstractions\nIConnectionClient\nIMessageClient"]
    Core["Communication.Core\nConnectionClientBase\nReconnectPolicy"]
    Sockets["Communication.Sockets\nTcpClient\nUdpClient\nTcpServer"]
    Serial["Communication.Serial\nSerialPortClient\nModbusRtu"]
    RabbitMQ["Communication.RabbitMQ\nRabbitMqBroker\nConsumer / Publisher"]
    Wpf["Communication.Wpf\nUI 컨트롤\nStatusIndicator"]
    FullKit["Communication.FullKit\n전체 번들"]

    Abstractions --> Core
    Core --> Sockets
    Core --> Serial
    Core --> RabbitMQ
    Sockets --> Wpf
    Serial --> Wpf
    Abstractions --> FullKit
    Core --> FullKit
    Sockets --> FullKit
    Serial --> FullKit
    RabbitMQ --> FullKit
    Wpf --> FullKit