namespace Codemaru.Services;

public static class AdminLocalization
{
    private static readonly string[] Keys =
    [
        "dashboard", "dashboardLead", "openCards", "totalUsers", "newUsers", "activeUsers", "services",
        "viewList", "accounts", "searchUsers", "close", "dbUnavailable", "noUsers", "user", "provider",
        "joined", "lastUsed", "serviceManagement", "serviceLead", "portalHealthy", "category", "status",
        "screens", "connected", "userScreen", "administrator", "noAdmin",
        "cards", "cardsLead", "backDashboard", "savedCards", "tenants", "publicUrls", "recentEdits",
        "tenantCards", "tenantLead", "searchCards", "storeUnavailable", "noCards", "tenantOwner",
        "publicPath", "lastSaved", "publicCard", "storageNote"
    ];

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Texts =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["ko"] = Map(["운영 대시보드", "CodeMaru 서비스와 관리 화면을 한곳에서 확인합니다.", "명함 관리 열기", "전체 이용자", "최근 7일 가입", "최근 7일 이용자", "연결된 서비스", "목록 보기", "공통 사용자 DB 계정", "이름, 이메일, 로그인 방식 검색", "닫기", "사용자 DB를 불러올 수 없습니다.", "조건에 맞는 이용자가 없습니다.", "이용자", "로그인 방식", "가입일", "최근 이용", "통합 서비스 관리", "각 서비스의 사용자 사이트와 관리자 사이트를 바로 엽니다.", "포털 정상", "영역", "상태", "화면 연결", "연결됨", "사용자 화면", "관리자", "관리 화면 없음", "명함 관리", "테넌트별 저장 명함과 공개 주소를 확인합니다.", "운영 대시보드", "저장된 명함", "테넌트", "공개 주소", "최근 7일 수정", "테넌트 명함 목록", "사용자 계정 하나를 하나의 테넌트로 구분합니다.", "이름, 이메일, 브랜드, 테넌트 검색", "명함 저장소를 불러올 수 없습니다.", "조건에 맞는 저장 명함이 없습니다.", "테넌트 / 소유자", "공개 경로", "최근 저장", "공개 명함", "현재 모델은 테넌트당 대표 명함 1개이며 CardId 기반 다중 명함으로 확장할 수 있습니다."]),
            ["en"] = Map(["Operations dashboard", "Manage CodeMaru services from one place.", "Open card management", "Total users", "Joined in 7 days", "Active in 7 days", "Connected services", "View list", "Accounts in the shared user database", "Search name, email, or provider", "Close", "The user database is unavailable.", "No users match the filter.", "User", "Sign-in provider", "Joined", "Last active", "Integrated service management", "Open each service and its administration site.", "Portal healthy", "Category", "Status", "Screens", "Connected", "User screen", "Admin", "No admin screen", "Card management", "Review saved cards and public URLs by tenant.", "Operations dashboard", "Saved cards", "Tenants", "Public URLs", "Edited in 7 days", "Tenant cards", "Each user account is treated as one tenant.", "Search name, email, brand, or tenant", "The card store is unavailable.", "No saved cards match the filter.", "Tenant / owner", "Public path", "Last saved", "Public card", "The current model stores one primary card per tenant and can expand to multiple CardId-based cards."]),
            ["es"] = Map(["Panel de operaciones", "Gestiona los servicios de CodeMaru en un solo lugar.", "Abrir gestión de tarjetas", "Usuarios totales", "Altas en 7 días", "Activos en 7 días", "Servicios conectados", "Ver lista", "Cuentas de la base compartida", "Buscar nombre, correo o proveedor", "Cerrar", "La base de usuarios no está disponible.", "Ningún usuario coincide.", "Usuario", "Proveedor de acceso", "Alta", "Último acceso", "Gestión integrada de servicios", "Abre cada servicio y su sitio de administración.", "Portal operativo", "Categoría", "Estado", "Pantallas", "Conectado", "Pantalla de usuario", "Administración", "Sin pantalla de administración", "Gestión de tarjetas", "Revisa tarjetas y URL públicas por inquilino.", "Panel de operaciones", "Tarjetas guardadas", "Inquilinos", "URL públicas", "Editadas en 7 días", "Tarjetas por inquilino", "Cada cuenta se trata como un inquilino.", "Buscar nombre, correo, marca o inquilino", "El almacén de tarjetas no está disponible.", "No hay tarjetas coincidentes.", "Inquilino / propietario", "Ruta pública", "Último guardado", "Tarjeta pública", "El modelo actual guarda una tarjeta principal por inquilino y admite ampliación mediante CardId."]),
            ["fr"] = Map(["Tableau des opérations", "Gérez les services CodeMaru depuis un seul endroit.", "Ouvrir la gestion des cartes", "Utilisateurs", "Inscriptions sur 7 jours", "Actifs sur 7 jours", "Services connectés", "Voir la liste", "Comptes de la base partagée", "Rechercher nom, e-mail ou fournisseur", "Fermer", "La base utilisateurs est indisponible.", "Aucun utilisateur correspondant.", "Utilisateur", "Fournisseur de connexion", "Inscription", "Dernière activité", "Gestion intégrée des services", "Ouvrez chaque service et son administration.", "Portail opérationnel", "Catégorie", "État", "Écrans", "Connecté", "Écran utilisateur", "Administration", "Aucune administration", "Gestion des cartes", "Consultez cartes et URL publiques par locataire.", "Tableau des opérations", "Cartes enregistrées", "Locataires", "URL publiques", "Modifiées sur 7 jours", "Cartes des locataires", "Chaque compte utilisateur constitue un locataire.", "Rechercher nom, e-mail, marque ou locataire", "Le stockage des cartes est indisponible.", "Aucune carte correspondante.", "Locataire / propriétaire", "Chemin public", "Dernier enregistrement", "Carte publique", "Le modèle actuel conserve une carte principale par locataire et peut évoluer avec CardId."]),
            ["it"] = Map(["Dashboard operativo", "Gestisci i servizi CodeMaru da un unico punto.", "Apri gestione biglietti", "Utenti totali", "Iscritti in 7 giorni", "Attivi in 7 giorni", "Servizi connessi", "Vedi elenco", "Account nel database condiviso", "Cerca nome, email o provider", "Chiudi", "Database utenti non disponibile.", "Nessun utente corrispondente.", "Utente", "Provider di accesso", "Iscrizione", "Ultima attività", "Gestione integrata servizi", "Apri ogni servizio e la relativa amministrazione.", "Portale operativo", "Categoria", "Stato", "Schermate", "Connesso", "Schermata utente", "Amministrazione", "Nessuna amministrazione", "Gestione biglietti", "Controlla biglietti e URL pubblici per tenant.", "Dashboard operativo", "Biglietti salvati", "Tenant", "URL pubblici", "Modificati in 7 giorni", "Biglietti tenant", "Ogni account utente è un tenant.", "Cerca nome, email, marchio o tenant", "Archivio biglietti non disponibile.", "Nessun biglietto corrispondente.", "Tenant / proprietario", "Percorso pubblico", "Ultimo salvataggio", "Biglietto pubblico", "Il modello attuale salva un biglietto principale per tenant ed è estendibile tramite CardId."]),
            ["pt"] = Map(["Painel de operações", "Gerencie os serviços CodeMaru em um só lugar.", "Abrir gestão de cartões", "Total de usuários", "Cadastros em 7 dias", "Ativos em 7 dias", "Serviços conectados", "Ver lista", "Contas no banco compartilhado", "Buscar nome, email ou provedor", "Fechar", "O banco de usuários está indisponível.", "Nenhum usuário corresponde.", "Usuário", "Provedor de login", "Cadastro", "Último acesso", "Gestão integrada de serviços", "Abra cada serviço e seu painel administrativo.", "Portal operacional", "Categoria", "Status", "Telas", "Conectado", "Tela do usuário", "Administração", "Sem tela administrativa", "Gestão de cartões", "Confira cartões e URLs públicas por locatário.", "Painel de operações", "Cartões salvos", "Locatários", "URLs públicas", "Editados em 7 dias", "Cartões por locatário", "Cada conta representa um locatário.", "Buscar nome, email, marca ou locatário", "O armazenamento de cartões está indisponível.", "Nenhum cartão corresponde.", "Locatário / proprietário", "Caminho público", "Último salvamento", "Cartão público", "O modelo atual salva um cartão principal por locatário e pode crescer com CardId."]),
            ["vi"] = Map(["Bảng điều hành", "Quản lý các dịch vụ CodeMaru tại một nơi.", "Mở quản lý danh thiếp", "Tổng người dùng", "Đăng ký trong 7 ngày", "Hoạt động trong 7 ngày", "Dịch vụ đã kết nối", "Xem danh sách", "Tài khoản trong cơ sở dữ liệu chung", "Tìm tên, email hoặc nhà cung cấp", "Đóng", "Không thể truy cập cơ sở dữ liệu người dùng.", "Không có người dùng phù hợp.", "Người dùng", "Nhà cung cấp đăng nhập", "Ngày tham gia", "Hoạt động gần nhất", "Quản lý dịch vụ tích hợp", "Mở từng dịch vụ và trang quản trị.", "Cổng hoạt động tốt", "Danh mục", "Trạng thái", "Màn hình", "Đã kết nối", "Màn hình người dùng", "Quản trị", "Không có trang quản trị", "Quản lý danh thiếp", "Xem danh thiếp và URL công khai theo tenant.", "Bảng điều hành", "Danh thiếp đã lưu", "Tenant", "URL công khai", "Sửa trong 7 ngày", "Danh thiếp tenant", "Mỗi tài khoản người dùng là một tenant.", "Tìm tên, email, thương hiệu hoặc tenant", "Kho danh thiếp không khả dụng.", "Không có danh thiếp phù hợp.", "Tenant / chủ sở hữu", "Đường dẫn công khai", "Lưu gần nhất", "Danh thiếp công khai", "Mô hình hiện tại lưu một danh thiếp chính mỗi tenant và có thể mở rộng bằng CardId."]),
            ["ja"] = Map(["運用ダッシュボード", "CodeMaruのサービスを一か所で管理します。", "名刺管理を開く", "全ユーザー", "7日間の登録", "7日間の利用者", "接続サービス", "一覧を見る", "共通ユーザーDBのアカウント", "名前、メール、ログイン方式を検索", "閉じる", "ユーザーDBを読み込めません。", "該当するユーザーはいません。", "ユーザー", "ログイン方式", "登録日", "最終利用", "統合サービス管理", "各サービスと管理サイトを開きます。", "ポータル正常", "分野", "状態", "画面", "接続済み", "ユーザー画面", "管理者", "管理画面なし", "名刺管理", "テナント別の名刺と公開URLを確認します。", "運用ダッシュボード", "保存済み名刺", "テナント", "公開URL", "7日間の更新", "テナント名刺", "各ユーザーアカウントを1テナントとして扱います。", "名前、メール、ブランド、テナントを検索", "名刺ストアを読み込めません。", "該当する名刺はありません。", "テナント / 所有者", "公開パス", "最終保存", "公開名刺", "現在はテナントごとに代表名刺1枚を保存し、CardIdで複数名刺へ拡張できます。"]),
            ["zh-hans"] = Map(["运营仪表板", "在一处管理 CodeMaru 服务。", "打开名片管理", "用户总数", "7天内注册", "7天内活跃", "已连接服务", "查看列表", "共享用户数据库账户", "搜索姓名、邮箱或登录方式", "关闭", "无法读取用户数据库。", "没有匹配的用户。", "用户", "登录方式", "注册日期", "最近使用", "集成服务管理", "打开各服务及其管理站点。", "门户正常", "类别", "状态", "页面", "已连接", "用户页面", "管理员", "无管理页面", "名片管理", "按租户查看名片和公开网址。", "运营仪表板", "已保存名片", "租户", "公开网址", "7天内修改", "租户名片", "每个用户账户视为一个租户。", "搜索姓名、邮箱、品牌或租户", "名片存储不可用。", "没有匹配的名片。", "租户 / 所有者", "公开路径", "最近保存", "公开名片", "当前每个租户保存一张主名片，并可通过 CardId 扩展为多张。"]),
            ["zh-hant"] = Map(["營運儀表板", "在一處管理 CodeMaru 服務。", "開啟名片管理", "使用者總數", "7天內註冊", "7天內活躍", "已連接服務", "查看清單", "共用使用者資料庫帳戶", "搜尋姓名、電子郵件或登入方式", "關閉", "無法讀取使用者資料庫。", "沒有符合的使用者。", "使用者", "登入方式", "註冊日期", "最近使用", "整合服務管理", "開啟各服務及其管理網站。", "入口網站正常", "類別", "狀態", "頁面", "已連接", "使用者頁面", "管理員", "無管理頁面", "名片管理", "依租戶查看名片與公開網址。", "營運儀表板", "已儲存名片", "租戶", "公開網址", "7天內修改", "租戶名片", "每個使用者帳戶視為一個租戶。", "搜尋姓名、電子郵件、品牌或租戶", "名片儲存不可用。", "沒有符合的名片。", "租戶 / 擁有者", "公開路徑", "最近儲存", "公開名片", "目前每個租戶儲存一張主要名片，並可透過 CardId 擴充為多張。"])
        };

    public static string Get(string language, string key)
    {
        var selected = Texts.TryGetValue(language, out var values) ? values : Texts["en"];
        return selected[key];
    }

    private static IReadOnlyDictionary<string, string> Map(string[] values)
    {
        if (values.Length != Keys.Length)
        {
            throw new InvalidOperationException($"Admin localization contains {values.Length} values; expected {Keys.Length}.");
        }

        return Keys.Zip(values).ToDictionary(pair => pair.First, pair => pair.Second);
    }
}
