namespace Codemaru.Services;

public sealed record ContactCopy(
    string PageTitle,
    string HireTitle,
    string Intro,
    string ScopeTitle,
    string[] Scopes,
    string PricingTitle,
    string[] PricingLabels,
    string OverseasPrice,
    string Footnote,
    string ContactCard,
    string Email,
    string Location,
    string LocationText,
    string Welcome,
    string FormTitle,
    string FormDescription,
    string FullName,
    string EmailAddress,
    string PhoneNumber,
    string Optional,
    string Message,
    string Placeholder,
    string Send,
    string Sending,
    string Success,
    string Failure);

public static class ContactLocalization
{
    private static readonly IReadOnlyDictionary<string, ContactCopy> Copies =
        new Dictionary<string, ContactCopy>(StringComparer.OrdinalIgnoreCase)
        {
            ["ko"] = Create(
                "개발 의뢰 및 문의", "개발 의뢰 안내",
                "CodeMaru는 C# WPF·MVVM 업무 프로그램, 장비 UI, 로컬 데이터베이스, ASP.NET 웹 서비스를 유지보수 가능한 구조로 개발합니다.",
                "주요 개발 범위",
                ["장비 UI 및 모니터링", "설정·레시피·파라미터 관리", "SQLite·SQL Server 로컬 프로그램", "업무용 관리자 프로그램", "ASP.NET 웹 서비스와 관리자 페이지", "CCTV·RTSP 뷰어"],
                "계약 기준",
                ["원격 기능 개발", "원격 프로젝트", "월 단위 원격 개발", "유지보수 계약", "현장 방문 지원", "국내 현장 상주", "장거리·해외 현장"],
                "항공·숙박·체류 조건에 따라 별도 산정",
                "최종 견적은 요구사항, 화면 수, 데이터베이스·장비 연동, 현장 대응 범위와 일정에 따라 달라집니다.",
                "연락 카드", "이메일", "위치", "충청남도 청양군 · 원격 및 현장 협업 가능",
                "Dreamine 관련 문의, 견적과 협업 제안을 환영합니다.",
                "의견을 보내주세요", "보내주신 내용은 연락과 회신 용도로만 사용합니다.",
                "이름", "이메일 주소", "전화번호", "선택", "문의 내용",
                "필요한 기능, 예상 일정과 원격·현장 여부를 함께 보내주세요.",
                "견적 문의 보내기", "전송 중", "메일이 전송되었습니다. 빠른 시일 내 회신드리겠습니다.", "전송에 실패했습니다. 잠시 후 다시 시도해 주세요."),
            ["en"] = Create(
                "Development Inquiry", "Project inquiry",
                "CodeMaru builds maintainable C# WPF and MVVM business software, equipment interfaces, local databases, and ASP.NET web services.",
                "Development scope",
                ["Equipment UI and monitoring", "Settings, recipes, and parameters", "SQLite and SQL Server applications", "Business administration tools", "ASP.NET services and admin portals", "CCTV and RTSP viewers"],
                "Engagement guide",
                ["Remote feature development", "Remote project", "Monthly remote development", "Maintenance agreement", "On-site visit", "Domestic on-site assignment", "Long-distance or overseas work"],
                "Quoted separately for travel and accommodation",
                "Final pricing depends on requirements, screen count, database or equipment integration, on-site scope, and schedule.",
                "Contact details", "Email", "Location", "Cheongyang, South Korea · Remote and on-site collaboration",
                "Dreamine questions, estimates, and collaboration proposals are welcome.",
                "Send a message", "Your information is used only to contact you and reply.",
                "Full name", "Email address", "Phone number", "optional", "Message",
                "Include the features you need, expected schedule, and whether work is remote or on-site.",
                "Send project inquiry", "Sending", "Your message was sent. We will reply soon.", "The message could not be sent. Please try again."),
            ["es"] = Create(
                "Consulta de desarrollo", "Solicitud de proyecto",
                "CodeMaru desarrolla software empresarial C# WPF·MVVM, interfaces de equipos, bases de datos locales y servicios ASP.NET fáciles de mantener.",
                "Áreas de desarrollo",
                ["UI y monitoreo de equipos", "Ajustes, recetas y parámetros", "Aplicaciones SQLite·SQL Server", "Herramientas administrativas", "Servicios ASP.NET y paneles", "Visores CCTV·RTSP"],
                "Guía de contratación",
                ["Función remota", "Proyecto remoto", "Desarrollo remoto mensual", "Mantenimiento", "Visita presencial", "Trabajo presencial en Corea", "Trabajo internacional"],
                "Cotización separada según viaje y alojamiento",
                "El precio final depende de requisitos, pantallas, integración, trabajo presencial y calendario.",
                "Contacto", "Correo", "Ubicación", "Cheongyang, Corea del Sur · Colaboración remota y presencial",
                "Aceptamos consultas de Dreamine, presupuestos y propuestas de colaboración.",
                "Enviar un mensaje", "Los datos se usan únicamente para contactar y responder.",
                "Nombre completo", "Correo electrónico", "Teléfono", "opcional", "Mensaje",
                "Indique funciones, calendario previsto y si el trabajo será remoto o presencial.",
                "Enviar consulta", "Enviando", "Mensaje enviado. Responderemos pronto.", "No se pudo enviar. Inténtelo de nuevo."),
            ["fr"] = Create(
                "Demande de développement", "Demande de projet",
                "CodeMaru développe des logiciels C# WPF·MVVM maintenables, interfaces d’équipement, bases locales et services ASP.NET.",
                "Domaines de développement",
                ["UI et supervision d’équipements", "Paramètres, recettes et réglages", "Applications SQLite·SQL Server", "Outils d’administration", "Services ASP.NET et portails", "Lecteurs CCTV·RTSP"],
                "Guide de collaboration",
                ["Fonction à distance", "Projet à distance", "Développement mensuel", "Maintenance", "Visite sur site", "Mission en Corée", "Mission internationale"],
                "Devis séparé selon transport et hébergement",
                "Le tarif final dépend des besoins, écrans, intégrations, présence sur site et calendrier.",
                "Coordonnées", "E-mail", "Localisation", "Cheongyang, Corée du Sud · Collaboration à distance et sur site",
                "Les questions Dreamine, demandes de devis et propositions sont les bienvenues.",
                "Envoyer un message", "Vos données servent uniquement à vous contacter et répondre.",
                "Nom complet", "Adresse e-mail", "Téléphone", "facultatif", "Message",
                "Indiquez les fonctions, le calendrier et le mode distant ou sur site.",
                "Envoyer la demande", "Envoi", "Message envoyé. Nous répondrons bientôt.", "Échec de l’envoi. Réessayez plus tard."),
            ["it"] = Create(
                "Richiesta di sviluppo", "Richiesta progetto",
                "CodeMaru sviluppa software C# WPF·MVVM manutenibile, interfacce per dispositivi, database locali e servizi ASP.NET.",
                "Aree di sviluppo",
                ["UI e monitoraggio dispositivi", "Impostazioni, ricette e parametri", "Applicazioni SQLite·SQL Server", "Strumenti amministrativi", "Servizi ASP.NET e pannelli", "Visualizzatori CCTV·RTSP"],
                "Guida alla collaborazione",
                ["Funzione da remoto", "Progetto remoto", "Sviluppo remoto mensile", "Manutenzione", "Visita in sede", "Incarico in Corea", "Incarico internazionale"],
                "Preventivo separato per viaggio e alloggio",
                "Il prezzo finale dipende da requisiti, schermate, integrazioni, presenza e calendario.",
                "Contatti", "E-mail", "Sede", "Cheongyang, Corea del Sud · Collaborazione remota e in sede",
                "Accogliamo domande Dreamine, preventivi e proposte di collaborazione.",
                "Invia un messaggio", "I dati sono usati solo per contattarti e rispondere.",
                "Nome completo", "Indirizzo e-mail", "Telefono", "facoltativo", "Messaggio",
                "Indica funzioni richieste, calendario e modalità remota o in sede.",
                "Invia richiesta", "Invio", "Messaggio inviato. Risponderemo presto.", "Invio non riuscito. Riprova più tardi."),
            ["pt"] = Create(
                "Consulta de desenvolvimento", "Solicitação de projeto",
                "A CodeMaru desenvolve software C# WPF·MVVM sustentável, interfaces de equipamentos, bases locais e serviços ASP.NET.",
                "Áreas de desenvolvimento",
                ["UI e monitoramento de equipamentos", "Configurações, receitas e parâmetros", "Aplicações SQLite·SQL Server", "Ferramentas administrativas", "Serviços ASP.NET e painéis", "Visualizadores CCTV·RTSP"],
                "Guia de contratação",
                ["Função remota", "Projeto remoto", "Desenvolvimento mensal", "Manutenção", "Visita presencial", "Trabalho presencial na Coreia", "Trabalho internacional"],
                "Orçamento separado conforme viagem e hospedagem",
                "O preço final depende dos requisitos, telas, integrações, presença e cronograma.",
                "Contato", "E-mail", "Localização", "Cheongyang, Coreia do Sul · Colaboração remota e presencial",
                "Perguntas sobre Dreamine, orçamentos e propostas são bem-vindos.",
                "Enviar mensagem", "Os dados são usados somente para contato e resposta.",
                "Nome completo", "Endereço de e-mail", "Telefone", "opcional", "Mensagem",
                "Informe funções, cronograma previsto e modalidade remota ou presencial.",
                "Enviar consulta", "Enviando", "Mensagem enviada. Responderemos em breve.", "Falha no envio. Tente novamente."),
            ["vi"] = Create(
                "Yêu cầu phát triển", "Thông tin dự án",
                "CodeMaru phát triển phần mềm C# WPF·MVVM dễ bảo trì, giao diện thiết bị, cơ sở dữ liệu cục bộ và dịch vụ ASP.NET.",
                "Phạm vi phát triển",
                ["Giao diện và giám sát thiết bị", "Cài đặt, công thức và tham số", "Ứng dụng SQLite·SQL Server", "Công cụ quản trị", "Dịch vụ ASP.NET và trang quản trị", "Trình xem CCTV·RTSP"],
                "Hình thức hợp tác",
                ["Tính năng từ xa", "Dự án từ xa", "Phát triển theo tháng", "Bảo trì", "Hỗ trợ tại chỗ", "Làm việc tại Hàn Quốc", "Công tác quốc tế"],
                "Báo giá riêng theo chi phí đi lại và lưu trú",
                "Chi phí cuối cùng phụ thuộc yêu cầu, số màn hình, tích hợp, phạm vi tại chỗ và lịch trình.",
                "Liên hệ", "Email", "Địa điểm", "Cheongyang, Hàn Quốc · Hỗ trợ từ xa và tại chỗ",
                "Chúng tôi hoan nghênh câu hỏi về Dreamine, báo giá và đề xuất hợp tác.",
                "Gửi tin nhắn", "Thông tin chỉ được dùng để liên hệ và phản hồi.",
                "Họ và tên", "Địa chỉ email", "Số điện thoại", "không bắt buộc", "Tin nhắn",
                "Hãy cho biết chức năng, lịch dự kiến và nhu cầu từ xa hoặc tại chỗ.",
                "Gửi yêu cầu", "Đang gửi", "Đã gửi tin nhắn. Chúng tôi sẽ sớm phản hồi.", "Không thể gửi. Vui lòng thử lại.")
            ,
            ["ja"] = Create(
                "開発依頼・お問い合わせ", "開発依頼のご案内",
                "CodeMaruは保守しやすいC# WPF・MVVM業務ソフト、機器UI、ローカルDB、ASP.NET Webサービスを開発します。",
                "主な開発分野",
                ["機器UI・監視", "設定・レシピ・パラメーター管理", "SQLite・SQL Serverアプリ", "業務用管理ツール", "ASP.NETサービス・管理画面", "CCTV・RTSPビューアー"],
                "契約の目安",
                ["リモート機能開発", "リモートプロジェクト", "月単位のリモート開発", "保守契約", "現地訪問", "韓国内常駐", "遠距離・海外対応"],
                "航空・宿泊・滞在条件により別途見積り",
                "最終金額は要件、画面数、DB・機器連携、現地対応範囲、日程により異なります。",
                "連絡先", "メール", "所在地", "韓国・忠清南道青陽郡 · リモート／現地対応可能",
                "Dreamineに関するご質問、お見積り、協業のご提案を歓迎します。",
                "メッセージを送る", "入力内容はご連絡と返信のためだけに使用します。",
                "お名前", "メールアドレス", "電話番号", "任意", "メッセージ",
                "必要な機能、希望日程、リモート／現地対応の希望をお知らせください。",
                "開発相談を送る", "送信中", "送信しました。近日中に返信いたします。", "送信できませんでした。しばらくしてから再度お試しください。"),
            ["zh-hans"] = Create(
                "开发委托与咨询", "开发委托说明",
                "CodeMaru 提供易于维护的 C# WPF·MVVM 业务软件、设备界面、本地数据库和 ASP.NET Web 服务开发。",
                "主要开发范围",
                ["设备界面与监控", "设置、配方与参数管理", "SQLite·SQL Server 应用", "业务管理工具", "ASP.NET 服务与管理后台", "CCTV·RTSP 查看器"],
                "合作参考",
                ["远程功能开发", "远程项目", "按月远程开发", "维护协议", "现场访问", "韩国境内驻场", "远距离或海外工作"],
                "根据交通、住宿和停留条件另行报价",
                "最终报价取决于需求、页面数量、数据库或设备连接、现场范围和日程。",
                "联系方式", "电子邮件", "位置", "韩国忠清南道青阳郡 · 支持远程与现场合作",
                "欢迎 Dreamine 咨询、报价请求和合作提案。",
                "发送消息", "您提交的信息仅用于联系和回复。",
                "姓名", "电子邮件", "电话号码", "选填", "消息",
                "请说明所需功能、预计日程以及远程或现场需求。",
                "发送项目咨询", "正在发送", "消息已发送，我们会尽快回复。", "发送失败，请稍后重试。"),
            ["zh-hant"] = Create(
                "開發委託與諮詢", "開發委託說明",
                "CodeMaru 提供易於維護的 C# WPF·MVVM 業務軟體、設備介面、本機資料庫與 ASP.NET Web 服務開發。",
                "主要開發範圍",
                ["設備介面與監控", "設定、配方與參數管理", "SQLite·SQL Server 應用", "業務管理工具", "ASP.NET 服務與管理後台", "CCTV·RTSP 檢視器"],
                "合作參考",
                ["遠端功能開發", "遠端專案", "按月遠端開發", "維護合約", "現場訪問", "韓國境內駐場", "遠距或海外工作"],
                "依交通、住宿與停留條件另行報價",
                "最終報價取決於需求、畫面數量、資料庫或設備連線、現場範圍與時程。",
                "聯絡方式", "電子郵件", "位置", "韓國忠清南道青陽郡 · 支援遠端與現場合作",
                "歡迎 Dreamine 諮詢、報價需求與合作提案。",
                "傳送訊息", "您提交的資訊僅用於聯絡與回覆。",
                "姓名", "電子郵件", "電話號碼", "選填", "訊息",
                "請說明所需功能、預計時程以及遠端或現場需求。",
                "傳送專案諮詢", "傳送中", "訊息已傳送，我們會盡快回覆。", "傳送失敗，請稍後再試。")
        };

    public static ContactCopy Get(string language) =>
        Copies.TryGetValue(language, out var copy) ? copy : Copies["en"];

    private static ContactCopy Create(
        string pageTitle, string hireTitle, string intro, string scopeTitle, string[] scopes,
        string pricingTitle, string[] pricingLabels, string overseasPrice, string footnote,
        string contactCard, string email, string location, string locationText, string welcome,
        string formTitle, string formDescription, string fullName, string emailAddress,
        string phoneNumber, string optional, string message, string placeholder, string send,
        string sending, string success, string failure) =>
        new(pageTitle, hireTitle, intro, scopeTitle, scopes, pricingTitle, pricingLabels,
            overseasPrice, footnote, contactCard, email, location, locationText, welcome,
            formTitle, formDescription, fullName, emailAddress, phoneNumber, optional,
            message, placeholder, send, sending, success, failure);
}
