namespace Codemaru.Services;

public sealed record GuideFeature(string Icon, string Title, string Description);

public sealed record GuideFaq(string Question, string Answer);

public sealed record ServiceGuideDetails(
    IReadOnlyList<string> Steps,
    IReadOnlyList<GuideFeature> Features,
    IReadOnlyList<GuideFaq> Faqs);

/// <summary>
/// Service-specific guide content. Page chrome stays shared, but workflows and FAQs
/// intentionally live here so adding a service cannot silently reuse an unrelated guide.
/// </summary>
public static class GuideDetailsCatalog
{
    private static readonly string[] FeatureIcons = ["⚙️", "👁️", "🔗"];

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, ServiceGuideDetails>> Catalog =
        new Dictionary<string, IReadOnlyDictionary<string, ServiceGuideDetails>>(StringComparer.OrdinalIgnoreCase)
        {
            ["ko"] = L(
                D("앞면·뒷면의 브랜드, 이름, 연락처와 공개 URL을 입력합니다.", "QR을 갱신해 모바일 랜딩 페이지를 확인하고 SVG·HTML·vCard를 내려받습니다.", "로그인 후 이력을 저장하면 여러 명함을 버전별로 다시 불러올 수 있습니다.",
                    "양면 명함 편집", "글꼴·크기·강조색과 배경 이미지를 앞뒷면별로 조정합니다.", "QR·vCard", "하나의 QR로 공개 프로필을 열고 연락처 파일을 저장하게 합니다.", "내보내기와 이력", "인쇄용 SVG, 랜딩 HTML과 로그인 계정의 명함 이력을 제공합니다.",
                    "QR을 만든 뒤 내용을 수정해도 되나요?", "같은 공개 URL을 유지하면 내용은 갱신됩니다. URL 이름을 바꿨다면 QR도 다시 생성하세요.", "로그인하지 않아도 명함을 만들 수 있나요?", "가능하지만 게스트 작업은 현재 브라우저에만 남습니다. 여러 기기와 버전 이력은 로그인이 필요합니다."),
                D("로그인한 뒤 고유 주소, 커플 이름, 예식일과 관리자 비밀번호로 청첩장을 만듭니다.", "관리 화면에서 사진·영상·음악·지도·예식 안내·계좌와 방명록을 구성합니다.", "레이아웃과 공개·검색 노출, OG 미리보기를 확인한 뒤 링크를 하객에게 공유합니다.",
                    "청첩장 편집", "기본 정보부터 섹션 순서, 테마와 모바일 문구까지 한곳에서 관리합니다.", "미디어와 지도", "갤러리·영상·배경음악과 예식장 좌표 및 지도 앱 링크를 제공합니다.", "공유와 운영", "방명록, 계좌 안내, 검색 노출, OG 이미지와 ThankYou 연결을 설정합니다.",
                    "만든 청첩장은 어디서 다시 수정하나요?", "로그인 후 내 청첩장 관리로 이동하거나 /청첩장주소/admin에서 관리자 비밀번호를 입력하세요.", "하객에게 보이는 언어도 관리자 언어와 함께 바뀌나요?", "관리 UI 언어와 공개 콘텐츠는 구분됩니다. 하객용 문구는 청첩장 설정에서 원하는 언어로 작성·저장합니다."),
                D("Wedding 청첩장과 연결하거나 독립된 감사장 주소를 만듭니다.", "감사 인사, 사진, 계좌·연락처와 공개 범위를 입력합니다.", "공유 미리보기 제목·설명·이미지를 확인한 뒤 링크를 전송합니다.",
                    "감사 메시지", "예식 후 인사와 추억을 모바일에 맞는 한 페이지로 정리합니다.", "사진·연락 정보", "사진과 필요한 계좌 또는 연락처를 선택적으로 함께 전달합니다.", "독립 링크와 OG", "청첩장과 분리된 주소와 메신저용 링크 미리보기를 제공합니다.",
                    "Wedding 없이도 ThankYou를 쓸 수 있나요?", "예. 독립 감사장으로 만들 수 있고, 기존 청첩장이 있다면 자연스럽게 연결할 수도 있습니다.", "청첩장 사진을 그대로 사용하나요?", "연결 시 재사용할 수 있지만 감사장 전용 사진과 OG 이미지를 별도로 지정할 수도 있습니다."),
                D("가족 앨범을 만들고 검색 노출 여부와 기본 정보를 설정합니다.", "가족을 초대한 뒤 사진·영상·이야기를 타임라인에 올립니다.", "구성원 권한과 공개 링크를 점검하고 장기간 비어 있는 앨범 정책을 확인합니다.",
                    "비공개 타임라인", "가족 기록을 일반 검색 결과와 분리해 시간순으로 보관합니다.", "가족 초대", "초대 링크와 구성원 권한으로 함께 기록하고 관리합니다.", "사진과 이야기", "사진·영상·댓글과 가족의 이야기를 한곳에서 찾아봅니다.",
                    "가족 앨범이 검색 엔진에 노출되나요?", "기본값은 비공개·검색 제외입니다. 공유 범위는 앨범 설정에서 다시 확인할 수 있습니다.", "비어 있는 새 앨범은 계속 보관되나요?", "남용 방지를 위해 생성 후 안내된 시간 안에 첫 기록이 없는 앨범은 자동 정리될 수 있습니다."),
                D("카메라가 연결된 Windows PC에 CCTV 에이전트를 설치합니다.", "RTSP 주소와 카메라 이름을 등록하고 에이전트의 HLS 변환 상태를 확인합니다.", "브라우저 뷰어에서 여러 채널과 공개·관리 링크를 점검합니다.",
                    "RTSP→HLS 변환", "브라우저가 직접 열기 어려운 RTSP 영상을 HLS로 중계합니다.", "다중 카메라", "등록된 채널을 한 화면에서 전환하고 상태를 확인합니다.", "원격 확인", "권한에 맞는 링크로 PC와 모바일 브라우저에서 영상을 확인합니다.",
                    "카메라만 연결하면 브라우저에서 바로 보이나요?", "아니요. 카메라가 연결된 Windows PC에서 에이전트가 실행되고 있어야 합니다.", "실시간 영상에 지연이 있나요?", "HLS 변환과 네트워크 버퍼 때문에 짧은 지연이 생길 수 있으며 에이전트 상태와 네트워크 품질의 영향을 받습니다."),
                D("상품 또는 개발 서비스의 설명, 가격과 제공 조건을 확인합니다.", "장바구니와 주문 정보를 확인하고 결제 또는 상담 절차를 진행합니다.", "주문 내역에서 배송·제공 상태를 확인하고 필요하면 문의합니다.",
                    "직영 상품", "CodeMaru가 직접 제공하는 상품과 소규모 개발 서비스를 안내합니다.", "주문 관리", "장바구니, 주문 상태와 배송·환불 관련 정보를 확인합니다.", "공통 계정", "CodeMaru 로그인으로 주문 내역과 문의 흐름을 이어갑니다.",
                    "누가 판매하고 운영하나요?", "상품별 판매·제공 주체와 조건을 상세 페이지에 표시하며 CodeMaru 직영 항목을 구분합니다.", "개발 서비스도 바로 결제하나요?", "범위가 정해진 상품은 주문할 수 있고, 맞춤 개발은 요구사항 확인과 견적 협의 후 진행합니다."),
                D("로그인 후 소개, 기술 스택, 경력과 외부 링크를 입력합니다.", "프로젝트마다 역할·성과·이미지·영상·저장소와 서비스 링크를 등록합니다.", "공개 범위와 대표 이미지·OG 정보를 확인한 뒤 포트폴리오 주소를 공유합니다.",
                    "프로젝트 기록", "기술과 결과뿐 아니라 맡은 역할과 운영 경험을 프로젝트별로 정리합니다.", "미디어와 링크", "대표 이미지, 영상, GitHub와 실제 서비스 링크를 함께 보여줍니다.", "공개 프로필", "공개 범위와 검색·공유 미리보기를 설정해 하나의 주소로 전달합니다.",
                    "모든 프로젝트를 공개해야 하나요?", "아니요. 준비 중인 항목은 숨기고 공개할 프로젝트만 선택할 수 있습니다.", "이미지는 어떤 크기가 좋은가요?", "목록 썸네일은 정사각형, 공유 이미지는 1200×630px, 배너는 가로형 원본을 권장합니다."),
                D("필요한 Dreamine.MVVM NuGet 패키지를 설치하고 프로젝트를 구성합니다.", "속성·명령과 소스 생성기로 ViewModel을 작성한 뒤 Locator·DI에 등록합니다.", "WPF, Blazor 또는 Hybrid 화면에 같은 ViewModel을 연결하고 샘플과 API 문서를 확인합니다.",
                    "MVVM Core·Generators", "Observable 상태, 명령과 반복 연결 코드를 소스 생성 단계에서 구성합니다.", "Locator·DI", "ViewModel과 서비스 계층을 플랫폼에 덜 의존적인 방식으로 주입합니다.", "WPF·Blazor Hybrid", "데스크톱과 웹 UI가 같은 도메인·ViewModel 흐름을 공유하도록 돕습니다.",
                    "Dreamine은 화면 제작 도구인가요?", "화면 디자이너가 아니라 MVVM 구조, 생성기, DI와 WPF·Blazor 통합을 제공하는 개발 프레임워크입니다.", "어떤 패키지부터 설치해야 하나요?", "기본은 Dreamine.MVVM.Core이며 자동 생성은 Generators, 주입은 Locators, 하이브리드 앱은 Hybrid.Wpf 패키지를 함께 사용합니다.")),

            ["en"] = L(
                D("Enter the front/back brand, identity, contact details, and public URL.", "Refresh the QR, test the mobile landing page, then export SVG, HTML, or vCard.", "Sign in to save versions and restore more than one card across sessions.", "Two-sided editor", "Control typography, sizing, accent color, and back images for each side.", "QR and vCard", "Open one public profile and let visitors save a contact file from its QR.", "Exports and history", "Produce print SVG, landing HTML, and account-backed card versions.", "Can I edit a card after creating its QR?", "Yes while the public URL stays the same. Regenerate the QR when the URL name changes.", "Can I create a card without signing in?", "Yes, but guest work remains in this browser. Sign in for history and cross-device access."),
                D("Sign in and create an invitation with a URL, couple name, date, and admin password.", "Add ceremony details, photos, video, music, maps, accounts, and guestbook content in Admin.", "Review layout, visibility, search, and OG preview settings before sharing the link.", "Invitation editor", "Manage basic details, section order, themes, and mobile copy in one workspace.", "Media and maps", "Publish galleries, video, background music, venue coordinates, and map-app links.", "Sharing and operations", "Configure guestbook, account info, search visibility, OG, and ThankYou linking.", "Where do I edit an existing invitation?", "Use My invitations after sign-in, or enter the admin password at /your-slug/admin.", "Does the guest language automatically follow my admin language?", "No. Admin UI language and public content are separate; save guest-facing copy in the intended language."),
                D("Connect a Wedding invitation or create a standalone ThankYou address.", "Add a thank-you message, photos, optional account/contact details, and visibility.", "Review the share title, description, and image before sending the link.", "Thank-you story", "Present post-event gratitude and memories on a mobile-first page.", "Photos and contacts", "Optionally share selected images and useful account or contact details.", "Standalone link and OG", "Use a separate URL with its own messenger/social preview.", "Can I use ThankYou without Wedding?", "Yes. It works independently and can also be linked from an existing invitation.", "Must it reuse the invitation photos?", "No. You can reuse them or upload ThankYou-specific photos and an OG image."),
                D("Create a family album and choose its basic privacy and discovery settings.", "Invite family members, then add photos, video, and stories to the timeline.", "Review member permissions and the cleanup policy for unused new albums.", "Private timeline", "Keep family records in chronological order and away from ordinary search results.", "Family invitations", "Collaborate through invitation links and member permissions.", "Photos and stories", "Browse media, comments, and family stories together.", "Will a family album appear in search engines?", "It is private and excluded by default; confirm the sharing scope in album settings.", "Are empty albums kept forever?", "An album with no first post within the stated period may be cleaned up to prevent abuse."),
                D("Install the CCTV agent on the Windows PC connected to the cameras.", "Register RTSP addresses and names, then confirm each HLS conversion status.", "Open the browser viewer and verify channels plus public/admin links.", "RTSP to HLS", "Relay camera streams in a browser-compatible HLS format.", "Multi-camera view", "Switch among registered channels and inspect their health in one place.", "Remote viewing", "Use permission-aware links from desktop and mobile browsers.", "Can a browser open the camera without the agent?", "No. The agent must be running on the Windows PC that can reach the camera.", "Why is there a short delay?", "HLS conversion and network buffering add latency; agent and network health also matter."),
                D("Review each product or development service, price, and delivery conditions.", "Confirm the cart and order information, then continue to payment or consultation.", "Track fulfillment or delivery in order history and contact support when needed.", "Direct offerings", "Browse goods and scoped development services provided directly by CodeMaru.", "Order management", "Follow cart, order, shipping, cancellation, and refund information.", "Shared account", "Keep purchases and support conversations under your CodeMaru login.", "Who sells and operates the listings?", "Each detail page identifies the provider and terms, including CodeMaru-direct items.", "Can custom development be purchased immediately?", "Fixed-scope items can be ordered; custom work begins after requirements and quotation review."),
                D("Sign in and complete your profile, stack, experience, and external links.", "Add each project's role, results, media, repository, and live service links.", "Set visibility and OG metadata, preview the profile, then share its address.", "Project case studies", "Describe responsibilities, measurable outcomes, and production operations by project.", "Media and links", "Combine cover images, video, GitHub, and live service links.", "Public profile", "Control visibility, search metadata, and link previews from one address.", "Must every project be public?", "No. Keep drafts hidden and publish only the projects you choose.", "What image sizes work best?", "Use square list thumbnails, 1200×630px share images, and wide originals for banners."),
                D("Install the Dreamine.MVVM NuGet packages required by your application.", "Build ViewModels with properties, commands, source generators, Locator, and DI.", "Bind the same ViewModel flow to WPF, Blazor, or Hybrid UI and review samples/API docs.", "MVVM Core and Generators", "Generate observable state, commands, and repetitive glue at compile time.", "Locator and DI", "Inject ViewModels and services with less platform coupling.", "WPF and Blazor Hybrid", "Share domain and ViewModel flows between desktop and web UI.", "Is Dreamine a visual page builder?", "No. It is a developer framework for MVVM structure, generators, DI, and WPF/Blazor integration.", "Which package should I install first?", "Start with Dreamine.MVVM.Core; add Generators, Locators, and Hybrid.Wpf for those capabilities.")),

            ["ja"] = L(
                D("表裏のブランド、氏名、連絡先、公開URLを入力します。", "QRを更新し、公開ページを確認してSVG・HTML・vCardを出力します。", "ログインして複数の名刺とバージョンを履歴に保存します。", "両面編集", "文字、サイズ、色、背景を面ごとに調整します。", "QR・vCard", "QRからプロフィールを開き連絡先を保存できます。", "出力・履歴", "印刷SVG、HTML、ログイン履歴を提供します。", "QR作成後も編集できますか？", "同じ公開URLなら更新されます。URL名を変えた場合はQRも再生成してください。", "未ログインでも作れますか？", "作成できますがゲスト作業は現在のブラウザーだけに残ります。"),
                D("ログイン後、URL、二人の名前、挙式日、管理パスワードで招待状を作ります。", "管理画面で写真・動画・音楽・地図・案内・口座・芳名帳を設定します。", "レイアウト、公開範囲、検索、OGを確認して共有します。", "招待状編集", "基本情報、セクション順、テーマを一元管理します。", "メディア・地図", "写真、動画、BGM、会場座標と地図リンクを掲載します。", "共有・運用", "芳名帳、口座、検索、OG、ThankYou連携を設定します。", "既存の招待状はどこで編集しますか？", "ログイン後の一覧、または /招待状URL/admin で管理パスワードを入力します。", "管理画面の言語が招待状にも反映されますか？", "管理UIと公開文面は別です。ゲスト向け文面は希望言語で保存してください。"),
                D("Weddingと連携するか、独立したThankYou URLを作ります。", "お礼、写真、任意の口座・連絡先と公開範囲を入力します。", "共有タイトル、説明、画像を確認して送ります。", "お礼メッセージ", "挙式後の感謝と思い出をモバイルページにまとめます。", "写真・連絡先", "必要な写真と口座・連絡先を選んで共有します。", "独立URL・OG", "専用URLとメッセンジャー用プレビューを持てます。", "Weddingなしでも使えますか？", "はい。単独で作成でき、既存の招待状にも連携できます。", "招待状の写真を使う必要がありますか？", "いいえ。再利用も専用写真・OG画像の登録も可能です。"),
                D("家族アルバムを作り、公開範囲と検索設定を選びます。", "家族を招待して写真・動画・物語を投稿します。", "権限と未使用アルバムの整理方針を確認します。", "非公開タイムライン", "家族の記録を検索結果から分けて時系列で保存します。", "家族招待", "招待リンクと権限で共同管理します。", "写真・物語", "メディア、コメント、家族の物語をまとめます。", "検索エンジンに表示されますか？", "初期設定は非公開・検索除外です。共有範囲を設定で確認してください。", "空のアルバムは残りますか？", "案内期間内に最初の投稿がない新規アルバムは整理される場合があります。"),
                D("カメラ接続済みWindows PCへCCTVエージェントを入れます。", "RTSP URLと名称を登録してHLS変換状態を確認します。", "ブラウザーでチャンネルと公開・管理リンクを確認します。", "RTSP→HLS", "RTSPをブラウザー対応HLSへ中継します。", "複数カメラ", "登録チャンネルと状態を一画面で確認します。", "遠隔表示", "権限付きリンクをPC・モバイルで開けます。", "エージェントなしで見られますか？", "いいえ。カメラへ接続できるWindows PCでエージェントを実行します。", "遅延はありますか？", "HLS変換とバッファにより短い遅延が発生します。"),
                D("商品・開発サービスの内容、価格、提供条件を確認します。", "カートと注文内容を確認し決済または相談へ進みます。", "注文履歴で配送・提供状態を追跡します。", "直営商品", "CodeMaru提供の商品と開発サービスを掲載します。", "注文管理", "注文、配送、取消、返金情報を確認します。", "共通アカウント", "CodeMaruログインで購入と問い合わせを管理します。", "販売者は誰ですか？", "詳細ページに提供者と条件を表示し、直営商品を区別します。", "カスタム開発も即購入できますか？", "定型商品は注文でき、個別開発は要件と見積確認後に開始します。"),
                D("プロフィール、技術、経験、外部リンクを入力します。", "各プロジェクトの役割、成果、画像、動画、リポジトリを追加します。", "公開範囲とOGを確認してURLを共有します。", "事例記録", "役割、成果、運用経験をプロジェクト別に整理します。", "メディア・リンク", "画像、動画、GitHub、公開サービスを掲載します。", "公開プロフィール", "公開範囲、検索、リンクプレビューを管理します。", "全プロジェクトを公開しますか？", "いいえ。下書きを隠し、選択した項目だけ公開できます。", "推奨画像サイズは？", "一覧は正方形、共有画像は1200×630px、バナーは横長を推奨します。"),
                D("必要なDreamine.MVVM NuGetパッケージを入れます。", "プロパティ、コマンド、生成器、Locator、DIでViewModelを作ります。", "同じViewModelをWPF・Blazor・Hybrid UIへ接続します。", "Core・Generators", "状態、コマンド、反復コードをコンパイル時に生成します。", "Locator・DI", "ViewModelとサービスを低依存で注入します。", "WPF・Blazor Hybrid", "デスクトップとWebでドメインとViewModelを共有します。", "画面作成ツールですか？", "いいえ。MVVM構造、生成器、DI、WPF/Blazor統合の開発フレームワークです。", "最初のパッケージは？", "Dreamine.MVVM.Coreから始め、必要に応じGenerators、Locators、Hybrid.Wpfを追加します。")),

            ["zh-hans"] = Chinese(false),
            ["zh-hant"] = Chinese(true),
            ["vi"] = Vietnamese(),
            ["es"] = Western("es"),
            ["fr"] = Western("fr"),
            ["it"] = Western("it"),
            ["pt"] = Western("pt")
        };

    public static ServiceGuideDetails Get(string? language, string serviceKey)
    {
        var languageCatalog = Catalog.TryGetValue(language ?? string.Empty, out var localized)
            ? localized
            : Catalog["en"];
        var normalizedKey = serviceKey.Equals("shop", StringComparison.OrdinalIgnoreCase) ? "shopstore" : serviceKey;
        return languageCatalog.TryGetValue(normalizedKey, out var details)
            ? details
            : languageCatalog["cardhybrid"];
    }

    private static IReadOnlyDictionary<string, ServiceGuideDetails> L(params ServiceGuideDetails[] details)
    {
        string[] keys = ["cardhybrid", "wedding", "thankyou", "families", "cctv", "shopstore", "portfolio", "dreamine"];
        if (details.Length != keys.Length)
        {
            throw new InvalidOperationException($"Guide catalog contains {details.Length} services; expected {keys.Length}.");
        }

        return keys.Zip(details, (key, value) => new KeyValuePair<string, ServiceGuideDetails>(key, value))
            .ToDictionary(pair => pair.Key, pair => pair.Value, StringComparer.OrdinalIgnoreCase);
    }

    private static ServiceGuideDetails D(params string[] values)
    {
        if (values.Length != 13)
        {
            throw new InvalidOperationException($"Service guide contains {values.Length} values; expected 13.");
        }

        return new(
            values[..3],
            [new(FeatureIcons[0], values[3], values[4]), new(FeatureIcons[1], values[5], values[6]), new(FeatureIcons[2], values[7], values[8])],
            [new(values[9], values[10]), new(values[11], values[12])]);
    }

    private static IReadOnlyDictionary<string, ServiceGuideDetails> Chinese(bool traditional) => traditional
        ? L(
            D("輸入名片正反面的品牌、姓名、聯絡方式與公開網址。", "更新 QR 並確認公開頁面，再匯出 SVG、HTML 或 vCard。", "登入後儲存多張名片與版本紀錄。", "雙面編輯", "分別調整字型、尺寸、色彩與背景。", "QR 與 vCard", "用一個 QR 開啟公開資料並儲存聯絡人。", "匯出與紀錄", "提供印刷 SVG、HTML 與帳戶版本。", "QR 建立後可以修改嗎？", "公開網址不變即可更新；網址名稱改變時請重建 QR。", "不登入也能建立嗎？", "可以，但訪客內容只保存在目前瀏覽器。"),
            D("登入後以網址、雙方姓名、婚期與管理密碼建立喜帖。", "在管理頁加入照片、影片、音樂、地圖、帳戶與留言簿。", "確認版型、公開範圍、搜尋與 OG 後分享。", "喜帖編輯", "集中管理基本資訊、區塊順序與主題。", "媒體與地圖", "提供相簿、影片、音樂、會場座標與地圖連結。", "分享與營運", "設定留言簿、帳戶、搜尋、OG 與 ThankYou。", "如何再次編輯？", "登入後開啟我的喜帖，或在 /喜帖網址/admin 輸入管理密碼。", "管理語言會改變賓客內容嗎？", "不會。管理 UI 與公開文案分開，請以需要的語言儲存文案。"),
            D("連結 Wedding 或建立獨立 ThankYou 網址。", "輸入謝詞、照片、選用的帳戶／聯絡資料與公開範圍。", "確認分享標題、描述與圖片後傳送。", "感謝訊息", "以行動頁整理婚禮後的謝意與回憶。", "照片與聯絡資料", "選擇性分享照片、帳戶或聯絡資訊。", "獨立網址與 OG", "提供專屬網址與社群預覽。", "沒有 Wedding 也能使用嗎？", "可以獨立建立，也能連結既有喜帖。", "一定要沿用喜帖照片嗎？", "不用，可重用或上傳專用照片與 OG 圖片。"),
            D("建立家庭相簿並選擇隱私與搜尋設定。", "邀請家人後上傳照片、影片與故事。", "確認成員權限與未使用相簿清理政策。", "私人時間軸", "依時間保存家庭紀錄並排除一般搜尋。", "家人邀請", "以邀請連結和權限共同管理。", "照片與故事", "集中瀏覽媒體、留言與家庭故事。", "會出現在搜尋引擎嗎？", "預設為私人且不索引，請在設定確認分享範圍。", "空相簿會永久保留嗎？", "在公告期間內沒有第一篇內容的新相簿可能被清理。"),
            D("在連接攝影機的 Windows PC 安裝 CCTV Agent。", "登錄 RTSP 網址與名稱並確認 HLS 轉換狀態。", "在瀏覽器確認多個頻道與公開／管理連結。", "RTSP→HLS", "將 RTSP 中繼為瀏覽器支援的 HLS。", "多攝影機", "在一個畫面切換頻道並檢查狀態。", "遠端檢視", "以權限連結在電腦與手機觀看。", "不用 Agent 可以觀看嗎？", "不行，能連接攝影機的 Windows PC 必須執行 Agent。", "為何有短暫延遲？", "HLS 轉換與網路緩衝會產生延遲。"),
            D("查看商品或開發服務的內容、價格與提供條件。", "確認購物車與訂單後進行付款或洽詢。", "在訂單紀錄追蹤配送與服務狀態。", "直營項目", "提供 CodeMaru 商品與範圍明確的開發服務。", "訂單管理", "查看訂單、配送、取消與退款資訊。", "共用帳戶", "用 CodeMaru 登入管理購買與詢問。", "由誰銷售？", "詳細頁會標示提供者、條件與 CodeMaru 直營項目。", "客製開發能直接購買嗎？", "固定範圍可下單，客製項目需確認需求與報價。"),
            D("輸入個人介紹、技術、經歷與外部連結。", "為專案加入角色、成果、圖片、影片與程式庫。", "設定公開範圍與 OG 後分享作品集網址。", "專案案例", "按專案整理責任、成果與營運經驗。", "媒體與連結", "一起顯示圖片、影片、GitHub 與正式服務。", "公開資料", "管理公開範圍、搜尋與連結預覽。", "所有專案都必須公開嗎？", "不用，可以隱藏草稿並只公開選定專案。", "建議圖片尺寸？", "列表使用方形，分享圖 1200×630px，橫幅使用寬幅原圖。"),
            D("安裝應用程式需要的 Dreamine.MVVM NuGet 套件。", "以屬性、命令、產生器、Locator 與 DI 建立 ViewModel。", "將相同 ViewModel 連接至 WPF、Blazor 或 Hybrid UI。", "Core 與 Generators", "在編譯時產生狀態、命令與重複連接碼。", "Locator 與 DI", "以較低平台相依性注入 ViewModel 和服務。", "WPF／Blazor Hybrid", "讓桌面與網頁共用領域和 ViewModel。", "這是視覺化頁面製作器嗎？", "不是，是提供 MVVM、產生器、DI 與 WPF/Blazor 整合的框架。", "先安裝哪個套件？", "從 Dreamine.MVVM.Core 開始，再依需求加入 Generators、Locators、Hybrid.Wpf。"))
        : L(
            D("输入名片正反面的品牌、姓名、联系方式和公开网址。", "刷新二维码并检查公开页面，再导出 SVG、HTML 或 vCard。", "登录后保存多张名片和版本记录。", "双面编辑", "分别调整字体、尺寸、颜色和背景。", "二维码与 vCard", "用一个二维码打开资料并保存联系人。", "导出与记录", "提供印刷 SVG、HTML 和账户版本。", "生成二维码后还能修改吗？", "公开网址不变即可更新；网址名称变化时请重新生成二维码。", "不登录也能创建吗？", "可以，但访客内容只保存在当前浏览器。"),
            D("登录后用网址、双方姓名、婚期和管理密码创建请柬。", "在管理页添加照片、视频、音乐、地图、账户和留言簿。", "检查布局、公开范围、搜索和 OG 后分享。", "请柬编辑", "集中管理基本信息、区块顺序和主题。", "媒体与地图", "提供相册、视频、音乐、会场坐标和地图链接。", "分享与运营", "设置留言簿、账户、搜索、OG 和 ThankYou。", "如何再次编辑？", "登录后打开我的请柬，或在 /请柬网址/admin 输入管理密码。", "管理语言会改变宾客内容吗？", "不会。管理 UI 和公开文案分开，请用需要的语言保存文案。"),
            D("连接 Wedding 或创建独立 ThankYou 网址。", "填写谢词、照片、可选账户／联系方式和公开范围。", "检查分享标题、描述和图片后发送。", "感谢信息", "用移动页面整理婚礼后的谢意和回忆。", "照片与联系信息", "选择性分享照片、账户或联系方式。", "独立网址和 OG", "提供专属网址与社交预览。", "没有 Wedding 也能使用吗？", "可以独立创建，也能连接已有请柬。", "必须沿用请柬照片吗？", "不必，可复用或上传专用照片和 OG 图片。"),
            D("创建家庭相册并选择隐私与搜索设置。", "邀请家人后上传照片、视频和故事。", "检查成员权限和未使用相册清理政策。", "私人时间线", "按时间保存家庭记录并排除普通搜索。", "家人邀请", "用邀请链接和权限共同管理。", "照片与故事", "集中浏览媒体、评论和家庭故事。", "会出现在搜索引擎吗？", "默认私密且不索引，请在设置中确认分享范围。", "空相册会永久保留吗？", "在提示期限内没有首篇内容的新相册可能被清理。"),
            D("在连接摄像头的 Windows PC 安装 CCTV Agent。", "登记 RTSP 地址和名称并确认 HLS 转换状态。", "在浏览器检查多个频道和公开／管理链接。", "RTSP→HLS", "将 RTSP 中继为浏览器支持的 HLS。", "多摄像头", "在一个页面切换频道并检查状态。", "远程查看", "用权限链接在电脑和手机观看。", "没有 Agent 能观看吗？", "不能，可连接摄像头的 Windows PC 必须运行 Agent。", "为什么有短暂延迟？", "HLS 转换和网络缓冲会带来延迟。"),
            D("查看商品或开发服务的内容、价格和条件。", "确认购物车和订单后付款或咨询。", "在订单记录跟踪配送与服务状态。", "直营项目", "提供 CodeMaru 商品和范围明确的开发服务。", "订单管理", "查看订单、配送、取消和退款信息。", "共享账户", "用 CodeMaru 登录管理购买和咨询。", "由谁销售？", "详情页会标明提供方、条件和 CodeMaru 直营项目。", "定制开发能直接购买吗？", "固定范围可下单，定制项目需确认需求和报价。"),
            D("填写个人介绍、技术、经历和外部链接。", "为项目添加角色、成果、图片、视频和代码仓库。", "设置公开范围和 OG 后分享作品集网址。", "项目案例", "按项目整理职责、成果与运营经验。", "媒体与链接", "一起展示图片、视频、GitHub 和正式服务。", "公开资料", "管理公开范围、搜索和链接预览。", "所有项目都要公开吗？", "不需要，可隐藏草稿并只公开选定项目。", "推荐图片尺寸？", "列表用方图，分享图 1200×630px，横幅用宽幅原图。"),
            D("安装应用所需的 Dreamine.MVVM NuGet 包。", "用属性、命令、生成器、Locator 和 DI 创建 ViewModel。", "把同一 ViewModel 连接到 WPF、Blazor 或 Hybrid UI。", "Core 与 Generators", "在编译时生成状态、命令和重复连接代码。", "Locator 与 DI", "以更低平台依赖注入 ViewModel 和服务。", "WPF／Blazor Hybrid", "让桌面和网页共享领域与 ViewModel。", "这是可视化页面生成器吗？", "不是，它是提供 MVVM、生成器、DI 与 WPF/Blazor 集成的框架。", "先装哪个包？", "从 Dreamine.MVVM.Core 开始，再按需添加 Generators、Locators、Hybrid.Wpf。"));

    private static IReadOnlyDictionary<string, ServiceGuideDetails> Vietnamese() => L(
        D("Nhập thương hiệu, tên, liên hệ và URL công khai cho hai mặt danh thiếp.", "Làm mới QR, kiểm tra trang công khai rồi xuất SVG, HTML hoặc vCard.", "Đăng nhập để lưu nhiều danh thiếp và lịch sử phiên bản.", "Sửa hai mặt", "Điều chỉnh phông, cỡ chữ, màu và nền cho từng mặt.", "QR và vCard", "Mở hồ sơ và lưu liên hệ bằng một mã QR.", "Xuất và lịch sử", "Cung cấp SVG in ấn, HTML và phiên bản tài khoản.", "Có sửa sau khi tạo QR không?", "Có nếu URL giữ nguyên; hãy tạo lại QR khi đổi tên URL.", "Không đăng nhập có tạo được không?", "Có, nhưng dữ liệu khách chỉ nằm trong trình duyệt hiện tại."),
        D("Đăng nhập rồi tạo thiệp bằng URL, tên cặp đôi, ngày cưới và mật khẩu quản trị.", "Thêm ảnh, video, nhạc, bản đồ, tài khoản và sổ lưu bút trong trang quản trị.", "Kiểm tra bố cục, phạm vi công khai, tìm kiếm và OG trước khi chia sẻ.", "Biên tập thiệp", "Quản lý thông tin, thứ tự mục và chủ đề tại một nơi.", "Đa phương tiện và bản đồ", "Đăng thư viện, video, nhạc, tọa độ và liên kết bản đồ.", "Chia sẻ và vận hành", "Cấu hình sổ lưu bút, tài khoản, tìm kiếm, OG và ThankYou.", "Sửa thiệp cũ ở đâu?", "Mở Thiệp của tôi sau khi đăng nhập hoặc nhập mật khẩu tại /slug/admin.", "Ngôn ngữ quản trị có đổi nội dung khách xem không?", "Không. UI quản trị và nội dung công khai tách biệt; hãy lưu nội dung bằng ngôn ngữ mong muốn."),
        D("Kết nối Wedding hoặc tạo địa chỉ ThankYou độc lập.", "Thêm lời cảm ơn, ảnh, thông tin tài khoản/liên hệ tùy chọn và phạm vi công khai.", "Kiểm tra tiêu đề, mô tả và ảnh chia sẻ trước khi gửi.", "Lời cảm ơn", "Tóm tắt lời tri ân và kỷ niệm sau sự kiện trên trang di động.", "Ảnh và liên hệ", "Chọn chia sẻ ảnh, tài khoản hoặc thông tin liên hệ.", "URL riêng và OG", "Dùng địa chỉ cùng ảnh xem trước riêng cho mạng xã hội.", "Dùng không cần Wedding được không?", "Được; có thể dùng độc lập hoặc liên kết với thiệp cũ.", "Phải dùng lại ảnh thiệp không?", "Không; có thể dùng lại hoặc tải ảnh và OG riêng."),
        D("Tạo album gia đình và chọn quyền riêng tư, tìm kiếm.", "Mời thành viên rồi đăng ảnh, video và câu chuyện.", "Kiểm tra quyền thành viên và chính sách dọn album chưa dùng.", "Dòng thời gian riêng", "Lưu kỷ niệm theo thời gian và tránh kết quả tìm kiếm thông thường.", "Mời gia đình", "Cùng quản lý bằng liên kết mời và quyền.", "Ảnh và câu chuyện", "Xem phương tiện, bình luận và chuyện gia đình tại một nơi.", "Album có lên công cụ tìm kiếm không?", "Mặc định riêng tư và noindex; hãy xác nhận phạm vi trong cài đặt.", "Album trống có giữ mãi không?", "Album mới chưa có bài đầu tiên trong thời hạn thông báo có thể bị dọn."),
        D("Cài CCTV Agent trên PC Windows nối với camera.", "Đăng ký RTSP và tên camera rồi kiểm tra chuyển đổi HLS.", "Mở trình duyệt để kiểm tra kênh và liên kết công khai/quản trị.", "RTSP sang HLS", "Chuyển tiếp RTSP thành HLS dùng được trong trình duyệt.", "Nhiều camera", "Chuyển kênh và xem trạng thái tại một màn hình.", "Xem từ xa", "Dùng liên kết theo quyền trên PC và điện thoại.", "Không có Agent xem được không?", "Không. Agent phải chạy trên PC Windows truy cập được camera.", "Vì sao có độ trễ?", "Chuyển đổi HLS và bộ đệm mạng tạo ra độ trễ ngắn."),
        D("Xem nội dung, giá và điều kiện của sản phẩm hoặc dịch vụ phát triển.", "Kiểm tra giỏ hàng, đơn rồi thanh toán hoặc tư vấn.", "Theo dõi giao hàng/cung cấp trong lịch sử đơn.", "Sản phẩm trực tiếp", "Hiển thị hàng hóa và dịch vụ do CodeMaru cung cấp.", "Quản lý đơn", "Xem đơn, giao hàng, hủy và hoàn tiền.", "Tài khoản chung", "Quản lý mua hàng và hỗ trợ bằng đăng nhập CodeMaru.", "Ai bán sản phẩm?", "Trang chi tiết nêu nhà cung cấp, điều kiện và mục do CodeMaru vận hành.", "Dịch vụ tùy chỉnh mua ngay được không?", "Gói cố định có thể đặt; việc tùy chỉnh bắt đầu sau khi duyệt yêu cầu và báo giá."),
        D("Nhập giới thiệu, kỹ năng, kinh nghiệm và liên kết ngoài.", "Thêm vai trò, kết quả, ảnh, video, kho mã cho từng dự án.", "Đặt phạm vi công khai và OG rồi chia sẻ URL portfolio.", "Hồ sơ dự án", "Tóm tắt trách nhiệm, kết quả và vận hành theo dự án.", "Phương tiện và liên kết", "Kết hợp ảnh, video, GitHub và dịch vụ thực tế.", "Hồ sơ công khai", "Quản lý phạm vi, tìm kiếm và xem trước liên kết.", "Có phải công khai mọi dự án không?", "Không; có thể ẩn bản nháp và chỉ xuất bản mục đã chọn.", "Nên dùng ảnh cỡ nào?", "Ảnh danh sách vuông, ảnh chia sẻ 1200×630px và banner ngang."),
        D("Cài các gói Dreamine.MVVM NuGet cần cho ứng dụng.", "Tạo ViewModel bằng thuộc tính, lệnh, generator, Locator và DI.", "Kết nối cùng ViewModel với WPF, Blazor hoặc Hybrid UI.", "Core và Generators", "Sinh trạng thái, lệnh và mã lặp khi biên dịch.", "Locator và DI", "Tiêm ViewModel và dịch vụ với ít phụ thuộc nền tảng.", "WPF và Blazor Hybrid", "Chia sẻ miền và ViewModel giữa desktop và web.", "Đây có phải trình tạo giao diện không?", "Không; đây là framework MVVM, generator, DI và tích hợp WPF/Blazor.", "Cài gói nào trước?", "Bắt đầu với Dreamine.MVVM.Core rồi thêm Generators, Locators, Hybrid.Wpf khi cần."));

    private static IReadOnlyDictionary<string, ServiceGuideDetails> Western(string language) => language switch
    {
        "es" => Spanish(),
        "fr" => French(),
        "it" => Italian(),
        _ => Portuguese()
    };

    private static IReadOnlyDictionary<string, ServiceGuideDetails> Spanish() => L(
        D("Introduce la marca, el nombre, los contactos y la URL pública de ambas caras.", "Actualiza el QR, comprueba la página móvil y exporta SVG, HTML o vCard.", "Inicia sesión para guardar varias tarjetas y recuperar sus versiones.", "Editor a dos caras", "Ajusta tipografía, tamaño, color y fondo por cada cara.", "QR y vCard", "Abre el perfil público y permite guardar el contacto.", "Exportación e historial", "Genera SVG de impresión, HTML y versiones de la cuenta.", "¿Puedo editar después de crear el QR?", "Sí, mientras mantengas la URL pública; vuelve a generar el QR si cambia.", "¿Puedo crear sin iniciar sesión?", "Sí, pero los datos de invitado solo quedan en este navegador."),
        D("Inicia sesión y crea la invitación con URL, nombres, fecha y contraseña de administración.", "Añade fotos, vídeo, música, mapa, cuentas y libro de visitas desde Administración.", "Revisa diseño, visibilidad, búsqueda y vista previa OG antes de compartir.", "Editor de invitaciones", "Gestiona datos, orden de secciones y tema en un solo lugar.", "Multimedia y mapa", "Publica galería, vídeo, música, ubicación y enlaces de mapas.", "Compartir y operar", "Configura libro de visitas, cuentas, SEO, OG y ThankYou.", "¿Dónde edito una invitación existente?", "Abre Mis invitaciones o usa /slug/admin con la contraseña administrativa.", "¿El idioma de administración cambia el contenido público?", "No. La interfaz y el texto para invitados se guardan por separado."),
        D("Conecta Wedding o crea una dirección ThankYou independiente.", "Añade el mensaje, fotos, contactos opcionales y visibilidad.", "Revisa el título, la descripción y la imagen social antes de compartir.", "Mensaje de agradecimiento", "Presenta recuerdos y agradecimientos en una página móvil.", "Fotos y contactos", "Comparte de forma opcional imágenes y datos útiles.", "URL y OG propios", "Usa una dirección y vista previa independientes.", "¿Funciona sin Wedding?", "Sí, puede ser independiente o enlazarse a una invitación.", "¿Debo reutilizar las fotos?", "No, puedes reutilizarlas o subir fotos y OG exclusivos."),
        D("Crea el álbum familiar y define privacidad y búsqueda.", "Invita a familiares y publica fotos, vídeos e historias.", "Revisa permisos y la política de limpieza de álbumes sin uso.", "Cronología privada", "Guarda recuerdos fuera de los resultados de búsqueda normales.", "Invitaciones familiares", "Colabora con enlaces de invitación y permisos.", "Fotos e historias", "Consulta multimedia, comentarios y relatos familiares.", "¿Aparece en buscadores?", "Es privado y no indexado por defecto; revisa el alcance al compartir.", "¿Se conserva un álbum vacío?", "Un álbum nuevo sin primera publicación puede eliminarse tras el plazo indicado."),
        D("Instala CCTV Agent en el PC Windows conectado a las cámaras.", "Registra las URL RTSP y comprueba la conversión HLS.", "Verifica canales y enlaces públicos o administrativos en el visor.", "RTSP a HLS", "Retransmite vídeo en un formato compatible con el navegador.", "Varias cámaras", "Cambia de canal y comprueba su estado en una pantalla.", "Vista remota", "Accede desde PC o móvil según los permisos.", "¿Funciona sin Agent?", "No. Agent debe ejecutarse en el PC que puede acceder a las cámaras.", "¿Por qué hay retardo?", "La conversión HLS y el búfer de red añaden una pequeña latencia."),
        D("Consulta producto o servicio, precio y condiciones.", "Revisa carrito y pedido antes de pagar o solicitar asesoría.", "Sigue la entrega o prestación desde el historial de pedidos.", "Oferta directa", "Productos y servicios definidos ofrecidos por CodeMaru.", "Gestión de pedidos", "Consulta compra, entrega, cancelación y reembolso.", "Cuenta compartida", "Mantén compras y soporte con tu inicio de sesión CodeMaru.", "¿Quién vende?", "Cada ficha identifica proveedor, condiciones y artículos directos de CodeMaru.", "¿Puedo comprar desarrollo a medida al instante?", "Los paquetes cerrados sí; los personalizados requieren alcance y presupuesto."),
        D("Completa perfil, tecnologías, experiencia y enlaces externos.", "Añade función, resultados, medios, repositorio y enlace por proyecto.", "Define visibilidad y OG y comparte la dirección del portfolio.", "Casos de proyecto", "Explica responsabilidades, resultados y experiencia operativa.", "Medios y enlaces", "Combina imágenes, vídeo, GitHub y servicio publicado.", "Perfil público", "Controla visibilidad, búsqueda y vista previa del enlace.", "¿Debo publicar todos los proyectos?", "No, conserva borradores ocultos y publica solo los elegidos.", "¿Qué tamaños de imagen convienen?", "Miniatura cuadrada, imagen social de 1200×630px y banner horizontal."),
        D("Instala los paquetes Dreamine.MVVM NuGet necesarios.", "Crea ViewModels con propiedades, comandos, generadores, Locator y DI.", "Conecta el mismo ViewModel a WPF, Blazor o Hybrid.", "Core y Generators", "Genera estado observable, comandos y código repetitivo.", "Locator y DI", "Inyecta ViewModels y servicios con menos acoplamiento.", "WPF y Blazor Hybrid", "Comparte dominio y ViewModels entre escritorio y web.", "¿Es un diseñador visual?", "No, es un framework de MVVM, generación, DI e integración WPF/Blazor.", "¿Qué paquete instalo primero?", "Empieza con Dreamine.MVVM.Core y añade Generators, Locators y Hybrid.Wpf según necesites."));

    private static IReadOnlyDictionary<string, ServiceGuideDetails> French() => L(
        D("Saisissez la marque, le nom, les contacts et l’URL publique des deux faces.", "Actualisez le QR, vérifiez la page mobile puis exportez SVG, HTML ou vCard.", "Connectez-vous pour conserver plusieurs cartes et leurs versions.", "Éditeur recto-verso", "Réglez police, taille, couleur et arrière-plan par face.", "QR et vCard", "Ouvrez le profil public et enregistrez le contact.", "Exports et historique", "Créez le SVG d’impression, le HTML et les versions du compte.", "Puis-je modifier après avoir créé le QR ?", "Oui si l’URL publique reste identique ; régénérez le QR si elle change.", "Puis-je créer sans connexion ?", "Oui, mais les données invité restent dans ce navigateur."),
        D("Connectez-vous puis créez l’invitation avec URL, noms, date et mot de passe admin.", "Ajoutez photos, vidéo, musique, carte, comptes et livre d’or dans l’administration.", "Contrôlez mise en page, visibilité, recherche et aperçu OG avant partage.", "Éditeur d’invitation", "Gérez informations, ordre des sections et thème au même endroit.", "Médias et carte", "Publiez galerie, vidéo, musique, lieu et liens cartographiques.", "Partage et gestion", "Configurez livre d’or, comptes, SEO, OG et ThankYou.", "Où modifier une invitation existante ?", "Ouvrez Mes invitations ou /slug/admin avec le mot de passe admin.", "La langue admin change-t-elle le contenu public ?", "Non. L’interface et les textes invités sont enregistrés séparément."),
        D("Reliez Wedding ou créez une adresse ThankYou indépendante.", "Ajoutez message, photos, contacts facultatifs et visibilité.", "Vérifiez titre, description et image sociale avant l’envoi.", "Message de remerciement", "Présentez souvenirs et remerciements sur une page mobile.", "Photos et contacts", "Partagez seulement les médias et informations utiles.", "URL et OG dédiés", "Utilisez une adresse et un aperçu social séparés.", "Fonctionne-t-il sans Wedding ?", "Oui, seul ou relié à une invitation existante.", "Faut-il réutiliser les photos ?", "Non, vous pouvez les reprendre ou importer des médias dédiés."),
        D("Créez l’album familial et définissez confidentialité et recherche.", "Invitez la famille puis publiez photos, vidéos et récits.", "Vérifiez les droits et la règle de nettoyage des albums inutilisés.", "Chronologie privée", "Conservez les souvenirs hors des résultats de recherche ordinaires.", "Invitations famille", "Collaborez avec liens d’invitation et autorisations.", "Photos et récits", "Retrouvez médias, commentaires et histoires familiales.", "L’album apparaît-il dans les moteurs ?", "Il est privé et non indexé par défaut ; vérifiez le partage.", "Un album vide est-il conservé ?", "Un nouvel album sans premier contenu peut être nettoyé après le délai annoncé."),
        D("Installez CCTV Agent sur le PC Windows relié aux caméras.", "Enregistrez les URL RTSP puis contrôlez la conversion HLS.", "Vérifiez canaux et liens publics/admin dans le navigateur.", "RTSP vers HLS", "Relaye la vidéo dans un format compatible navigateur.", "Multi-caméras", "Changez de canal et contrôlez son état sur un écran.", "Consultation distante", "Accédez sur PC ou mobile selon les droits.", "Est-ce possible sans Agent ?", "Non. Agent doit fonctionner sur le PC ayant accès aux caméras.", "Pourquoi y a-t-il un délai ?", "La conversion HLS et la mémoire tampon réseau ajoutent une faible latence."),
        D("Consultez produit ou service, prix et conditions.", "Vérifiez panier et commande avant paiement ou conseil.", "Suivez livraison ou prestation dans l’historique.", "Offres directes", "Produits et services cadrés fournis par CodeMaru.", "Gestion des commandes", "Suivez achat, livraison, annulation et remboursement.", "Compte commun", "Conservez achats et assistance sous votre compte CodeMaru.", "Qui vend ?", "Chaque fiche indique fournisseur, conditions et offres directes CodeMaru.", "Le sur-mesure s’achète-t-il immédiatement ?", "Les offres fixes oui ; le sur-mesure nécessite cadrage et devis."),
        D("Complétez profil, technologies, expérience et liens externes.", "Ajoutez rôle, résultats, médias, dépôt et service pour chaque projet.", "Réglez visibilité et OG puis partagez l’adresse du portfolio.", "Études de projets", "Décrivez responsabilités, résultats et expérience d’exploitation.", "Médias et liens", "Associez images, vidéo, GitHub et service en ligne.", "Profil public", "Contrôlez visibilité, recherche et aperçu du lien.", "Tous les projets doivent-ils être publics ?", "Non, gardez les brouillons masqués et publiez votre sélection.", "Quelles dimensions d’image ?", "Vignette carrée, partage 1200×630px et bannière horizontale."),
        D("Installez les paquets NuGet Dreamine.MVVM nécessaires.", "Créez les ViewModels avec propriétés, commandes, générateurs, Locator et DI.", "Branchez le même ViewModel sur WPF, Blazor ou Hybrid.", "Core et Generators", "Générez état observable, commandes et code répétitif.", "Locator et DI", "Injectez ViewModels et services avec moins de couplage.", "WPF et Blazor Hybrid", "Partagez domaine et ViewModels entre bureau et web.", "Est-ce un concepteur visuel ?", "Non, c’est un framework MVVM, génération, DI et intégration WPF/Blazor.", "Quel paquet installer d’abord ?", "Commencez par Dreamine.MVVM.Core puis ajoutez Generators, Locators et Hybrid.Wpf."));

    private static IReadOnlyDictionary<string, ServiceGuideDetails> Italian() => L(
        D("Inserisci marchio, nome, contatti e URL pubblico per entrambi i lati.", "Aggiorna il QR, verifica la pagina mobile ed esporta SVG, HTML o vCard.", "Accedi per salvare più biglietti e ripristinare le versioni.", "Editor fronte-retro", "Regola font, dimensioni, colore e sfondo per ogni lato.", "QR e vCard", "Apri il profilo pubblico e salva il contatto.", "Esportazione e cronologia", "Crea SVG di stampa, HTML e versioni dell’account.", "Posso modificare dopo aver creato il QR?", "Sì se l’URL resta uguale; rigenera il QR quando cambia.", "Posso creare senza accedere?", "Sì, ma i dati ospite restano solo in questo browser."),
        D("Accedi e crea l’invito con URL, nomi, data e password amministrativa.", "Aggiungi foto, video, musica, mappa, conti e guestbook nell’area Admin.", "Controlla layout, visibilità, ricerca e anteprima OG prima di condividere.", "Editor dell’invito", "Gestisci dati, ordine delle sezioni e tema in un’unica area.", "Media e mappa", "Pubblica galleria, video, musica, luogo e link alle mappe.", "Condivisione e gestione", "Configura guestbook, conti, SEO, OG e ThankYou.", "Dove modifico un invito esistente?", "Apri I miei inviti oppure /slug/admin con la password amministrativa.", "La lingua Admin cambia il contenuto pubblico?", "No. Interfaccia e testi per gli invitati vengono salvati separatamente."),
        D("Collega Wedding o crea un indirizzo ThankYou indipendente.", "Aggiungi messaggio, foto, contatti opzionali e visibilità.", "Controlla titolo, descrizione e immagine social prima dell’invio.", "Messaggio di ringraziamento", "Raccogli ricordi e ringraziamenti in una pagina mobile.", "Foto e contatti", "Condividi solo media e informazioni utili.", "URL e OG dedicati", "Usa un indirizzo e un’anteprima separati.", "Funziona senza Wedding?", "Sì, in modo indipendente o collegato a un invito.", "Devo riutilizzare le foto?", "No, puoi riusarle oppure caricare foto e OG dedicati."),
        D("Crea l’album di famiglia e imposta privacy e ricerca.", "Invita i familiari e pubblica foto, video e storie.", "Controlla permessi e politica per gli album inutilizzati.", "Timeline privata", "Conserva i ricordi fuori dai normali risultati di ricerca.", "Inviti familiari", "Collabora con link d’invito e permessi.", "Foto e storie", "Consulta media, commenti e racconti della famiglia.", "L’album appare nei motori di ricerca?", "È privato e noindex per impostazione predefinita; verifica la condivisione.", "Un album vuoto resta per sempre?", "Un nuovo album senza primo contenuto può essere rimosso dopo il periodo indicato."),
        D("Installa CCTV Agent sul PC Windows collegato alle telecamere.", "Registra gli URL RTSP e verifica la conversione HLS.", "Controlla canali e link pubblici/admin nel browser.", "Da RTSP a HLS", "Ritrasmette il video in un formato compatibile col browser.", "Più telecamere", "Cambia canale e controlla lo stato in una schermata.", "Visualizzazione remota", "Accedi da PC o mobile secondo i permessi.", "Funziona senza Agent?", "No. Agent deve essere in esecuzione sul PC che raggiunge le telecamere.", "Perché c’è ritardo?", "La conversione HLS e il buffer di rete aggiungono una breve latenza."),
        D("Consulta prodotto o servizio, prezzo e condizioni.", "Controlla carrello e ordine prima del pagamento o della consulenza.", "Segui consegna o fornitura dalla cronologia ordini.", "Offerte dirette", "Prodotti e servizi definiti forniti da CodeMaru.", "Gestione ordini", "Controlla acquisto, consegna, annullamento e rimborso.", "Account condiviso", "Mantieni acquisti e supporto con il login CodeMaru.", "Chi vende?", "Ogni scheda indica fornitore, condizioni e offerte dirette CodeMaru.", "Lo sviluppo su misura si acquista subito?", "I pacchetti fissi sì; il lavoro personalizzato richiede ambito e preventivo."),
        D("Completa profilo, tecnologie, esperienza e link esterni.", "Aggiungi ruolo, risultati, media, repository e servizio per progetto.", "Imposta visibilità e OG e condividi l’indirizzo portfolio.", "Casi di progetto", "Descrivi responsabilità, risultati ed esperienza operativa.", "Media e link", "Combina immagini, video, GitHub e servizio online.", "Profilo pubblico", "Controlla visibilità, ricerca e anteprima del link.", "Tutti i progetti devono essere pubblici?", "No, nascondi le bozze e pubblica solo quelli scelti.", "Quali dimensioni usare?", "Miniatura quadrata, condivisione 1200×630px e banner orizzontale."),
        D("Installa i pacchetti NuGet Dreamine.MVVM necessari.", "Crea ViewModel con proprietà, comandi, generatori, Locator e DI.", "Collega lo stesso ViewModel a WPF, Blazor o Hybrid.", "Core e Generators", "Genera stato osservabile, comandi e codice ripetitivo.", "Locator e DI", "Inietta ViewModel e servizi con meno accoppiamento.", "WPF e Blazor Hybrid", "Condividi dominio e ViewModel tra desktop e web.", "È un designer visuale?", "No, è un framework MVVM, generazione, DI e integrazione WPF/Blazor.", "Quale pacchetto installo prima?", "Inizia da Dreamine.MVVM.Core e aggiungi Generators, Locators e Hybrid.Wpf."));

    private static IReadOnlyDictionary<string, ServiceGuideDetails> Portuguese() => L(
        D("Insira marca, nome, contatos e URL pública nas duas faces.", "Atualize o QR, confira a página móvel e exporte SVG, HTML ou vCard.", "Entre para salvar vários cartões e recuperar versões.", "Editor frente e verso", "Ajuste fonte, tamanho, cor e fundo por face.", "QR e vCard", "Abra o perfil público e salve o contato.", "Exportação e histórico", "Gere SVG de impressão, HTML e versões da conta.", "Posso editar depois de criar o QR?", "Sim, mantendo a URL pública; gere outro QR se ela mudar.", "Posso criar sem entrar?", "Sim, mas os dados de visitante ficam apenas neste navegador."),
        D("Entre e crie o convite com URL, nomes, data e senha administrativa.", "Adicione fotos, vídeo, música, mapa, contas e livro de visitas no Admin.", "Revise layout, visibilidade, pesquisa e prévia OG antes de compartilhar.", "Editor do convite", "Gerencie dados, ordem das seções e tema em um só lugar.", "Mídia e mapa", "Publique galeria, vídeo, música, local e links de mapa.", "Compartilhamento e operação", "Configure livro de visitas, contas, SEO, OG e ThankYou.", "Onde edito um convite existente?", "Abra Meus convites ou use /slug/admin com a senha administrativa.", "O idioma do Admin muda o conteúdo público?", "Não. A interface e o texto dos convidados são salvos separadamente."),
        D("Conecte o Wedding ou crie um endereço ThankYou independente.", "Adicione mensagem, fotos, contatos opcionais e visibilidade.", "Confira título, descrição e imagem social antes de enviar.", "Mensagem de agradecimento", "Reúna lembranças e agradecimentos em uma página móvel.", "Fotos e contatos", "Compartilhe apenas mídia e informações úteis.", "URL e OG próprios", "Use endereço e prévia social separados.", "Funciona sem Wedding?", "Sim, de forma independente ou ligado a um convite.", "Preciso reutilizar as fotos?", "Não, reutilize ou envie fotos e OG exclusivos."),
        D("Crie o álbum familiar e defina privacidade e pesquisa.", "Convide familiares e publique fotos, vídeos e histórias.", "Confira permissões e a política de álbuns sem uso.", "Linha do tempo privada", "Guarde lembranças fora da pesquisa comum.", "Convites familiares", "Colabore com links de convite e permissões.", "Fotos e histórias", "Veja mídia, comentários e relatos da família.", "O álbum aparece nos buscadores?", "É privado e noindex por padrão; confira o escopo de compartilhamento.", "Um álbum vazio fica para sempre?", "Um álbum novo sem primeira publicação pode ser limpo após o prazo informado."),
        D("Instale o CCTV Agent no PC Windows ligado às câmeras.", "Cadastre URLs RTSP e confira a conversão HLS.", "Verifique canais e links públicos/admin no navegador.", "RTSP para HLS", "Retransmite vídeo em formato compatível com navegador.", "Várias câmeras", "Troque canais e confira o estado em uma tela.", "Visualização remota", "Acesse no PC ou celular conforme a permissão.", "Funciona sem o Agent?", "Não. O Agent deve rodar no PC que alcança as câmeras.", "Por que há atraso?", "A conversão HLS e o buffer de rede acrescentam pequena latência."),
        D("Consulte produto ou serviço, preço e condições.", "Confira carrinho e pedido antes do pagamento ou consultoria.", "Acompanhe entrega ou serviço no histórico.", "Ofertas diretas", "Produtos e serviços definidos fornecidos pela CodeMaru.", "Gestão de pedidos", "Veja compra, entrega, cancelamento e reembolso.", "Conta compartilhada", "Mantenha compras e suporte no login CodeMaru.", "Quem vende?", "Cada página identifica fornecedor, condições e ofertas diretas CodeMaru.", "Desenvolvimento personalizado é imediato?", "Pacotes fechados podem ser pedidos; projetos sob medida exigem escopo e orçamento."),
        D("Preencha perfil, tecnologias, experiência e links externos.", "Adicione papel, resultados, mídia, repositório e serviço por projeto.", "Defina visibilidade e OG e compartilhe o endereço do portfólio.", "Casos de projeto", "Descreva responsabilidades, resultados e experiência operacional.", "Mídia e links", "Combine imagens, vídeo, GitHub e serviço publicado.", "Perfil público", "Controle visibilidade, pesquisa e prévia do link.", "Todos os projetos devem ser públicos?", "Não, oculte rascunhos e publique apenas os escolhidos.", "Que tamanhos de imagem usar?", "Miniatura quadrada, compartilhamento 1200×630px e banner horizontal."),
        D("Instale os pacotes NuGet Dreamine.MVVM necessários.", "Crie ViewModels com propriedades, comandos, generators, Locator e DI.", "Conecte o mesmo ViewModel a WPF, Blazor ou Hybrid.", "Core e Generators", "Gere estado observável, comandos e código repetitivo.", "Locator e DI", "Injete ViewModels e serviços com menos acoplamento.", "WPF e Blazor Hybrid", "Compartilhe domínio e ViewModels entre desktop e web.", "É um construtor visual?", "Não, é um framework MVVM, geração, DI e integração WPF/Blazor.", "Qual pacote instalar primeiro?", "Comece com Dreamine.MVVM.Core e adicione Generators, Locators e Hybrid.Wpf."));
}
