using Dreamine.UI.Blazor.Localization;

namespace Codemaru.Services;

public sealed class SiteLocalization : DreamineLocalizationService
{
    public string HtmlLanguage => Languages.First(item =>
        string.Equals(item.Code, Language, StringComparison.OrdinalIgnoreCase)).HtmlLanguage ?? Language;

    private static readonly Dictionary<string, Dictionary<string, string>> Texts = new(StringComparer.OrdinalIgnoreCase)
    {
        ["ko"] = new()
        {
            ["language"] = "언어", ["contact"] = "문의하기", ["login"] = "로그인",
            ["nav.home"] = "홈", ["nav.toggle"] = "메뉴 열기/닫기",
            ["theme.label"] = "화면 테마", ["theme.system"] = "시스템", ["theme.light"] = "라이트", ["theme.dark"] = "다크",
            ["screenSettings"] = "화면 설정", ["account"] = "내 계정", ["admin"] = "관리자", ["logout"] = "로그아웃",
            ["about"] = "CodeMaru 소개", ["privacy"] = "개인정보처리방침", ["terms"] = "이용약관",
            ["footer"] = "운영 및 개발: 장민수",
            ["home.kicker"] = "CodeMaru", ["home.title"] = "필요한 디지털 도구를\n직접 만듭니다",
            ["home.lead"] = "명함 QR부터 모바일 청첩장, 감사장, 가족 앨범,\nCCTV 모니터링, 직영 쇼핑몰까지.",
            ["home.services"] = "서비스 둘러보기", ["home.about"] = "CodeMaru 소개",
            ["value.design.title"] = "직접 설계 · 개발", ["value.design.text"] = "필요한 기능을 직접 설계하고 끝까지 책임집니다.",
            ["value.run.title"] = "실제로 운영 중", ["value.run.text"] = "모든 서비스는 실제 운영 경험을 통해 검증됩니다.",
            ["value.improve.title"] = "지속적인 개선", ["value.improve.text"] = "사용자의 피드백을 반영하며 꾸준히 개선합니다.",
            ["services.title"] = "CodeMaru 서비스", ["services.lead"] = "작은 문제를 해결하는 데서 시작해, 실제로 쓰이는 서비스를 만듭니다.",
            ["service.guide"] = "이용 설명서", ["service.open"] = "사이트 보기",
            ["service.dreamine"] = "WPF와 Blazor를 한 코드 흐름으로 묶는 오픈소스 MVVM 프레임워크입니다. ViewModel, Command, 변경 알림 코드를 줄이고 데스크톱과 웹 UI를 함께 설계할 수 있습니다.",
            ["service.cardhybrid"] = "QR 코드 하나로 모바일 소개 페이지와 vCard 연락처 저장을 연결합니다. 명함 디자인, SVG/HTML 출력, AI 배경 제거, 버전 저장까지 한 화면에서 관리합니다.",
            ["service.cardhybrid.action"] = "명함 만들기",
            ["service.wedding"] = "사진, 지도, 방명록, 배경음악, 계좌 안내가 담긴 모바일 청첩장을 만들고 링크 하나로 하객에게 전달합니다.",
            ["service.wedding.action"] = "청첩장 만들기",
            ["service.thankyou"] = "결혼식 이후 전할 감사 인사, 사진, 계좌 안내와 연락처를 모바일 페이지로 정리합니다.",
            ["service.thankyou.action"] = "감사장 만들기",
            ["service.families"] = "가족끼리만 공유하는 비공개 앨범과 타임라인입니다. 사진과 이야기를 검색 엔진 노출 없이 보관합니다.",
            ["service.families.action"] = "바로가기",
            ["service.portfolio"] = ".NET, Blazor, WPF와 서비스 운영 경험을 프로젝트 단위로 정리한 개발자 포트폴리오입니다.",
            ["service.portfolio.action"] = "포트폴리오 보기",
            ["service.cctv"] = "Windows PC의 RTSP 영상을 HLS로 변환해 브라우저에서 확인하고 여러 카메라를 관리합니다.",
            ["service.cctv.action"] = "뷰어 열기",
            ["service.shop"] = "농산물, 소프트웨어와 소규모 개발 용역을 직접 판매하는 CodeMaru 직영 쇼핑몰입니다.",
            ["service.shop.action"] = "쇼핑하기",
            ["about.title"] = "작은 문제부터\n직접 해결합니다",
            ["about.lead"] = "CodeMaru는 장민수가 운영하는 1인 개발 스튜디오입니다. 보기 좋은 시제품에 그치지 않고, 실제로 사용할 서비스를 직접 만들고 운영하며 개선합니다.",
            ["about.contact"] = "개발 문의하기", ["about.github"] = "GitHub",
            ["about.why"] = "필요해서 만들고,\n운영하며 검증합니다",
            ["about.why1"] = "명함을 더 편하게 공유하고 싶어서 CardHybrid를, 가족의 기록을 안전하게 모으기 위해 Families를 만들었습니다.",
            ["about.why2"] = "장비 UI와 데이터베이스, CCTV 모니터링처럼 현장에서 필요했던 도구도 같은 방식으로 해결합니다. 서비스에서 얻은 경험은 오픈소스 Dreamine 프레임워크로 다시 정리합니다.",
            ["about.build"] = "웹과 데스크톱,\n현장을 함께 연결합니다",
            ["about.buildLead"] = "한 화면만 만드는 것이 아니라 서비스가 지속될 수 있는 전체 흐름을 구성합니다.",
            ["about.cta"] = "해결하고 싶은 문제가 있나요?",
            ["about.ctaLead"] = "필요한 기능과 현재 상황을 알려주시면 구현 범위와 현실적인 진행 방법을 함께 검토합니다."
            ,["about.principle.design"] = "직접 설계 · 개발", ["about.principle.designText"] = "문제를 이해하고 구조를 설계한 뒤, 화면부터 데이터와 배포까지 책임집니다.",
            ["about.principle.run"] = "실제 운영", ["about.principle.runText"] = "직접 운영하면서 장애와 사용 흐름을 확인하고, 동작하는 결과로 검증합니다.",
            ["about.principle.improve"] = "지속적인 개선", ["about.principle.improveText"] = "사용자 피드백과 운영 데이터를 반영해 작은 개선을 꾸준히 이어갑니다.",
            ["about.cap.wpf"] = "장비 제어, 모니터링, 업무용 데스크톱 UI",
            ["about.cap.web"] = "웹 서비스, 관리자 페이지, 인증",
            ["about.cap.db"] = "SQLite, SQL Server, MySQL 기반 데이터 구조",
            ["about.cap.cctv"] = "영상 변환, 실시간 모니터링, 원격 뷰어",
            ["about.cap.automation"] = "산업 자동화", ["about.cap.automationText"] = "PLC 연동, 설정·레시피, 현장 운영 도구",
            ["about.cap.oss"] = "Dreamine MVVM 생태계와 재사용 라이브러리"
        },
        ["en"] = new()
        {
            ["language"] = "Language", ["contact"] = "Contact", ["login"] = "Sign in",
            ["nav.home"] = "Home", ["nav.toggle"] = "Open or close menu",
            ["theme.label"] = "Theme", ["theme.system"] = "System", ["theme.light"] = "Light", ["theme.dark"] = "Dark",
            ["screenSettings"] = "Display settings", ["account"] = "My account", ["admin"] = "Admin", ["logout"] = "Sign out",
            ["about"] = "About CodeMaru", ["privacy"] = "Privacy", ["terms"] = "Terms",
            ["footer"] = "Built and operated by Minsu Jang",
            ["home.kicker"] = "CodeMaru", ["home.title"] = "We build the digital tools\nyou actually need",
            ["home.lead"] = "Business-card QR, mobile invitations, thank-you pages, family albums,\nCCTV monitoring, and a directly operated store.",
            ["home.services"] = "Explore services", ["home.about"] = "About CodeMaru",
            ["value.design.title"] = "Designed and built in-house", ["value.design.text"] = "We design every essential feature and take responsibility through delivery.",
            ["value.run.title"] = "Proven in production", ["value.run.text"] = "Every service is validated through real operational experience.",
            ["value.improve.title"] = "Continuously improved", ["value.improve.text"] = "We keep improving with feedback from real users.",
            ["services.title"] = "CodeMaru Services", ["services.lead"] = "We start with small problems and turn them into services people use.",
            ["service.guide"] = "User guide", ["service.open"] = "Visit site",
            ["service.dreamine"] = "An open-source MVVM framework that unifies WPF and Blazor in one development flow while reducing repetitive ViewModel, command, and notification code.",
            ["service.cardhybrid"] = "Connect a mobile profile and vCard download with one QR code. Manage card design, SVG/HTML export, AI background removal, and versions in one place.",
            ["service.cardhybrid.action"] = "Create a card",
            ["service.wedding"] = "Create a mobile wedding invitation with photos, maps, guestbook, music, and payment details, then share it with one link.",
            ["service.wedding.action"] = "Create invitation",
            ["service.thankyou"] = "Organize post-wedding thanks, photos, payment details, and contact information in a mobile page.",
            ["service.thankyou.action"] = "Create thank-you page",
            ["service.families"] = "A private family album and timeline that keeps photos and stories away from search engines.",
            ["service.families.action"] = "Open service",
            ["service.portfolio"] = "A developer portfolio organizing .NET, Blazor, WPF, and production experience by project.",
            ["service.portfolio.action"] = "View portfolio",
            ["service.cctv"] = "Convert RTSP streams from a Windows PC to HLS for browser viewing and multi-camera management.",
            ["service.cctv.action"] = "Open viewer",
            ["service.shop"] = "CodeMaru's directly operated store for produce, software, and small development projects.",
            ["service.shop.action"] = "Shop now",
            ["about.title"] = "Solving real problems,\none at a time",
            ["about.lead"] = "CodeMaru is an independent development studio run by Minsu Jang. We go beyond attractive prototypes to build, operate, and continuously improve services people can actually use.",
            ["about.contact"] = "Discuss a project", ["about.github"] = "GitHub",
            ["about.why"] = "Built from necessity,\nvalidated in operation",
            ["about.why1"] = "CardHybrid began with the need to share business cards more easily, while Families was created to preserve family memories privately.",
            ["about.why2"] = "We solve field problems the same way, from equipment interfaces and databases to CCTV monitoring. Lessons from production become reusable open-source capabilities in Dreamine.",
            ["about.build"] = "Connecting web, desktop,\nand the real world",
            ["about.buildLead"] = "We design the complete flow that keeps a service running, not just a single screen.",
            ["about.cta"] = "Have a problem worth solving?",
            ["about.ctaLead"] = "Tell us what you need and where you are today. We will review a realistic scope and path to delivery."
            ,["about.principle.design"] = "Designed and built in-house", ["about.principle.designText"] = "We understand the problem, design the structure, and own everything from interface to data and deployment.",
            ["about.principle.run"] = "Operated in production", ["about.principle.runText"] = "We observe failures and user flows directly and validate our work with functioning results.",
            ["about.principle.improve"] = "Continuously improved", ["about.principle.improveText"] = "We make steady improvements using user feedback and operational data.",
            ["about.cap.wpf"] = "Equipment control, monitoring, and business desktop UI",
            ["about.cap.web"] = "Web services, admin portals, and authentication",
            ["about.cap.db"] = "Data architecture with SQLite, SQL Server, and MySQL",
            ["about.cap.cctv"] = "Video conversion, live monitoring, and remote viewing",
            ["about.cap.automation"] = "Industrial automation", ["about.cap.automationText"] = "PLC integration, recipes, settings, and field tools",
            ["about.cap.oss"] = "Dreamine MVVM ecosystem and reusable libraries"
        },
        ["es"] = new()
        {
            ["nav.home"] = "Inicio", ["theme.label"] = "Tema", ["theme.system"] = "Sistema", ["theme.light"] = "Claro", ["theme.dark"] = "Oscuro",
            ["language"] = "Idioma", ["contact"] = "Contacto", ["login"] = "Iniciar sesión",
            ["screenSettings"] = "Ajustes de pantalla", ["account"] = "Mi cuenta", ["admin"] = "Administración", ["logout"] = "Cerrar sesión",
            ["about"] = "Acerca de CodeMaru", ["privacy"] = "Privacidad", ["terms"] = "Términos", ["footer"] = "Desarrollado y operado por Minsu Jang",
            ["home.title"] = "Creamos las herramientas digitales\nque realmente necesitas", ["home.lead"] = "QR para tarjetas, invitaciones móviles, agradecimientos, álbumes familiares,\nmonitoreo CCTV y tienda propia.",
            ["home.services"] = "Explorar servicios", ["home.about"] = "Acerca de CodeMaru",
            ["services.title"] = "Servicios de CodeMaru", ["services.lead"] = "Empezamos con pequeños problemas y los convertimos en servicios útiles.",
            ["service.guide"] = "Guía de uso", ["service.open"] = "Visitar sitio",
            ["service.dreamine"] = "Framework MVVM de código abierto que une WPF y Blazor y reduce el código repetitivo.",
            ["service.cardhybrid"] = "Conecta un perfil móvil y una vCard con un QR y gestiona diseño, exportación e historial.", ["service.cardhybrid.action"] = "Crear tarjeta",
            ["service.wedding"] = "Crea una invitación móvil con fotos, mapa, libro de visitas, música y datos de pago.", ["service.wedding.action"] = "Crear invitación",
            ["service.thankyou"] = "Reúne agradecimientos, fotos, datos de pago y contacto en una página móvil.", ["service.thankyou.action"] = "Crear agradecimiento",
            ["service.families"] = "Álbum y cronología privados para guardar recuerdos familiares fuera de buscadores.", ["service.families.action"] = "Abrir servicio",
            ["service.portfolio"] = "Portafolio de proyectos con experiencia en .NET, Blazor, WPF y operación de servicios.", ["service.portfolio.action"] = "Ver portafolio",
            ["service.cctv"] = "Convierte vídeo RTSP a HLS para verlo en el navegador y gestionar varias cámaras.", ["service.cctv.action"] = "Abrir visor",
            ["service.shop"] = "Tienda directa de CodeMaru para productos, software y pequeños proyectos de desarrollo.", ["service.shop.action"] = "Comprar",
            ["about.title"] = "Resolvemos problemas reales,\nuno a uno", ["about.contact"] = "Consultar un proyecto", ["about.cta"] = "¿Tienes un problema por resolver?"
        },
        ["fr"] = new()
        {
            ["nav.home"] = "Accueil", ["theme.label"] = "Thème", ["theme.system"] = "Système", ["theme.light"] = "Clair", ["theme.dark"] = "Sombre",
            ["language"] = "Langue", ["contact"] = "Contact", ["login"] = "Connexion",
            ["screenSettings"] = "Paramètres d’affichage", ["account"] = "Mon compte", ["admin"] = "Administration", ["logout"] = "Déconnexion",
            ["about"] = "À propos de CodeMaru", ["privacy"] = "Confidentialité", ["terms"] = "Conditions", ["footer"] = "Développé et exploité par Minsu Jang",
            ["home.title"] = "Nous créons les outils numériques\ndont vous avez vraiment besoin", ["home.lead"] = "QR de carte de visite, invitations mobiles, remerciements, albums familiaux,\nsurveillance CCTV et boutique directe.",
            ["home.services"] = "Découvrir les services", ["home.about"] = "À propos de CodeMaru",
            ["services.title"] = "Services CodeMaru", ["services.lead"] = "Nous transformons de petits problèmes en services réellement utiles.",
            ["service.guide"] = "Guide d’utilisation", ["service.open"] = "Visiter le site",
            ["service.dreamine"] = "Framework MVVM open source réunissant WPF et Blazor tout en réduisant le code répétitif.",
            ["service.cardhybrid"] = "Relie un profil mobile et une vCard à un QR et gère design, export et historique.", ["service.cardhybrid.action"] = "Créer une carte",
            ["service.wedding"] = "Créez une invitation mobile avec photos, carte, livre d’or, musique et paiement.", ["service.wedding.action"] = "Créer l’invitation",
            ["service.thankyou"] = "Rassemblez remerciements, photos, paiement et contacts sur une page mobile.", ["service.thankyou.action"] = "Créer le remerciement",
            ["service.families"] = "Album et journal privés pour conserver les souvenirs familiaux hors des moteurs de recherche.", ["service.families.action"] = "Ouvrir le service",
            ["service.portfolio"] = "Portfolio de projets couvrant .NET, Blazor, WPF et l’exploitation de services.", ["service.portfolio.action"] = "Voir le portfolio",
            ["service.cctv"] = "Convertit les flux RTSP en HLS pour le navigateur et la gestion multicaméra.", ["service.cctv.action"] = "Ouvrir le lecteur",
            ["service.shop"] = "Boutique CodeMaru pour produits, logiciels et petits projets de développement.", ["service.shop.action"] = "Acheter",
            ["about.title"] = "Résoudre les vrais problèmes,\nun par un", ["about.contact"] = "Discuter d’un projet", ["about.cta"] = "Un problème à résoudre ?"
        },
        ["it"] = new()
        {
            ["nav.home"] = "Home", ["theme.label"] = "Tema", ["theme.system"] = "Sistema", ["theme.light"] = "Chiaro", ["theme.dark"] = "Scuro",
            ["language"] = "Lingua", ["contact"] = "Contatti", ["login"] = "Accedi",
            ["screenSettings"] = "Impostazioni schermo", ["account"] = "Il mio account", ["admin"] = "Amministrazione", ["logout"] = "Esci",
            ["about"] = "Chi è CodeMaru", ["privacy"] = "Privacy", ["terms"] = "Termini", ["footer"] = "Sviluppato e gestito da Minsu Jang",
            ["home.title"] = "Creiamo gli strumenti digitali\nche servono davvero", ["home.lead"] = "QR per biglietti da visita, inviti mobili, ringraziamenti, album di famiglia,\nmonitoraggio CCTV e negozio diretto.",
            ["home.services"] = "Scopri i servizi", ["home.about"] = "Chi è CodeMaru",
            ["services.title"] = "Servizi CodeMaru", ["services.lead"] = "Partiamo da piccoli problemi e creiamo servizi realmente utili.",
            ["service.guide"] = "Guida all’uso", ["service.open"] = "Visita il sito",
            ["service.dreamine"] = "Framework MVVM open source che unisce WPF e Blazor riducendo il codice ripetitivo.",
            ["service.cardhybrid"] = "Collega profilo mobile e vCard con un QR e gestisce design, esportazione e versioni.", ["service.cardhybrid.action"] = "Crea biglietto",
            ["service.wedding"] = "Crea un invito mobile con foto, mappa, messaggi, musica e dati di pagamento.", ["service.wedding.action"] = "Crea invito",
            ["service.thankyou"] = "Raccoglie ringraziamenti, foto, pagamenti e contatti in una pagina mobile.", ["service.thankyou.action"] = "Crea ringraziamento",
            ["service.families"] = "Album e diario privati per conservare i ricordi di famiglia fuori dai motori di ricerca.", ["service.families.action"] = "Apri servizio",
            ["service.portfolio"] = "Portfolio di progetti con esperienza .NET, Blazor, WPF e gestione di servizi.", ["service.portfolio.action"] = "Vedi portfolio",
            ["service.cctv"] = "Converte video RTSP in HLS per browser e gestione di più telecamere.", ["service.cctv.action"] = "Apri visualizzatore",
            ["service.shop"] = "Negozio CodeMaru per prodotti, software e piccoli progetti di sviluppo.", ["service.shop.action"] = "Acquista",
            ["about.title"] = "Risolviamo problemi reali,\nuno alla volta", ["about.contact"] = "Parliamo del progetto", ["about.cta"] = "Hai un problema da risolvere?"
        },
        ["pt"] = new()
        {
            ["nav.home"] = "Início", ["theme.label"] = "Tema", ["theme.system"] = "Sistema", ["theme.light"] = "Claro", ["theme.dark"] = "Escuro",
            ["language"] = "Idioma", ["contact"] = "Contato", ["login"] = "Entrar",
            ["screenSettings"] = "Configurações de exibição", ["account"] = "Minha conta", ["admin"] = "Administração", ["logout"] = "Sair",
            ["about"] = "Sobre a CodeMaru", ["privacy"] = "Privacidade", ["terms"] = "Termos", ["footer"] = "Desenvolvido e operado por Minsu Jang",
            ["home.title"] = "Criamos as ferramentas digitais\nque você realmente precisa", ["home.lead"] = "QR de cartão, convites móveis, agradecimentos, álbuns de família,\nmonitoramento CCTV e loja própria.",
            ["home.services"] = "Explorar serviços", ["home.about"] = "Sobre a CodeMaru",
            ["services.title"] = "Serviços CodeMaru", ["services.lead"] = "Começamos com pequenos problemas e criamos serviços realmente úteis.",
            ["service.guide"] = "Guia de uso", ["service.open"] = "Visitar site",
            ["service.dreamine"] = "Framework MVVM open source que integra WPF e Blazor e reduz código repetitivo.",
            ["service.cardhybrid"] = "Liga perfil móvel e vCard a um QR e gerencia design, exportação e versões.", ["service.cardhybrid.action"] = "Criar cartão",
            ["service.wedding"] = "Crie um convite móvel com fotos, mapa, mensagens, música e dados de pagamento.", ["service.wedding.action"] = "Criar convite",
            ["service.thankyou"] = "Reúna agradecimentos, fotos, pagamentos e contatos numa página móvel.", ["service.thankyou.action"] = "Criar agradecimento",
            ["service.families"] = "Álbum e linha do tempo privados para guardar memórias familiares fora das buscas.", ["service.families.action"] = "Abrir serviço",
            ["service.portfolio"] = "Portfólio de projetos com experiência em .NET, Blazor, WPF e operação.", ["service.portfolio.action"] = "Ver portfólio",
            ["service.cctv"] = "Converte vídeo RTSP em HLS para navegador e gestão de várias câmeras.", ["service.cctv.action"] = "Abrir visualizador",
            ["service.shop"] = "Loja direta CodeMaru para produtos, software e pequenos projetos.", ["service.shop.action"] = "Comprar",
            ["about.title"] = "Resolvendo problemas reais,\num de cada vez", ["about.contact"] = "Conversar sobre um projeto", ["about.cta"] = "Tem um problema para resolver?"
        },
        ["vi"] = new()
        {
            ["nav.home"] = "Trang chủ", ["theme.label"] = "Giao diện", ["theme.system"] = "Hệ thống", ["theme.light"] = "Sáng", ["theme.dark"] = "Tối",
            ["language"] = "Ngôn ngữ", ["contact"] = "Liên hệ", ["login"] = "Đăng nhập",
            ["screenSettings"] = "Cài đặt hiển thị", ["account"] = "Tài khoản", ["admin"] = "Quản trị", ["logout"] = "Đăng xuất",
            ["about"] = "Giới thiệu CodeMaru", ["privacy"] = "Quyền riêng tư", ["terms"] = "Điều khoản",
            ["footer"] = "Phát triển và vận hành: Minsu Jang",
            ["home.kicker"] = "CodeMaru", ["home.title"] = "Chúng tôi tạo ra công cụ số\nmà bạn thực sự cần",
            ["home.lead"] = "QR danh thiếp, thiệp cưới di động, lời cảm ơn, album gia đình,\ngiám sát CCTV và cửa hàng trực tiếp.",
            ["home.services"] = "Khám phá dịch vụ", ["home.about"] = "Giới thiệu CodeMaru",
            ["value.design.title"] = "Tự thiết kế và phát triển", ["value.design.text"] = "Chúng tôi thiết kế chức năng cần thiết và chịu trách nhiệm đến khi hoàn thành.",
            ["value.run.title"] = "Đang vận hành thực tế", ["value.run.text"] = "Mỗi dịch vụ đều được kiểm chứng qua quá trình vận hành thực tế.",
            ["value.improve.title"] = "Cải tiến liên tục", ["value.improve.text"] = "Chúng tôi liên tục cải tiến dựa trên phản hồi của người dùng.",
            ["services.title"] = "Dịch vụ CodeMaru", ["services.lead"] = "Bắt đầu từ vấn đề nhỏ và tạo ra dịch vụ hữu ích trong thực tế.",
            ["service.guide"] = "Hướng dẫn", ["service.open"] = "Xem trang",
            ["service.dreamine"] = "Framework MVVM mã nguồn mở kết nối WPF và Blazor, giúp giảm mã lặp.",
            ["service.cardhybrid"] = "Kết nối hồ sơ di động và vCard bằng một mã QR, quản lý thiết kế, xuất file và phiên bản.", ["service.cardhybrid.action"] = "Tạo danh thiếp",
            ["service.wedding"] = "Tạo thiệp cưới di động với ảnh, bản đồ, lời chúc, nhạc và thông tin thanh toán.", ["service.wedding.action"] = "Tạo thiệp cưới",
            ["service.thankyou"] = "Tổng hợp lời cảm ơn, ảnh, thanh toán và liên hệ trên một trang di động.", ["service.thankyou.action"] = "Tạo trang cảm ơn",
            ["service.families"] = "Album và dòng thời gian riêng tư để lưu kỷ niệm gia đình ngoài công cụ tìm kiếm.", ["service.families.action"] = "Mở dịch vụ",
            ["service.portfolio"] = "Hồ sơ dự án về .NET, Blazor, WPF và kinh nghiệm vận hành dịch vụ.", ["service.portfolio.action"] = "Xem hồ sơ",
            ["service.cctv"] = "Chuyển RTSP sang HLS để xem trên trình duyệt và quản lý nhiều camera.", ["service.cctv.action"] = "Mở trình xem",
            ["service.shop"] = "Cửa hàng CodeMaru bán sản phẩm, phần mềm và dự án phát triển nhỏ.", ["service.shop.action"] = "Mua sắm",
            ["about.title"] = "Giải quyết từng vấn đề\nmột cách trực tiếp",
            ["about.lead"] = "CodeMaru là studio phát triển độc lập do Minsu Jang vận hành. Chúng tôi không dừng ở bản mẫu đẹp mắt mà trực tiếp xây dựng, vận hành và cải tiến các dịch vụ thực sự hữu ích.",
            ["about.contact"] = "Trao đổi dự án", ["about.github"] = "GitHub",
            ["about.why"] = "Tạo ra từ nhu cầu,\nkiểm chứng qua vận hành",
            ["about.why1"] = "CardHybrid ra đời để chia sẻ danh thiếp dễ dàng hơn, còn Families giúp lưu giữ kỷ niệm gia đình một cách riêng tư.",
            ["about.why2"] = "Chúng tôi cũng giải quyết các nhu cầu thực tế như giao diện thiết bị, cơ sở dữ liệu và giám sát CCTV. Kinh nghiệm vận hành được tổng hợp lại trong framework mã nguồn mở Dreamine.",
            ["about.build"] = "Kết nối web, máy tính\nvà hiện trường",
            ["about.buildLead"] = "Không chỉ tạo một màn hình, chúng tôi thiết kế toàn bộ luồng để dịch vụ có thể vận hành bền vững.",
            ["about.cta"] = "Bạn có vấn đề cần giải quyết?",
            ["about.ctaLead"] = "Hãy cho chúng tôi biết nhu cầu và tình trạng hiện tại. Chúng tôi sẽ cùng xem xét phạm vi và phương án triển khai thực tế."
        },
        ["ja"] = new()
        {
            ["nav.home"] = "ホーム", ["theme.label"] = "画面テーマ", ["theme.system"] = "システム", ["theme.light"] = "ライト", ["theme.dark"] = "ダーク",
            ["language"] = "言語", ["contact"] = "お問い合わせ", ["login"] = "ログイン",
            ["screenSettings"] = "表示設定", ["account"] = "マイアカウント", ["admin"] = "管理者", ["logout"] = "ログアウト",
            ["about"] = "CodeMaruについて", ["privacy"] = "プライバシー", ["terms"] = "利用規約",
            ["footer"] = "開発・運営：チャン・ミンス",
            ["home.kicker"] = "CodeMaru", ["home.title"] = "本当に必要なデジタルツールを\n自らつくります",
            ["home.lead"] = "名刺QR、モバイル招待状、感謝状、家族アルバム、\nCCTV監視、直営ストアまで。",
            ["home.services"] = "サービスを見る", ["home.about"] = "CodeMaruについて",
            ["value.design.title"] = "自社設計・開発", ["value.design.text"] = "必要な機能を自ら設計し、完成まで責任を持ちます。",
            ["value.run.title"] = "実運用で検証", ["value.run.text"] = "すべてのサービスを実際の運用経験を通じて検証します。",
            ["value.improve.title"] = "継続的な改善", ["value.improve.text"] = "利用者の声を反映し、継続的に改善します。",
            ["services.title"] = "CodeMaruのサービス", ["services.lead"] = "小さな課題から始め、実際に使われるサービスをつくります。",
            ["service.guide"] = "利用ガイド", ["service.open"] = "サイトを見る",
            ["service.dreamine"] = "WPFとBlazorを一つの開発フローでつなぐオープンソースMVVMフレームワークです。反復的なViewModel、Command、変更通知コードを削減します。",
            ["service.cardhybrid"] = "一つのQRコードでモバイルプロフィールとvCard保存をつなぎます。名刺デザイン、SVG/HTML出力、AI背景除去、履歴を一画面で管理します。",
            ["service.cardhybrid.action"] = "名刺を作る",
            ["service.wedding"] = "写真、地図、ゲストブック、BGM、口座案内を含むモバイル招待状を作り、一つのリンクで共有できます。",
            ["service.wedding.action"] = "招待状を作る",
            ["service.thankyou"] = "結婚式後の感謝の言葉、写真、口座案内、連絡先をモバイルページにまとめます。",
            ["service.thankyou.action"] = "お礼ページを作る",
            ["service.families"] = "家族だけで共有する非公開アルバムとタイムラインです。写真や物語を検索エンジンに公開せず保存します。",
            ["service.families.action"] = "サービスを開く",
            ["service.portfolio"] = ".NET、Blazor、WPFとサービス運用経験をプロジェクト別にまとめた開発者ポートフォリオです。",
            ["service.portfolio.action"] = "ポートフォリオを見る",
            ["service.cctv"] = "Windows PCのRTSP映像をHLSに変換し、ブラウザーでの確認と複数カメラ管理を提供します。",
            ["service.cctv.action"] = "ビューアーを開く",
            ["service.shop"] = "農産物、ソフトウェア、小規模開発サービスを直接販売するCodeMaru直営ストアです。",
            ["service.shop.action"] = "買い物する",
            ["about.title"] = "小さな課題から\n直接解決します",
            ["about.lead"] = "CodeMaruはチャン・ミンスが運営する個人開発スタジオです。見栄えの良い試作品で終わらず、実際に使えるサービスを開発・運営し、継続的に改善します。",
            ["about.contact"] = "開発を相談する", ["about.github"] = "GitHub",
            ["about.why"] = "必要から生まれ、\n運用で検証します",
            ["about.why1"] = "CardHybridは名刺をより簡単に共有するため、Familiesは家族の記録を安全に残すために生まれました。",
            ["about.why2"] = "機器UI、データベース、CCTV監視など現場の課題も同じ方法で解決します。運用経験はオープンソースのDreamineへ還元します。",
            ["about.build"] = "Web・デスクトップ・\n現場をつなぎます",
            ["about.buildLead"] = "一つの画面ではなく、サービスを継続運用できる全体の流れを設計します。",
            ["about.cta"] = "解決したい課題はありますか？",
            ["about.ctaLead"] = "必要な機能と現在の状況をお知らせください。現実的な実装範囲と進め方を一緒に検討します。"
            ,["about.principle.design"] = "自社設計・開発", ["about.principle.designText"] = "課題を理解して構造を設計し、画面からデータ、配布まで責任を持ちます。",
            ["about.principle.run"] = "実運用", ["about.principle.runText"] = "自ら運用して障害と利用動線を確認し、動作する成果で検証します。",
            ["about.principle.improve"] = "継続的な改善", ["about.principle.improveText"] = "利用者の声と運用データを反映し、小さな改善を続けます。",
            ["about.cap.wpf"] = "機器制御、監視、業務用デスクトップUI",
            ["about.cap.web"] = "Webサービス、管理画面、認証",
            ["about.cap.db"] = "SQLite、SQL Server、MySQLによるデータ構造",
            ["about.cap.cctv"] = "映像変換、リアルタイム監視、遠隔ビューアー",
            ["about.cap.automation"] = "産業オートメーション", ["about.cap.automationText"] = "PLC連携、設定・レシピ、現場運用ツール",
            ["about.cap.oss"] = "Dreamine MVVMエコシステムと再利用ライブラリ"
        },
        ["zh-hans"] = new()
        {
            ["nav.home"] = "首页", ["theme.label"] = "界面主题", ["theme.system"] = "跟随系统", ["theme.light"] = "浅色", ["theme.dark"] = "深色",
            ["language"] = "语言", ["contact"] = "联系我们", ["login"] = "登录",
            ["screenSettings"] = "显示设置", ["account"] = "我的账户", ["admin"] = "管理后台", ["logout"] = "退出登录",
            ["about"] = "关于 CodeMaru", ["privacy"] = "隐私政策", ["terms"] = "使用条款",
            ["footer"] = "开发与运营：Minsu Jang",
            ["home.kicker"] = "CodeMaru", ["home.title"] = "亲自打造真正需要的\n数字化工具",
            ["home.lead"] = "从名片二维码、移动请柬、感谢页、家庭相册，\n到 CCTV 监控和直营商店。",
            ["home.services"] = "浏览服务", ["home.about"] = "关于 CodeMaru",
            ["value.design.title"] = "自主设计与开发", ["value.design.text"] = "亲自设计所需功能，并负责到底。",
            ["value.run.title"] = "真实运营验证", ["value.run.text"] = "所有服务都通过真实运营经验进行验证。",
            ["value.improve.title"] = "持续改进", ["value.improve.text"] = "根据用户反馈持续优化产品。",
            ["services.title"] = "CodeMaru 服务", ["services.lead"] = "从小问题出发，打造真正有人使用的服务。",
            ["service.guide"] = "使用指南", ["service.open"] = "访问网站",
            ["service.dreamine"] = "连接 WPF 与 Blazor、减少重复代码的开源 MVVM 框架。",
            ["service.cardhybrid"] = "用一个二维码连接移动简介与 vCard，并集中管理设计、导出和版本。", ["service.cardhybrid.action"] = "制作名片",
            ["service.wedding"] = "制作包含照片、地图、留言、音乐和收款信息的移动请柬。", ["service.wedding.action"] = "制作请柬",
            ["service.thankyou"] = "将致谢、照片、收款信息和联系方式整理成移动页面。", ["service.thankyou.action"] = "制作感谢页",
            ["service.families"] = "不被搜索引擎收录的私人家庭相册与时间线。", ["service.families.action"] = "打开服务",
            ["service.portfolio"] = "按项目展示 .NET、Blazor、WPF 与服务运营经验的开发者作品集。", ["service.portfolio.action"] = "查看作品集",
            ["service.cctv"] = "将 RTSP 视频转换为 HLS，在浏览器中查看并管理多台摄像机。", ["service.cctv.action"] = "打开监控",
            ["service.shop"] = "销售产品、软件和小型开发服务的 CodeMaru 直营商店。", ["service.shop.action"] = "立即购买",
            ["about.title"] = "从小问题开始\n亲自解决",
            ["about.lead"] = "CodeMaru 是由 Minsu Jang 运营的独立开发工作室。我们不止制作好看的原型，更亲自构建、运营并持续改进真正可用的服务。",
            ["about.contact"] = "咨询开发项目", ["about.github"] = "GitHub",
            ["about.why"] = "源于真实需求，\n经过运营验证",
            ["about.why1"] = "CardHybrid 为更方便地分享名片而生，Families 则用于安全保存家庭回忆。",
            ["about.why2"] = "设备界面、数据库和 CCTV 监控等现场需求也以同样方式解决。运营经验会沉淀到开源 Dreamine 框架中。",
            ["about.build"] = "连接 Web、桌面端\n与真实现场",
            ["about.buildLead"] = "我们设计的不只是一个页面，而是让服务能够持续运行的完整流程。",
            ["about.cta"] = "有需要解决的问题吗？",
            ["about.ctaLead"] = "请告诉我们所需功能和当前情况，我们会共同评估合理的实现范围与推进方式。"
        },
        ["zh-hant"] = new()
        {
            ["nav.home"] = "首頁", ["theme.label"] = "畫面主題", ["theme.system"] = "跟隨系統", ["theme.light"] = "淺色", ["theme.dark"] = "深色",
            ["language"] = "語言", ["contact"] = "聯絡我們", ["login"] = "登入",
            ["screenSettings"] = "顯示設定", ["account"] = "我的帳戶", ["admin"] = "管理後台", ["logout"] = "登出",
            ["about"] = "關於 CodeMaru", ["privacy"] = "隱私權政策", ["terms"] = "使用條款",
            ["footer"] = "開發與營運：Minsu Jang",
            ["home.kicker"] = "CodeMaru", ["home.title"] = "親自打造真正需要的\n數位工具",
            ["home.lead"] = "從名片 QR Code、行動喜帖、感謝頁、家庭相簿，\n到 CCTV 監控與直營商店。",
            ["home.services"] = "瀏覽服務", ["home.about"] = "關於 CodeMaru",
            ["value.design.title"] = "自主設計與開發", ["value.design.text"] = "親自設計所需功能，並負責到底。",
            ["value.run.title"] = "真實營運驗證", ["value.run.text"] = "所有服務都透過真實營運經驗進行驗證。",
            ["value.improve.title"] = "持續改善", ["value.improve.text"] = "依據使用者回饋持續優化產品。",
            ["services.title"] = "CodeMaru 服務", ["services.lead"] = "從小問題出發，打造真正有人使用的服務。",
            ["service.guide"] = "使用指南", ["service.open"] = "造訪網站",
            ["service.dreamine"] = "連接 WPF 與 Blazor、減少重複程式碼的開源 MVVM 框架。",
            ["service.cardhybrid"] = "用一個 QR Code 連接行動簡介與 vCard，集中管理設計、匯出與版本。", ["service.cardhybrid.action"] = "製作名片",
            ["service.wedding"] = "製作包含照片、地圖、留言、音樂與收款資訊的行動喜帖。", ["service.wedding.action"] = "製作喜帖",
            ["service.thankyou"] = "將致謝、照片、收款資訊與聯絡方式整理成行動頁面。", ["service.thankyou.action"] = "製作感謝頁",
            ["service.families"] = "不被搜尋引擎收錄的私人家庭相簿與時間軸。", ["service.families.action"] = "開啟服務",
            ["service.portfolio"] = "按專案呈現 .NET、Blazor、WPF 與服務營運經驗的開發者作品集。", ["service.portfolio.action"] = "查看作品集",
            ["service.cctv"] = "將 RTSP 影像轉換為 HLS，在瀏覽器查看並管理多台攝影機。", ["service.cctv.action"] = "開啟監控",
            ["service.shop"] = "銷售產品、軟體與小型開發服務的 CodeMaru 直營商店。", ["service.shop.action"] = "立即購買",
            ["about.title"] = "從小問題開始\n親自解決",
            ["about.lead"] = "CodeMaru 是由 Minsu Jang 營運的獨立開發工作室。我們不只製作好看的原型，更親自建置、營運並持續改善真正可用的服務。",
            ["about.contact"] = "諮詢開發專案", ["about.github"] = "GitHub",
            ["about.why"] = "源於真實需求，\n經過營運驗證",
            ["about.why1"] = "CardHybrid 為更方便地分享名片而生，Families 則用於安全保存家庭回憶。",
            ["about.why2"] = "設備介面、資料庫與 CCTV 監控等現場需求也以同樣方式解決。營運經驗會沉澱到開源 Dreamine 框架中。",
            ["about.build"] = "連接 Web、桌面端\n與真實現場",
            ["about.buildLead"] = "我們設計的不只是一個畫面，而是讓服務能夠持續運作的完整流程。",
            ["about.cta"] = "有需要解決的問題嗎？",
            ["about.ctaLead"] = "請告訴我們所需功能與目前情況，我們會共同評估合理的實作範圍與推進方式。"
        }
    };

    public SiteLocalization()
        : base(new DreamineLocalizationCatalog(
            "ko",
            [
                new("en", "US", "English"),
                new("es", "ES", "Español"),
                new("fr", "FR", "Français"),
                new("it", "IT", "Italiano"),
                new("pt", "PT", "Português"),
                new("ko", "KR", "한국어"),
                new("ja", "JP", "日本語"),
                new("zh-hans", "CN", "简体中文", "zh-Hans"),
                new("zh-hant", "HK", "繁體中文", "zh-Hant"),
                new("vi", "VN", "Tiếng Việt")
            ],
            Texts,
            "en"))
    {
    }
}
