<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Wedding.Layouts.Contracts</RootNamespace>
    <AssemblyName>Wedding.Layouts.Contracts</AssemblyName>
  </PropertyGroup>

</Project>
