using System.Globalization;

namespace DreamineVMS.Web.Services;

/// <summary>Localized copy used exclusively by the VMS home page.</summary>
public static class VmsHomeText
{
    private static readonly string[] Codes =
    [
        "en", "es", "fr", "it", "pt", "ko", "ja", "zh-hans", "zh-hant", "vi"
    ];

    // en, es, fr, it, pt, ko, ja, zh-Hans, zh-Hant, vi
    private static readonly Dictionary<string, string[]> Texts = new(StringComparer.OrdinalIgnoreCase)
    {
        ["page.title"] = ["Dreamine VMS — Remote IP Camera Monitoring", "Dreamine VMS — Monitoreo remoto de cámaras IP", "Dreamine VMS — Surveillance à distance des caméras IP", "Dreamine VMS — Monitoraggio remoto delle telecamere IP", "Dreamine VMS — Monitoramento remoto de câmeras IP", "Dreamine VMS — IP 카메라 원격 모니터링", "Dreamine VMS — IPカメラのリモート監視", "Dreamine VMS — IP 摄像头远程监控", "Dreamine VMS — IP 攝影機遠端監控", "Dreamine VMS — Giám sát camera IP từ xa"],
        ["hero.badge"] = ["Free remote CCTV monitoring", "Monitoreo CCTV remoto gratuito", "Surveillance CCTV à distance gratuite", "Monitoraggio CCTV remoto gratuito", "Monitoramento CCTV remoto gratuito", "무료 CCTV 원격 모니터링", "無料のCCTVリモート監視", "免费远程 CCTV 监控", "免費遠端 CCTV 監控", "Giám sát CCTV từ xa miễn phí"],
        ["hero.title.1"] = ["Anywhere,", "Desde cualquier lugar,", "Où que vous soyez,", "Ovunque ti trovi,", "De qualquer lugar,", "어디서든", "どこからでも", "无论身在何处", "無論身在何處", "Ở bất cứ đâu,"],
        ["hero.title.2"] = ["monitor your cameras", "vigila tus cámaras", "surveillez vos caméras", "guarda le tue telecamere", "monitore suas câmeras", "내 카메라를", "カメラを", "都能查看摄像头", "都能查看攝影機", "theo dõi camera của bạn"],
        ["hero.title.3"] = ["in real time", "en tiempo real", "en temps réel", "in tempo reale", "em tempo real", "실시간으로", "リアルタイムで", "实时画面", "即時畫面", "theo thời gian thực"],
        ["hero.subtitle.1"] = ["Just enter your IP camera's RTSP address", "Solo introduce la dirección RTSP de tu cámara IP", "Saisissez simplement l’adresse RTSP de votre caméra IP", "Inserisci l’indirizzo RTSP della tua telecamera IP", "Basta informar o endereço RTSP da sua câmera IP", "IP 카메라 RTSP 주소만 입력하면", "IPカメラのRTSPアドレスを入力するだけで", "只需输入 IP 摄像头的 RTSP 地址", "只需輸入 IP 攝影機的 RTSP 位址", "Chỉ cần nhập địa chỉ RTSP của camera IP"],
        ["hero.subtitle.2"] = ["Start web streaming and mobile viewing instantly", "Empieza al instante a transmitir en la web y a verlo en el móvil", "Lancez instantanément le streaming web et le visionnage mobile", "Avvia subito lo streaming web e la visione da mobile", "Comece imediatamente o streaming na web e a visualização no celular", "즉시 웹 스트리밍 · 모바일 접속 완료", "すぐにWeb配信・モバイル視聴を開始できます", "即可开始网页直播并通过手机观看", "即可開始網頁串流並透過手機觀看", "Bắt đầu phát trực tuyến trên web và xem bằng điện thoại ngay lập tức"],
        ["action.manage"] = ["Manage cameras →", "Gestionar cámaras →", "Gérer les caméras →", "Gestisci telecamere →", "Gerenciar câmeras →", "카메라 관리 →", "カメラ管理 →", "管理摄像头 →", "管理攝影機 →", "Quản lý camera →"],
        ["action.manage.short"] = ["Manage cameras", "Gestionar cámaras", "Gérer les caméras", "Gestisci telecamere", "Gerenciar câmeras", "카메라 관리", "カメラ管理", "管理摄像头", "管理攝影機", "Quản lý camera"],
        ["action.live"] = ["Watch live", "Ver en directo", "Voir en direct", "Guarda in diretta", "Ver ao vivo", "라이브 보기", "ライブを見る", "观看直播", "觀看直播", "Xem trực tiếp"],
        ["action.start"] = ["Start for free →", "Empezar gratis →", "Commencer gratuitement →", "Inizia gratis →", "Comece grátis →", "무료로 시작하기 →", "無料で始める →", "免费开始 →", "免費開始 →", "Bắt đầu miễn phí →"],
        ["action.login"] = ["Sign in", "Iniciar sesión", "Se connecter", "Accedi", "Entrar", "로그인", "ログイン", "登录", "登入", "Đăng nhập"],
        ["live.title"] = ["📹 Live channels", "📹 Canales en directo", "📹 Chaînes en direct", "📹 Canali in diretta", "📹 Canais ao vivo", "📹 라이브 목록", "📹 ライブ一覧", "📹 直播列表", "📹 直播清單", "📹 Danh sách trực tiếp"],
        ["live.empty"] = ["There are no public cameras yet.", "Aún no hay cámaras públicas.", "Aucune caméra publique pour le moment.", "Non ci sono ancora telecamere pubbliche.", "Ainda não há câmeras públicas.", "공개 설정된 카메라가 아직 없습니다.", "公開されているカメラはまだありません。", "目前还没有公开摄像头。", "目前尚無公開攝影機。", "Chưa có camera công khai nào."],
        ["live.camera.count"] = ["{0} public camera(s)", "{0} cámara(s) pública(s)", "{0} caméra(s) publique(s)", "{0} telecamera/e pubblica/e", "{0} câmera(s) pública(s)", "카메라 {0} 대 공개", "公開カメラ {0} 台", "{0} 个公开摄像头", "{0} 台公開攝影機", "{0} camera công khai"],
        ["live.badge"] = ["LIVE", "EN DIRECTO", "EN DIRECT", "IN DIRETTA", "AO VIVO", "LIVE", "ライブ", "直播", "直播", "TRỰC TIẾP"],
        ["download.title"] = ["Download the agent app", "Descargar la aplicación del agente", "Télécharger l’application agent", "Scarica l’app agente", "Baixar o aplicativo agente", "에이전트 앱 다운로드", "エージェントアプリをダウンロード", "下载代理应用", "下載代理程式", "Tải ứng dụng tác nhân"],
        ["download.description"] = ["Install it on the PC connected to your cameras. Sign in after installation and streaming starts automatically.", "Instálala en el PC conectado a tus cámaras. Inicia sesión después de instalarla y la transmisión comenzará automáticamente.", "Installez-la sur le PC connecté à vos caméras. Connectez-vous après l’installation et le streaming démarrera automatiquement.", "Installala sul PC collegato alle telecamere. Dopo l’installazione, accedi e lo streaming partirà automaticamente.", "Instale no PC conectado às câmeras. Entre após a instalação e o streaming começará automaticamente.", "카메라가 연결된 PC에 설치하세요. 설치 후 로그인하면 자동으로 스트리밍이 시작됩니다.", "カメラに接続されたPCへインストールしてください。インストール後にログインすると配信が自動的に始まります。", "请安装到连接摄像头的电脑上。安装后登录，视频流将自动开始。", "請安裝至連接攝影機的電腦。安裝後登入，串流將自動開始。", "Hãy cài đặt trên máy tính kết nối với camera. Sau khi cài đặt, đăng nhập để tự động bắt đầu phát trực tuyến."],
        ["download.req.windows"] = ["Windows 10 / 11 (64-bit)", "Windows 10 / 11 (64 bits)", "Windows 10 / 11 (64 bits)", "Windows 10 / 11 (64 bit)", "Windows 10 / 11 (64 bits)", "Windows 10 / 11 (64비트)", "Windows 10 / 11（64ビット）", "Windows 10 / 11（64 位）", "Windows 10 / 11（64 位元）", "Windows 10 / 11 (64-bit)"],
        ["download.req.ffmpeg"] = ["FFmpeg included automatically — no separate installation", "FFmpeg incluido automáticamente — no requiere instalación adicional", "FFmpeg inclus automatiquement — aucune installation séparée", "FFmpeg incluso automaticamente — nessuna installazione separata", "FFmpeg incluído automaticamente — sem instalação separada", "FFmpeg 자동 포함 — 별도 설치 불필요", "FFmpegを自動同梱 — 別途インストール不要", "自动包含 FFmpeg — 无需另行安装", "自動包含 FFmpeg — 無需另行安裝", "Tự động bao gồm FFmpeg — không cần cài đặt riêng"],
        ["download.req.rtsp"] = ["An IP camera RTSP address is required", "Se requiere la dirección RTSP de una cámara IP", "Une adresse RTSP de caméra IP est requise", "È necessario un indirizzo RTSP della telecamera IP", "É necessário um endereço RTSP de câmera IP", "IP 카메라 RTSP 주소 필요", "IPカメラのRTSPアドレスが必要", "需要 IP 摄像头 RTSP 地址", "需要 IP 攝影機 RTSP 位址", "Cần có địa chỉ RTSP của camera IP"],
        ["download.req.size"] = ["About 300 MB installed · about 90 MB installer", "Aproximadamente 300 MB instalados · instalador de unos 90 MB", "Environ 300 Mo installés · programme d’installation d’environ 90 Mo", "Circa 300 MB installati · installer di circa 90 MB", "Cerca de 300 MB instalados · instalador de aproximadamente 90 MB", "설치 용량 약 300MB · 설치 파일 약 90MB", "インストール容量 約300MB・インストーラー 約90MB", "安装后约 300 MB · 安装程序约 90 MB", "安裝後約 300 MB · 安裝程式約 90 MB", "Dung lượng sau cài đặt khoảng 300 MB · bộ cài khoảng 90 MB"],
        ["download.req.disk"] = ["Disk usage while streaming: about 180 MB/hour per camera (at 400 kbps)", "Uso de disco durante la transmisión: unos 180 MB/hora por cámara (a 400 kbps)", "Utilisation du disque pendant le streaming : environ 180 Mo/heure par caméra (à 400 kbit/s)", "Uso del disco durante lo streaming: circa 180 MB/ora per telecamera (a 400 kbps)", "Uso de disco durante o streaming: cerca de 180 MB/hora por câmera (a 400 kbps)", "스트리밍 중 디스크 사용량: 카메라 1대당 약 180MB/시간 (400kbps 기준)", "配信中のディスク使用量：カメラ1台あたり約180MB/時（400kbpsの場合）", "直播时磁盘用量：每个摄像头约 180 MB/小时（按 400 kbps 计算）", "串流時磁碟用量：每台攝影機約 180 MB/小時（以 400 kbps 計）", "Dung lượng đĩa khi phát trực tuyến: khoảng 180 MB/giờ cho mỗi camera (ở 400 kbps)"],
        ["download.req.cleanup"] = ["Old files are removed automatically when the app or camera restarts", "Los archivos antiguos se eliminan automáticamente al reiniciar la aplicación o la cámara", "Les anciens fichiers sont supprimés automatiquement au redémarrage de l’application ou de la caméra", "I file meno recenti vengono rimossi automaticamente al riavvio dell’app o della telecamera", "Arquivos antigos são removidos automaticamente quando o aplicativo ou a câmera reinicia", "앱 또는 카메라 재시작 시 오래된 파일 자동 정리", "アプリまたはカメラの再起動時に古いファイルを自動削除", "应用或摄像头重启时会自动清理旧文件", "應用程式或攝影機重新啟動時會自動清理舊檔案", "Tệp cũ được tự động dọn dẹp khi ứng dụng hoặc camera khởi động lại"],
        ["download.webview.lead"] = ["The WebView2 Runtime is downloaded automatically during the first installation", "WebView2 Runtime se descarga automáticamente durante la primera instalación", "Le runtime WebView2 est téléchargé automatiquement lors de la première installation", "WebView2 Runtime viene scaricato automaticamente durante la prima installazione", "O WebView2 Runtime é baixado automaticamente na primeira instalação", "최초 설치 시 WebView2 Runtime을 자동으로 다운로드", "初回インストール時にWebView2 Runtimeを自動ダウンロード", "首次安装时会自动下载 WebView2 Runtime", "首次安裝時會自動下載 WebView2 Runtime", "WebView2 Runtime được tự động tải xuống trong lần cài đặt đầu tiên"],
        ["download.webview.detail"] = [". This may take several minutes depending on your internet speed. Please wait on the installation screen.", ". Puede tardar varios minutos según la velocidad de Internet. Espera en la pantalla de instalación.", ". Cette opération peut prendre plusieurs minutes selon votre connexion Internet. Veuillez patienter sur l’écran d’installation.", ". L’operazione può richiedere alcuni minuti in base alla velocità di Internet. Attendi nella schermata di installazione.", ". Isso pode levar alguns minutos, dependendo da velocidade da internet. Aguarde na tela de instalação.", "합니다. 인터넷 속도에 따라 수 분이 걸릴 수 있습니다. 설치 화면에서 기다려 주세요.", "します。インターネット速度によっては数分かかるため、インストール画面でお待ちください。", "。根据网速，可能需要几分钟。请在安装界面耐心等待。", "。依網路速度，可能需要數分鐘。請在安裝畫面耐心等候。", ". Quá trình này có thể mất vài phút tùy theo tốc độ Internet. Vui lòng chờ tại màn hình cài đặt."],
        ["download.admin.prefix"] = ["Administrator privileges are needed only when running from ", "Los privilegios de administrador solo son necesarios al ejecutar desde ", "Les droits d’administrateur ne sont requis que pour une exécution depuis ", "I privilegi di amministratore sono necessari solo durante l’esecuzione da ", "Privilégios de administrador são necessários apenas ao executar em ", "관리자 권한은 ", "管理者権限が必要なのは、", "仅当从", "只有從", "Chỉ cần quyền quản trị viên khi chạy từ "],
        ["download.admin.location"] = ["a folder without write permission, such as C:\\Program Files", "una carpeta sin permiso de escritura, como C:\\Program Files", "un dossier sans autorisation d’écriture, tel que C:\\Program Files", "una cartella senza autorizzazione di scrittura, ad esempio C:\\Program Files", "uma pasta sem permissão de gravação, como C:\\Program Files", "C:\\Program Files 등 쓰기 권한이 없는 폴더", "C:\\Program Filesなどの書き込み権限がないフォルダー", "C:\\Program Files 等没有写入权限的文件夹", "C:\\Program Files 等沒有寫入權限的資料夾", "thư mục không có quyền ghi, chẳng hạn như C:\\Program Files"],
        ["download.admin.suffix"] = [".", ".", ".", ".", ".", "에서 실행할 때만 필요합니다.", "から実行する場合のみです。", "运行时才需要管理员权限。", "執行時才需要系統管理員權限。", "."],
        ["download.default.path"] = ["The default installation path (your AppData folder) works without elevation.", "La ruta de instalación predeterminada (tu carpeta AppData) funciona sin elevación.", "Le chemin d’installation par défaut (votre dossier AppData) fonctionne sans élévation de privilèges.", "Il percorso di installazione predefinito (la cartella AppData) funziona senza privilegi elevati.", "O caminho de instalação padrão (sua pasta AppData) funciona sem elevação de privilégios.", "기본 설치 경로(사용자 AppData)에서는 일반 실행으로 충분합니다.", "既定のインストール先（ユーザーのAppData）では通常実行で十分です。", "在默认安装路径（用户 AppData）下，普通运行即可。", "在預設安裝路徑（使用者 AppData）下，一般執行即可。", "Với đường dẫn cài đặt mặc định (thư mục AppData của người dùng), chỉ cần chạy bình thường."],
        ["download.install"] = ["Install Dreamine VMS", "Instalar Dreamine VMS", "Installer Dreamine VMS", "Installa Dreamine VMS", "Instalar o Dreamine VMS", "Dreamine VMS 설치", "Dreamine VMSをインストール", "安装 Dreamine VMS", "安裝 Dreamine VMS", "Cài đặt Dreamine VMS"],
        ["download.version"] = ["v1.0.0 · Windows 64-bit", "v1.0.0 · Windows de 64 bits", "v1.0.0 · Windows 64 bits", "v1.0.0 · Windows 64 bit", "v1.0.0 · Windows 64 bits", "v1.0.0 · Windows 64비트", "v1.0.0 · Windows 64ビット", "v1.0.0 · Windows 64 位", "v1.0.0 · Windows 64 位元", "v1.0.0 · Windows 64-bit"],
        ["feature.rtsp.title"] = ["RTSP → HLS conversion", "Conversión RTSP → HLS", "Conversion RTSP → HLS", "Conversione RTSP → HLS", "Conversão de RTSP → HLS", "RTSP → HLS 변환", "RTSP → HLS変換", "RTSP → HLS 转换", "RTSP → HLS 轉換", "Chuyển đổi RTSP → HLS"],
        ["feature.rtsp.description"] = ["Enter an IP camera address and FFmpeg automatically converts it to an HLS stream.", "Introduce la dirección de una cámara IP y FFmpeg la convertirá automáticamente en un flujo HLS.", "Saisissez l’adresse d’une caméra IP et FFmpeg la convertira automatiquement en flux HLS.", "Inserisci l’indirizzo di una telecamera IP e FFmpeg lo convertirà automaticamente in uno stream HLS.", "Informe o endereço de uma câmera IP e o FFmpeg o converterá automaticamente em um stream HLS.", "IP 카메라 주소만 입력하면 FFmpeg가 자동으로 HLS 스트림으로 변환합니다.", "IPカメラのアドレスを入力するだけで、FFmpegがHLSストリームへ自動変換します。", "输入 IP 摄像头地址后，FFmpeg 会自动转换为 HLS 视频流。", "輸入 IP 攝影機位址後，FFmpeg 會自動轉換為 HLS 串流。", "Nhập địa chỉ camera IP và FFmpeg sẽ tự động chuyển đổi thành luồng HLS."],
        ["feature.browser.title"] = ["Watch without installing", "Ver sin instalar", "Regarder sans installation", "Guarda senza installare", "Assista sem instalar", "설치 없이 시청", "インストールせずに視聴", "无需安装即可观看", "無需安裝即可觀看", "Xem không cần cài đặt"],
        ["feature.browser.description"] = ["Viewers need no app. One link works anywhere on a phone or PC.", "Los espectadores no necesitan ninguna aplicación. Un solo enlace funciona desde cualquier móvil o PC.", "Aucune application n’est nécessaire pour regarder. Un lien suffit sur smartphone ou PC, où que vous soyez.", "Chi guarda non deve installare app. Basta un link da smartphone o PC, ovunque.", "Quem assiste não precisa de aplicativo. Um link funciona em qualquer lugar, no celular ou PC.", "보는 사람은 앱 설치 불필요. 링크 하나로 어디서든 스마트폰/PC 접속.", "見る側はアプリ不要。リンクひとつで、どこからでもスマートフォンやPCからアクセスできます。", "观看者无需安装应用。只需一个链接，即可随时通过手机或电脑访问。", "觀看者無需安裝應用程式。只要一個連結，即可隨時透過手機或電腦存取。", "Người xem không cần cài ứng dụng. Chỉ với một liên kết, có thể truy cập ở bất cứ đâu bằng điện thoại hoặc máy tính."],
        ["feature.isolation.title"] = ["Tenant isolation", "Aislamiento entre usuarios", "Isolation des locataires", "Isolamento dei tenant", "Isolamento de locatários", "테넌트 격리", "テナント分離", "租户隔离", "租戶隔離", "Cách ly đối tượng thuê"],
        ["feature.isolation.description"] = ["Only you manage your cameras after signing up. External links show only cameras you make public.", "Tras registrarte, solo tú administras tus cámaras. Los enlaces externos muestran únicamente las cámaras que hagas públicas.", "Après l’inscription, vous seul gérez vos caméras. Les liens externes n’affichent que celles que vous rendez publiques.", "Dopo la registrazione, solo tu gestisci le tue telecamere. I link esterni mostrano solo quelle che rendi pubbliche.", "Após o cadastro, somente você gerencia suas câmeras. Links externos mostram apenas as câmeras que você tornar públicas.", "회원가입 후 내 카메라는 나만 관리. 공개 설정한 카메라만 외부 링크에 노출.", "登録後、自分のカメラを管理できるのは自分だけ。外部リンクには公開設定したカメラだけが表示されます。", "注册后只有您能管理自己的摄像头。外部链接仅显示您设为公开的摄像头。", "註冊後只有您能管理自己的攝影機。外部連結僅顯示您設為公開的攝影機。", "Sau khi đăng ký, chỉ bạn quản lý camera của mình. Liên kết bên ngoài chỉ hiển thị camera bạn đặt ở chế độ công khai."],
        ["feature.multi.title"] = ["Multiple cameras", "Varias cámaras", "Plusieurs caméras", "Più telecamere", "Várias câmeras", "다중 카메라", "複数カメラ", "多摄像头", "多攝影機", "Nhiều camera"],
        ["feature.multi.description"] = ["Register multiple cameras and view them together in a grid on one screen.", "Registra varias cámaras y reúnelas en una cuadrícula en una sola pantalla.", "Enregistrez plusieurs caméras et affichez-les ensemble dans une grille sur un seul écran.", "Registra più telecamere e visualizzale insieme in una griglia su un’unica schermata.", "Cadastre várias câmeras e veja todas em uma grade na mesma tela.", "카메라 여러 대를 등록하고 그리드 레이아웃으로 한 화면에 모아보기.", "複数のカメラを登録し、グリッドレイアウトで1画面にまとめて表示できます。", "注册多个摄像头，并通过网格布局在同一屏幕中集中查看。", "註冊多台攝影機，並透過網格版面在同一畫面集中查看。", "Đăng ký nhiều camera và xem cùng nhau theo bố cục lưới trên một màn hình."],
        ["feature.share.title"] = ["Share a public link", "Compartir un enlace público", "Partager un lien public", "Condividi un link pubblico", "Compartilhe um link público", "공개 링크 공유", "公開リンクを共有", "分享公开链接", "分享公開連結", "Chia sẻ liên kết công khai"],
        ["feature.share.prefix"] = ["Share your personal URL ", "Comparte tu URL personal ", "Partagez votre URL personnelle ", "Condividi il tuo URL personale ", "Compartilhe seu URL pessoal ", "내 전용 URL ", "自分専用のURL ", "将您的专属网址 ", "將您的專屬網址 ", "Chia sẻ URL riêng của bạn "],
        ["feature.share.nickname"] = ["nickname", "apodo", "pseudo", "nickname", "apelido", "닉네임", "ニックネーム", "昵称", "暱稱", "biệt-danh"],
        ["feature.share.suffix"] = [" with family and coworkers.", " con familiares y compañeros de trabajo.", " avec votre famille et vos collègues.", " con familiari e colleghi.", " com familiares e colegas de trabalho.", "를 가족·직원과 공유.", "を家族やスタッフと共有できます。", "分享给家人和员工。", "分享給家人和員工。", " với gia đình và đồng nghiệp."],
        ["feature.ffmpeg.title"] = ["Automatic FFmpeg setup", "Instalación automática de FFmpeg", "Installation automatique de FFmpeg", "Configurazione automatica di FFmpeg", "Instalação automática do FFmpeg", "FFmpeg 자동 설치", "FFmpegを自動セットアップ", "自动安装 FFmpeg", "自動安裝 FFmpeg", "Tự động cài đặt FFmpeg"],
        ["feature.ffmpeg.description"] = ["Install one WPF app on the camera PC and FFmpeg is downloaded automatically too.", "Instala una aplicación WPF en el PC de la cámara y FFmpeg también se descargará automáticamente.", "Installez une seule application WPF sur le PC de la caméra et FFmpeg sera également téléchargé automatiquement.", "Installa una sola app WPF sul PC della telecamera e anche FFmpeg verrà scaricato automaticamente.", "Instale um único aplicativo WPF no PC da câmera e o FFmpeg também será baixado automaticamente.", "카메라 PC에 WPF 앱 하나만 설치하면 FFmpeg까지 자동 다운로드 완료.", "カメラ用PCにWPFアプリをひとつインストールすれば、FFmpegも自動でダウンロードされます。", "只需在摄像头电脑上安装一个 WPF 应用，FFmpeg 也会自动下载。", "只需在攝影機電腦上安裝一個 WPF 應用程式，FFmpeg 也會自動下載。", "Chỉ cần cài một ứng dụng WPF trên máy tính camera, FFmpeg cũng sẽ được tự động tải xuống."],
        ["footer.start"] = ["Start free now", "Empezar gratis ahora", "Commencer gratuitement", "Inizia subito gratis", "Comece grátis agora", "지금 무료로 시작", "今すぐ無料で始める", "立即免费开始", "立即免費開始", "Bắt đầu miễn phí ngay"],
        ["footer.account"] = ["I already have an account", "Ya tengo una cuenta", "J’ai déjà un compte", "Ho già un account", "Já tenho uma conta", "이미 계정이 있어요", "すでにアカウントを持っています", "我已有账户", "我已有帳戶", "Tôi đã có tài khoản"],
        ["footer.guide"] = ["Installation guide", "Guía de instalación", "Guide d’installation", "Guida all’installazione", "Guia de instalação", "설치 가이드", "インストールガイド", "安装指南", "安裝指南", "Hướng dẫn cài đặt"]
    };

    public static string Get(string? language, string key)
    {
        if (!Texts.TryGetValue(key, out var values))
            return key;

        var normalized = VmsLocalization.NormalizeLanguageCode(language);
        var index = Array.FindIndex(Codes, code => string.Equals(code, normalized, StringComparison.OrdinalIgnoreCase));
        if (index < 0)
            index = Array.IndexOf(Codes, "ko");

        return values[index];
    }

    public static string Format(string? language, string key, params object?[] args)
    {
        var format = Get(language, key);
        try
        {
            return string.Format(CultureInfo.CurrentCulture, format, args);
        }
        catch (FormatException)
        {
            return format;
        }
    }
}
