<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>GamePlatform</RootNamespace>
    <AssemblyName>GamePlatform.Web</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateProgramFile>false</GenerateProgramFile>
    <UserSecretsId>codemaru-oauth-2ba4e1b2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\100. Library\Database.Abstractions\Dreamine.Database.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\100. Library\Database.Core\Dreamine.Database.Core.csproj" />
    <ProjectReference Include="..\..\..\100. Library\Database.Sqlite\Dreamine.Database.Sqlite.csproj" />
    <ProjectReference Include="..\..\..\100. Library\Identity\Dreamine.Identity.csproj" SetTargetFramework="TargetFramework=net8.0" />
    <ProjectReference Include="..\..\..\100. Library\UI.Blazor\Dreamine.UI.Blazor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
  </ItemGroup>

</Project>
